// ServiceManager - the userspace service supervisor.
//
// SystemManager spawns this program from the init package and hands it a bootstrap
// channel, then over it the init package itself as a shared buffer. ServiceManager
// maps the package and brings up the core services in dependency order: a service
// is started only once every service it depends on is up. Each service is spawned
// with its own report channel; ServiceManager waits for its "online" report,
// records its state, keeps that channel as the service's control channel, and
// relays the report up to SystemManager. In a test boot (per the "MODE" flag the
// kernel sends down the chain) it then exercises the stop path on a leaf service
// and the restart policy and watchdog on a managed canary; a production boot skips
// those drills. It reports in itself and then stands as a supervisor for the life
// of the system.
//
// As a supervisor it does not exit after bring-up: it blocks on every live control
// channel at once and reacts when one needs it. A real service that crashes peer-
// closes its control channel, which the supervisor observes and records. The managed
// canary additionally proves the recovery machinery an unattended edge node depends
// on: a crashed canary is restarted per a back-off policy (escalating once a restart
// budget is spent), and a hung one - detected by a missed heartbeat - is killed and
// restarted. The shell can drive a reverse-dependency `stop <service>` over an admin
// channel (dependents stop before their dependencies), and SystemGraphService can
// query restart / watchdog counters over the `supervisor` interface for observability.

#![no_std]
#![no_main]

extern crate alloc;

use alloc::string::String;
use alloc::vec::Vec;
use proto::system::config;
use proto::system::log;
use proto::system::network;
use proto::system::permission;
use proto::system::process;
use proto::system::supervisor;
use proto::system::{Entry, Error, Field, Severity, SupervisorStat};
use rt::*;

#[path = "service_manager/bootstrap.rs"]
mod bootstrap;
#[path = "service_manager/lifecycle.rs"]
mod lifecycle;

use bootstrap::{bootstrap_serve, console_report, drive_runtime_drivers, emit_event, launch_from_volume, send_factory, start_service, stop_service};
use lifecycle::{depends_on_scoped, has_running_dependent, serve_stats_once, shutdown_all, shutdown_order, verify_shutdown_order};

// A service in the boot manifest: its package entry name, the supervisor's crash
// policy for it, and the names of the services that must be up before it may start.
struct Service {
	name: &'static [u8],
	restart: Restart,
	deps: &'static [&'static [u8]],
}

// The supervisor's crash policy for a managed service (the manifest `restart`
// column): Transparent restarts it per the ladder - its clients re-resolve through
// the broker - while Escalate records it Failed (today's default until a service's
// bootstrap can be re-run from the roots the supervisor holds and its clients have
// migrated to re-resolving).
#[derive(Clone, Copy, PartialEq)]
enum Restart {
	Transparent,
	Escalate,
}

// The core service manifest (`N` and `MANIFEST`), generated by the build script from
// services/manifest.txt - the single source of truth the kernel build script also reads
// for its staging lists, so the runtime table and the staged programs cannot drift.
// The manifest row order is deliberately NOT the start order: DeviceManager, the shell
// and others are listed before LogService though all depend on it, so the dependency
// resolver derives the real order (proving it is driven by declared deps, not position).
// (A fixed size keeps the state arrays on the stack.)
include!(concat!(env!("OUT_DIR"), "/manifest.rs"));

// The lifecycle state ServiceManager tracks for each service.
#[derive(Clone, Copy, PartialEq)]
enum State {
	// Not started yet (its dependencies are not all up).
	Pending,
	// Started and reported in.
	Running,
	// Stopped on request after having run.
	Stopped,
	// Could not be started, or did not report in.
	Failed,
}

// The watchdog's heartbeat deadline: a healthy service answers a probe in one
// synchronous round-trip, far inside this window; a service that misses it is hung.
// (~1s at the 100-ticks-per-second monotonic clock.) The live window is the
// operator's policy (the `service.watchdog-ticks` config key); this is the default
// when the config tree does not answer.
const WATCHDOG_TICKS: u64 = 100;

// The restart budget the supervisor spends on a managed service before it escalates
// (gives up and leaves it failed) rather than restarting it again. The live budget
// is the `service.restart-budget` config key; this is the default when the config
// tree does not answer.
const MAX_RESTARTS: u32 = 3;

// The base back-off between restart attempts, scaled by the attempt count so repeated
// failures wait progressively longer. A bounded one-shot sleep, idle-friendly under the
// test scheduler (which advances finite deadlines).
const RESTART_BACKOFF_TICKS: u64 = 10;

// The supervision knobs read from the config tree once ConfigService serves, with
// the compiled-in constants as defaults. Read once per boot: the supervisor holds
// them for its whole standing life, so a later `set` applies at the next boot.
struct Policy {
	watchdog_ticks: u64,
	restart_budget: u32,
}

// Read the supervision policy (`service.watchdog-ticks`, `service.restart-budget`)
// over the supervisor's ConfigService client; defaults stand when the tree is not
// up (config_client 0) or a key does not parse.
unsafe fn read_policy(config_client: u64) -> Policy {
	let mut policy: Policy = Policy { watchdog_ticks: WATCHDOG_TICKS, restart_budget: MAX_RESTARTS };
	if config_client == 0 {
		return policy;
	}
	let mut client = config::Client::new(ChannelTransport { chan: config_client });
	if let Some(Ok(value)) = client.get("service.watchdog-ticks") {
		if let Ok(ticks) = value.parse::<u64>() {
			if ticks > 0 {
				policy.watchdog_ticks = ticks;
			}
		}
	}
	if let Some(Ok(value)) = client.get("service.restart-budget") {
		if let Ok(budget) = value.parse::<u32>() {
			policy.restart_budget = budget;
		}
	}
	policy
}

// What last took a managed component down, surfaced to observability as a string the
// component itself could not report (a crashed component reports nothing).
#[derive(Clone, Copy, PartialEq)]
enum Failure {
	None,
	Crashed,
	Hung,
	Stopped,
	Bootstrap,
}

impl Failure {
	fn as_bytes(self) -> &'static [u8] {
		match self {
			Failure::None => b"",
			Failure::Crashed => b"crashed",
			Failure::Hung => b"hung",
			Failure::Stopped => b"stopped",
			Failure::Bootstrap => b"bootstrap failed",
		}
	}
}
// The supervisor's per-component bookkeeping: how often it has had to intervene and
// why. Surfaced over the `supervisor` interface and folded into the System Graph.
#[derive(Clone, Copy)]
struct Supervised {
	restarts: u32,
	watchdog_trips: u32,
	failure: Failure,
}

impl Supervised {
	const fn new() -> Supervised {
		Supervised { restarts: 0, watchdog_trips: 0, failure: Failure::None }
	}
}

#[unsafe(no_mangle)]
pub extern "C" fn __user_main(bootstrap: u64) -> ! {
	let mut buf: [u8; 256] = [0u8; 256];

	// 1. receive the init package shared buffer and map it. Keep the handle so we
	//    can share the package with DeviceManager (which spawns drivers from it).
	let (pkg_handle, archive): (u64, &[u8]) = unsafe { recv_package(bootstrap, &mut buf) }.unwrap_or_else(|| exit());
	let pkg_len: usize = archive.len();
	let package: Package = Package::parse(archive).unwrap_or_else(|| exit());

	// 1b. receive (and release) the legacy ramdisk volume buffer. StorageService now
	//     reads its volume from the virtio-blk disk over the block service channel
	//     routed up from DeviceManager, so the embedded ramdisk is no longer used in
	//     the boot path; we drop the capability rather than delegate it. (The kernel's
	//     direct StorageService test still drives the older RAMDISK bootstrap mode.)
	match unsafe { recv_blocking(bootstrap, &mut buf) } {
		Received::Message { len, handle } if handle != 0 && len >= 7 && &buf[..7] == b"RAMDISK" => unsafe {
			close(handle);
		},
		_ => exit(),
	};

	// 1c. receive the boot mode flag ("MODE" + one byte, relayed down the chain from
	//     the kernel). The bring-up self-tests - the stop-path exercise and the canary
	//     crash / hang drills - run only in a test boot (1); a production boot (0)
	//     never deliberately faults a process or stops a service.
	let selftest: bool = match unsafe { recv_blocking(bootstrap, &mut buf) } {
		Received::Message { len, .. } if len == 5 && &buf[..4] == b"MODE" => buf[4] == 1,
		_ => exit(),
	};

	// 2. bring the services up in dependency order. Each pass starts every pending
	//    service whose dependencies are all Running; repeat until a pass makes no
	//    progress (everything started, or what is left is blocked on a failed or
	//    missing dependency). StorageService's service-channel client end is kept
	//    alive in `storage_client` so the service stays standing after it reports in.
	let mut state: [State; N] = [State::Pending; N];
	let mut channels: [u64; N] = [0u64; N];
	// The spawned Process handle of each component, kept so SystemGraphService can be
	// handed a read-only duplicate of every component it observes (the live data source
	// for that component's graph node).
	let mut procs: [u64; N] = [0u64; N];
	// The reason each service that failed to bootstrap gave for going down - the failing
	// step and error it reported over its bootstrap channel before exiting (or a note that
	// it closed without reporting). Empty for a service that came up. Surfaced in the log
	// and the supervisor status view, so a failure is explained rather than silent.
	let mut failure_reason: [String; N] = core::array::from_fn(|_| String::new());
	let mut storage_client: u64 = 0;
	let mut block_client: u64 = 0;
	let mut block2_client: u64 = 0;
	let mut block3_client: u64 = 0;
	let mut media_client: u64 = 0;
	let mut iso_client: u64 = 0;
	let mut block4_client: u64 = 0;
	let mut udf_client: u64 = 0;
	// The USB stick's block channel, handed up by the xhci driver in DeviceManager's
	// phase 2 (0 when no mass-storage device is attached), and the usb StorageService
	// instance's client end minted when that instance bootstraps.
	let mut block5_client: u64 = 0;
	let mut usb_client: u64 = 0;
	// The xHCI driver's USB bus query channel (the typed `usb` inventory), handed up
	// with the phase-2 driver channels and granted to the `lsusb` command through
	// PermissionManager.
	let mut usbq_client: u64 = 0;
	let mut net_frames: u64 = 0;
	let mut net_client: u64 = 0;
	let mut gpu_client: u64 = 0;
	let mut snd_client: u64 = 0;
	let mut input_raw: u64 = 0;
	let mut input_client: u64 = 0;
	// The xhci driver's pointer-event channel (a USB pointing device), folded by
	// InputService alongside the virtio pointer's raw channel.
	let mut usb_pointer: u64 = 0;
	// The console end of the InputService -> ConsoleService pointer-forward channel,
	// minted when InputService bootstraps and handed to ConsoleService when it bootstraps
	// (InputService is a declared dependency of ConsoleService, so it starts first).
	let mut pointer_console: u64 = 0;
	let mut audio_client: u64 = 0;
	let mut time_client: u64 = 0;
	let mut console_client: u64 = 0;
	let mut console_control: u64 = 0;
	let mut log_client: u64 = 0;
	let mut device_client: u64 = 0;
	let mut process_client: u64 = 0;
	let mut config_client: u64 = 0;
	let mut graph_client: u64 = 0;
	// The PermissionManager service-channel client end, kept after PermissionManager
	// bootstraps and later handed to the shell for its `perm` command.
	let mut perm_client: u64 = 0;
	// The ResourceManager service-channel client end, kept after ResourceManager
	// bootstraps and later handed to the shell for its `usage` command.
	let mut res_client: u64 = 0;
	// The SessionService service-channel client end (the session factory), kept after
	// SessionService bootstraps and handed to ConsoleService (so it can mint a session
	// per VT it spawns); the shell's VT 1 session is minted from it into `session1`.
	let mut session_client: u64 = 0;
	// VT 1's session channel, minted once from the session factory and reused across
	// every restart of the VT 1 shell: the supervisor holds it, so the session - and thus
	// the cwd - survives a shell crash / restart. A fresh duplicate is handed to each
	// shell the supervisor (re)starts.
	let mut session1: u64 = 0;
	// The admin channel the shell drives `stop <service>` over (the supervisor keeps the
	// server end), and the channel SystemGraphService queries the `supervisor` interface
	// on (the supervisor serves it). Both are minted when the shell and SystemGraphService
	// bootstrap, and stood on in the supervise loop.
	let mut admin_server: u64 = 0;
	// A second admin channel: the one PermissionManager grants to the sandboxed `stop`
	// command (the supervisor capability), so `stop` run as its own ELF reaches the
	// supervisor's teardown path. The supervisor keeps this server end too and stands on
	// it alongside the shell's in the supervise loop; minted when PermissionManager
	// bootstraps.
	let mut admin_server2: u64 = 0;
	let mut stats_server: u64 = 0;
	// A second supervisor-status channel: the one PermissionManager grants to the sandboxed
	// `lssvc` command (the services capability), so `lssvc` run as its own ELF queries the
	// supervisor's typed status view. The supervisor keeps this server end and stands on it
	// alongside SystemGraphService's in the supervise loop; minted when PermissionManager
	// bootstraps.
	let mut stats_server2: u64 = 0;
	// The supervisor's OWN ProcessService connection - the broker launches transparent-
	// restart replacements through it. Minted right when ProcessService comes up, BEFORE
	// the root is transferred to the shell at its bootstrap (a transferred handle is gone
	// from our table, so a late mint would find nothing to mint from).
	let mut broker_process: u64 = 0;
	// The supervisor's OWN system-volume connection - a restarted ConfigService's
	// persistence backing is re-minted from it. Minted like the process connection
	// above (the storage root is transferred to the shell at its bootstrap).
	let mut broker_storage: u64 = 0;
	// A drill-only PermissionManager connection (test boots drive the `run` op through it
	// to prove a governed tool's grant survives a service restart), minted like the
	// process connection above, before the root transfers to the shell.
	let mut drill_perm: u64 = 0;
	loop {
		let mut progress: bool = false;
		let mut i: usize = 0;
		while i < N {
			if state[i] == State::Pending && deps_satisfied(MANIFEST[i].deps, &state) {
				let mut proc_handle: u64 = 0;
				let started: State = unsafe { start_service(&package, MANIFEST[i].name, bootstrap, pkg_handle, pkg_len, &mut block_client, &mut block2_client, &mut block3_client, &mut block4_client, &mut block5_client, &mut media_client, &mut iso_client, &mut udf_client, &mut usb_client, &mut usbq_client, &mut net_frames, &mut net_client, &mut gpu_client, &mut snd_client, &mut audio_client, &mut time_client, &mut console_client, &mut console_control, &mut storage_client, &mut log_client, &mut device_client, &mut process_client, &mut config_client, &mut input_raw, &mut usb_pointer, &mut input_client, &mut pointer_console, &mut graph_client, &mut perm_client, &mut res_client, &mut session_client, &mut session1, &mut admin_server, &mut admin_server2, &mut stats_server, &mut stats_server2, &procs, &state, &mut proc_handle, &mut channels[i], &mut failure_reason[i], &mut buf) };
				state[i] = started;
				procs[i] = proc_handle;
				progress = true;
				if MANIFEST[i].name == b"process_service" && started == State::Running {
					broker_process = unsafe { service_connect(process_client) }.unwrap_or(0);
				}
				if MANIFEST[i].name == b"storage_service" && started == State::Running {
					broker_storage = unsafe { service_connect(storage_client) }.unwrap_or(0);
				}
				if MANIFEST[i].name == b"permission_manager" && started == State::Running && selftest {
					drill_perm = unsafe { service_connect(perm_client) }.unwrap_or(0);
				}
				// Once the system StorageService is up, drive DeviceManager's phase
				// 2 - it now loads the non-bootstrap drivers from the volume, which is only
				// mountable now. This runs before the driver-consuming services (which depend
				// on process_service, so come up later), so their driver channels are ready.
				if MANIFEST[i].name == b"storage_service" && started == State::Running {
					if let Some(dm) = index_of(b"device_manager") {
						unsafe { drive_runtime_drivers(channels[dm], storage_client, &mut net_frames, &mut gpu_client, &mut snd_client, &mut input_raw, &mut block5_client, &mut usbq_client, &mut usb_pointer, &mut buf) };
					}
					// LogService starts before StorageService, so its volume client (the
					// on-disk journal) is delivered late, like its config client: minted
					// from the freshly mounted system volume and sent on LogService's
					// control channel.
					if let Some(lg) = index_of(b"log_service") {
						if let Some(vol) = unsafe { service_connect(storage_client) } {
							unsafe { send_blocking(channels[lg], b"STORAGE", vol) };
						}
					}
				}
			}
			i += 1;
		}
		if !progress {
			break;
		}
	}

	// The drivers' online facts, snapshotted after bring-up: a non-zero client channel
	// means the driver came up and handed its channel over (DeviceManager launched it and
	// it reported in). Folded into the supervisor's status view, so `lssvc` lists the
	// drivers alongside the managed services - drivers are services too.
	let driver_state: [(&'static [u8], bool); 6] = [
		(b"driver.virtio_blk", block_client != 0),
		(b"driver.virtio_net", net_frames != 0),
		(b"driver.virtio_gpu", gpu_client != 0),
		(b"driver.virtio_snd", snd_client != 0),
		(b"driver.virtio_input", input_raw != 0),
		(b"driver.xhci", block5_client != 0),
	];

	// 3. in a test boot, exercise the stop path on a leaf service. DeviceManager is the
	//    safe choice: nothing depends on it, so stopping it does not tear down the running
	//    system (stopping log_service, storage_service, or the interactive shell would).
	//    This proves the supervisor can stop a service and track the transition, and
	//    the transition is recorded in the journal like the startup events. A production
	//    boot skips the exercise and leaves DeviceManager running.
	let mut sup: [Supervised; N] = [Supervised::new(); N];
	// Fold any bring-up failure into the supervisor's status: a service that reported a
	// bootstrap failure (or closed without reporting) is Failed with its reason already in
	// `failure_reason`, so `lssvc` and the System Graph show why rather than a bare "failed".
	for idx in 0..N {
		if state[idx] == State::Failed {
			sup[idx].failure = Failure::Bootstrap;
		}
	}

	// 3. bring up the managed canary and, in a test boot, exercise the restart policy
	//    and the watchdog on it. The supervisor owns the canary outright (it is not in
	//    the manifest), so it can crash it, hang it, and restart it without disturbing
	//    the running system - proving the unattended-recovery machinery an edge node
	//    depends on. A crash is detected by the control channel peer-closing and
	//    recovered by a policy restart with back-off; a hang is caught by a missed
	//    heartbeat and recovered by a kill + restart. Each transition is reported up
	//    the boot chain and journaled. A production boot spawns and supervises the
	//    canary but never deliberately faults it.
	let (park, _park_peer): (u64, u64) = match unsafe { channel() } {
		Some(pair) => pair,
		None => (0, 0),
	};
	// The supervision knobs, read from the freshly-serving config tree (the canary
	// below and the standing supervisor both run under them).
	let policy: Policy = unsafe { read_policy(config_client) };
	let mut canary_proc: u64 = 0;
	let mut canary_ctrl: u64 = 0;
	let mut canary_sup: Supervised = Supervised::new();
	unsafe {
		let (proc, ctrl): (u64, u64) = spawn_canary(&package, &mut buf);
		if proc != 0 {
			canary_proc = proc;
			canary_ctrl = ctrl;
			send_blocking(bootstrap, b"WatchdogProbe: online", 0);
			emit_event(log_client, b"watchdog_probe", b"online");
			if selftest {
				// prove the heartbeat path on a healthy canary: it answers the probe in time.
				let _alive: bool = heartbeat(canary_ctrl, clock() + policy.watchdog_ticks);
				// crash -> restart: command a real fault, observe the peer-close, restart per policy.
				send_blocking(canary_ctrl, b"CRASH", 0);
				if restart_canary(&package, &mut canary_proc, &mut canary_ctrl, &mut canary_sup, Failure::Crashed, policy.restart_budget, park, &mut buf) {
					send_blocking(bootstrap, b"WatchdogProbe: restarted", 0);
					emit_event(log_client, b"watchdog_probe", b"restarted");
				}
				// hang -> watchdog -> restart: command a hang, miss the heartbeat, kill the hung
				// process, then restart per policy.
				send_blocking(canary_ctrl, b"HANG", 0);
				if !heartbeat(canary_ctrl, clock() + policy.watchdog_ticks) {
					canary_sup.watchdog_trips += 1;
					signal(canary_proc, SIG_KILL);
					if restart_canary(&package, &mut canary_proc, &mut canary_ctrl, &mut canary_sup, Failure::Hung, policy.restart_budget, park, &mut buf) {
						send_blocking(bootstrap, b"WatchdogProbe: recovered", 0);
						emit_event(log_client, b"watchdog_probe", b"recovered");
					}
				}
			}
		}
	}

	// 3b. the transparent-restart drill (a test boot only): kill a REAL standing service
	//     other components hold channels to - ConfigService - restart it per policy, and
	//     prove a live client survives: the canary re-resolves CONFIG through the broker
	//     (its bootstrap channel), round-trips a typed get against the restarted
	//     instance, and proves an un-granted name is denied. This runs BEFORE the
	//     DeviceManager stop drill below, because the replacement is launched from the
	//     system volume, which stopping DeviceManager makes unavailable. The broker
	//     stands for the life of the system (the supervise loop serves resolves and
	//     restarts config on a runtime crash the same way).
	let mut broker: Broker = Broker { config: config_client, device: device_client, process: broker_process, storage: broker_storage };
	if selftest && canary_ctrl != 0 {
		if let Some(cfg) = index_of(b"config_service") {
			if state[cfg] == State::Running && procs[cfg] != 0 {
				unsafe {
					// A real crash: kill the live instance out from under its clients.
					signal(procs[cfg], SIG_KILL);
					if restart_service(&mut broker, cfg, &mut state, &mut channels, &mut procs, &mut sup, policy.restart_budget, park, &mut buf) {
						send_blocking(bootstrap, b"ConfigService: restarted", 0);
						emit_event(log_client, b"config_service", b"restarted");
						// The client-survives proof: the canary resolves and queries the
						// restarted instance, and its STORAGE resolve is denied.
						let vlen: usize = drive_check(canary_ctrl, &broker, &state, &mut buf);
						if vlen > 0 && &buf[..vlen] == b"CONFIG-OK DENIED-OK" {
							send_blocking(bootstrap, b"WatchdogProbe: config client survived", 0);
							emit_event(log_client, b"watchdog_probe", b"config client survived");
						}
						// The first REAL client migration proof: run the governed `config`
						// tool through PermissionManager. PM's config grant died with the
						// killed instance, so mid-launch it re-resolves CONFIG through the
						// broker (served by the DrillTransport, since the supervisor is both
						// the caller and the broker here), and the tool prints the live value
						// from the restarted instance to the captured stdout.
						if drill_perm != 0 {
							if let (Some(pm), Some((output, console))) = (index_of(b"permission_manager"), channel()) {
								let mut perm_drill = permission::Client::new(DrillTransport { perm: drill_perm, pm_ctrl: channels[pm], broker: &broker, state: &state });
								match perm_drill.run("config", "system.name", "vol://system", &console) {
									Some(Ok(started)) => {
										// The tool prints in pieces (the value, then the newline)
										// and exits, closing its stdout - collect to the close.
										let mut printed: Vec<u8> = Vec::new();
										loop {
											match recv_blocking(output, &mut buf) {
												Received::Message { len, .. } => printed.extend_from_slice(&buf[..len]),
												Received::Closed => break,
											}
										}
										if printed == b"LiberSystem\n" {
											send_blocking(bootstrap, b"PermissionManager: config client reconnected", 0);
											emit_event(log_client, b"permission_manager", b"config client reconnected");
										}
										close(started.task);
									}
									_ => {}
								}
								close(output);
							}
						}
					}
				}
			}
		}
	}

	// 3c. in a test boot, exercise the stop path on a leaf service. DeviceManager is the
	//     safe choice: nothing depends on it at this point, so stopping it does not tear
	//     down the running system (stopping log_service, storage_service, or the
	//     interactive shell would). This proves the supervisor can stop a service and
	//     track the transition, and the transition is recorded in the journal like the
	//     startup events. A production boot skips the exercise and leaves DeviceManager
	//     running.
	if selftest {
		if let Some(dev) = index_of(b"device_manager") {
			if state[dev] == State::Running {
				state[dev] = unsafe { stop_service(channels[dev], bootstrap, &mut buf) };
				sup[dev].failure = Failure::Stopped;
				channels[dev] = 0;
				unsafe { emit_event(log_client, b"device_manager", b"stopped") };
			}
		}
	}

	// 3d. verify the graceful-shutdown ordering (a test boot only). The graceful
	//     `poweroff` / `reboot` tears the service tree down in reverse-dependency order
	//     (dependents before their dependencies) before powering the machine off; the
	//     actual teardown + power cannot run under the test harness (system_power would
	//     stop QEMU mid-suite), so this exercises the ordering logic against the live
	//     manifest instead: it computes the order the graceful power path would use and
	//     confirms it covers every running service (no dependency cycle strands one) and
	//     lists each dependent before its dependency. Non-destructive - nothing is torn
	//     down or powered off.
	if selftest {
		let order: Vec<usize> = shutdown_order(&state);
		if verify_shutdown_order(&order, &state) {
			unsafe {
				send_blocking(bootstrap, b"ServiceManager: shutdown order ok", 0);
			}
		}
	}

	// 4. report in once the whole set has settled - every service either Running or,
	//    for the leaf we exercised the stop path on, Stopped, with none left Failed.
	//    Keep `storage_client` alive in case the shell never took it (e.g. a spawn
	//    failure), so StorageService's service channel does not peer-close prematurely;
	//    once the shell owns it, the shell keeps the service standing.
	if all_settled(&state) {
		unsafe {
			send_blocking(bootstrap, b"ServiceManager: online", 0);
		}
	}
	let _ = storage_client;

	// 5. stand as the supervisor. Unlike the earlier design, ServiceManager does not
	//    exit after bring-up: it blocks on every live control channel at once so it can
	//    react when something needs it - a real service crashing (its channel peer-closes),
	//    the canary failing (restart per policy), the shell asking to `stop` a service
	//    (reverse-dependency teardown), or SystemGraphService querying the supervisor state.
	//    No timer stands here, so the loop sleeps at ~0% CPU until an event arrives.
	unsafe {
		supervise(&mut state, &mut channels, &mut sup, &failure_reason, &mut procs, &package, &mut broker, &mut canary_proc, &mut canary_ctrl, &mut canary_sup, &policy, admin_server, admin_server2, stats_server, stats_server2, &driver_state, log_client, park, &mut buf);
	}
	exit();
}

// Whether every service reached a healthy end state - Running, or Stopped for a
// service the supervisor deliberately stopped - with none left Failed or Pending.
// ServiceManager announces itself online only once its whole set is accounted for.
fn all_settled(state: &[State; N]) -> bool {
	let mut i: usize = 0;
	while i < N {
		if state[i] != State::Running && state[i] != State::Stopped {
			return false;
		}
		i += 1;
	}
	true
}

// Whether every dependency in `deps` is in the Running state.
fn deps_satisfied(deps: &[&[u8]], state: &[State; N]) -> bool {
	for &dep in deps {
		match index_of(dep) {
			Some(idx) if state[idx] == State::Running => {}
			_ => return false,
		}
	}
	true
}

// The manifest index of the service named `name`, if any.
fn index_of(name: &[u8]) -> Option<usize> {
	let mut i: usize = 0;
	while i < N {
		if MANIFEST[i].name == name {
			return Some(i);
		}
		i += 1;
	}
	None
}

// The pinned bootstrap set: the services ServiceManager raw-spawns from the
// init package, because they are on the path to mounting the system volume and so cannot
// be loaded from it. media / iso / udf storage reuse the pinned storage_service binary.
// Every other service is loaded from the volume's `bin/` through ProcessService.
fn is_pinned(name: &[u8]) -> bool {
	matches!(name, b"log_service" | b"device_manager" | b"storage_service" | b"media_storage" | b"iso_storage" | b"udf_storage" | b"usb_storage" | b"process_service")
}

// Spawn the managed watchdog canary from the init package, keeping its control channel
// (the canary serves directly on its bootstrap channel, so the supervisor's end is both
// the bootstrap peer and the control channel). Returns (Process, control), or (0, 0) on
// failure. Waits for the canary's "online" report so the caller knows it is up before
// exercising the restart and watchdog paths against it. The canary is raw-spawned from
// the package (not loaded from the volume) because the supervisor exercises it after
// stopping DeviceManager - which drops virtio_blk, so the system volume is unavailable.
unsafe fn spawn_canary(package: &Package, buf: &mut [u8]) -> (u64, u64) {
	unsafe {
		let elf: &[u8] = match package.lookup(b"watchdog_probe") {
			Some(e) => e,
			None => return (0, 0),
		};
		let (ctrl, probe_side): (u64, u64) = match channel() {
			Some(pair) => pair,
			None => return (0, 0),
		};
		let proc: i64 = spawn(elf, probe_side);
		if proc < 0 {
			return (0, 0);
		}
		match recv_blocking(ctrl, buf) {
			Received::Message { .. } => (proc as u64, ctrl),
			Received::Closed => {
				close(proc as u64);
				(0, 0)
			}
		}
	}
}

// Restart the managed canary per the restart policy: record what took it down, drain
// and release its dead endpoints, then - unless the restart budget is spent - back off
// (longer after repeated failures) and respawn, charging one restart. Returns true if a
// replacement is running, false if the budget is exhausted (the caller escalates). The
// canary stands in for the policy a real service restart would follow.
unsafe fn restart_canary(package: &Package, proc: &mut u64, ctrl: &mut u64, sup: &mut Supervised, failure: Failure, budget: u32, park: u64, buf: &mut [u8]) -> bool {
	unsafe {
		sup.failure = failure;
		// Reap the old endpoints so the dead process is fully gone before its replacement.
		drain_closed(*ctrl, buf);
		if *ctrl != 0 {
			close(*ctrl);
			*ctrl = 0;
		}
		if *proc != 0 {
			close(*proc);
			*proc = 0;
		}
		// Spend from the restart budget; once exhausted, escalate rather than restart again.
		if sup.restarts >= budget {
			return false;
		}
		// Back off before the respawn, scaled by the attempt count. A bounded one-shot
		// sleep, so the test scheduler still advances it deterministically.
		sleep_ticks(park, RESTART_BACKOFF_TICKS * (sup.restarts as u64 + 1));
		let (new_proc, new_ctrl): (u64, u64) = spawn_canary(package, buf);
		if new_proc == 0 {
			return false;
		}
		*proc = new_proc;
		*ctrl = new_ctrl;
		sup.restarts += 1;
		true
	}
}

// Drain a channel until its peer is gone, discarding any queued messages. Used to wait
// out a dying process so its control channel is fully closed before it is replaced.
unsafe fn drain_closed(channel: u64, buf: &mut [u8]) {
	unsafe {
		if channel == 0 {
			return;
		}
		loop {
			match recv_blocking(channel, buf) {
				Received::Message { .. } => {}
				Received::Closed => return,
			}
		}
	}
}

// ---- the transparent-restart broker (the Resolver) ---------------------------------
//
// The durable reference a client holds to a service is the capability NAME, not the
// live channel: a component (re-)resolves a name over its kept-alive bootstrap channel
// (RESOLVE_OP + tag), and the supervisor - the one process that spawns every service,
// holds its factory root, and runs the restart ladder - answers with a fresh client
// channel to the CURRENT live instance, minted through the service's CONNECT_OP
// factory. A resolve is answered only if the requester's grant set carries that name
// (the capability discipline enforced on every connect, not just once at spawn), and
// the supervisor is single-threaded, so a resolve aimed at a service it is currently
// restarting is simply answered once the replacement serves - the client experiences
// the crash as latency, not an error.

// The live serve roots the broker mints resolved connections from, updated when a
// restart replaces an instance (the old root died with it). `process` is the
// supervisor's OWN ProcessService connection (minted at bring-up, before the root is
// transferred to the shell), which volume-staged replacements are launched through;
// `storage` is the system-volume root a restarted ConfigService's persistence
// backing is re-minted from.
struct Broker {
	config: u64,
	device: u64,
	process: u64,
	storage: u64,
}

// The grant set of each resolving component: which capability names its resolves may
// answer. The canary is the standing client that proves the broker; PermissionManager
// re-resolves the grantable clients it mints for governed tools (`config` / `set` /
// `lsdev`); ConsoleService re-resolves its per-VT config/device factories;
// SystemGraphService re-resolves its device-nodes connection. A component migrating
// to the SvcTransport / connect_or_resolve wrappers adds its row here.
fn cap_grants(requester: &[u8]) -> &'static [&'static [u8]] {
	match requester {
		b"watchdog_probe" => &[CAP_CONFIG],
		b"permission_manager" => &[CAP_CONFIG, CAP_DEVICE],
		b"console_service" => &[CAP_CONFIG, CAP_DEVICE],
		b"system_graph_service" => &[CAP_DEVICE],
		_ => &[],
	}
}

// The manifest service serving a resolvable capability name.
fn service_of_cap(name: &[u8]) -> Option<&'static [u8]> {
	match name {
		CAP_CONFIG => Some(b"config_service"),
		CAP_DEVICE => Some(b"device_service"),
		_ => None,
	}
}

// Answer one RESOLVE request from `requester` arriving on `chan`: check the grant,
// check the service is alive, and mint a fresh client connection from its live root.
// The reply is b"OK" + the minted channel, or b"DENIED" / b"DOWN" with no handle.
unsafe fn serve_resolve(chan: u64, requester: &[u8], request: &[u8], broker: &Broker, state: &[State; N]) {
	unsafe {
		let name: &[u8] = &request[2..];
		if !cap_grants(requester).iter().any(|&g| g == name) {
			send_blocking(chan, b"DENIED", 0);
			return;
		}
		let root: u64 = match name {
			CAP_CONFIG => broker.config,
			CAP_DEVICE => broker.device,
			_ => 0,
		};
		let alive: bool = match service_of_cap(name).and_then(index_of) {
			Some(idx) => state[idx] == State::Running,
			None => false,
		};
		if root == 0 || !alive {
			send_blocking(chan, b"DOWN", 0);
			return;
		}
		match service_connect(root) {
			Some(minted) => {
				send_blocking(chan, b"OK", minted);
			}
			None => {
				send_blocking(chan, b"DOWN", 0);
			}
		}
	}
}

// Whether a RESOLVE request opens `request` (the reserved broker opcode).
fn is_resolve(request: &[u8]) -> bool {
	request.len() > 2 && u16::from_le_bytes([request[0], request[1]]) == RESOLVE_OP
}

// Whether `request` is a service's clean-exit announcement (the shell on logout). A
// service that sends this before closing its report channel is stopping deliberately,
// so the supervisor records a stop rather than a crash.
fn is_goodbye(request: &[u8]) -> bool {
	request.len() >= 2 && u16::from_le_bytes([request[0], request[1]]) == GOODBYE_OP
}

// Restart a crashed service under the Transparent policy - the ladder a real service
// follows (the Tier-1 shape: a self-contained bootstrap, a volume launch plus a fresh
// serve root, so a replacement serves correctly from scratch). Records the crash,
// reaps the dead endpoints (control, Process, the broker's dead root), and - unless
// the restart budget is spent - backs off, relaunches from the volume through the
// supervisor's own ProcessService connection, re-runs the SERVE bootstrap, and waits
// for the replacement's online report. On success the control channel, Process
// handle, broker root and state are all replaced and one restart is charged; on
// failure the service is left Failed (the caller escalates). Clients holding
// channels to the dead instance reconnect through the broker (serve_resolve above) -
// that is the whole point.
unsafe fn restart_service(broker: &mut Broker, idx: usize, state: &mut [State; N], channels: &mut [u64; N], procs: &mut [u64; N], sup: &mut [Supervised; N], budget: u32, park: u64, buf: &mut [u8]) -> bool {
	unsafe {
		sup[idx].failure = Failure::Crashed;
		state[idx] = State::Failed;
		// Reap every endpoint of the dead instance: the control channel, our Process
		// handle, and the broker's serve root (it died with the instance).
		drain_closed(channels[idx], buf);
		if channels[idx] != 0 {
			close(channels[idx]);
			channels[idx] = 0;
		}
		if procs[idx] != 0 {
			close(procs[idx]);
			procs[idx] = 0;
		}
		let root: &mut u64 = match MANIFEST[idx].name {
			b"config_service" => &mut broker.config,
			b"device_service" => &mut broker.device,
			// A Transparent service whose bootstrap this ladder cannot re-run yet.
			_ => return false,
		};
		if *root != 0 {
			close(*root);
			*root = 0;
		}
		// Spend from the restart budget; once exhausted, escalate rather than restart.
		if sup[idx].restarts >= budget {
			return false;
		}
		sleep_ticks(park, RESTART_BACKOFF_TICKS * (sup[idx].restarts as u64 + 1));
		// Relaunch from the volume and re-run the SERVE bootstrap, like bring-up.
		let (manager_side, service_side): (u64, u64) = match channel() {
			Some(pair) => pair,
			None => return false,
		};
		let proc: i64 = launch_from_volume(broker.process, MANIFEST[idx].name, service_side);
		if proc < 0 {
			return false;
		}
		// A restarted ConfigService gets a fresh persistence backing (the old volume
		// connection died with the crashed instance), so the replacement reloads the
		// persisted tree - a `config set` survives the restart.
		if MANIFEST[idx].name == b"config_service" && broker.storage != 0 && !send_factory(manager_side, b"STORAGE", broker.storage) {
			close(proc as u64);
			return false;
		}
		if !bootstrap_serve(manager_side, root) {
			close(proc as u64);
			return false;
		}
		match recv_blocking(manager_side, buf) {
			Received::Message { .. } => {}
			Received::Closed => {
				close(proc as u64);
				return false;
			}
		}
		channels[idx] = manager_side;
		procs[idx] = proc as u64;
		state[idx] = State::Running;
		sup[idx].restarts += 1;
		sup[idx].failure = Failure::None;
		true
	}
}

// Drive one canary CHECK to its verdict: send the command, then serve the RESOLVE
// requests the canary's client machinery sends back on the same channel until its
// non-resolve reply (the verdict) arrives. Both sides are single-threaded, so the
// interleaving is deterministic. Returns the verdict length in `buf` (0 = the canary
// died mid-check).
unsafe fn drive_check(canary_ctrl: u64, broker: &Broker, state: &[State; N], buf: &mut [u8]) -> usize {
	unsafe {
		if !send_blocking(canary_ctrl, b"CHECK", 0) {
			return 0;
		}
		loop {
			match recv_blocking(canary_ctrl, buf) {
				Received::Message { len, .. } if is_resolve(&buf[..len]) => {
					// Copy the request out of `buf`: serve_resolve round-trips reuse it.
					let mut req: [u8; 64] = [0u8; 64];
					let rlen: usize = len.min(req.len());
					req[..rlen].copy_from_slice(&buf[..rlen]);
					serve_resolve(canary_ctrl, b"watchdog_probe", &req[..rlen], broker, state);
				}
				Received::Message { len, .. } => return len,
				Received::Closed => return 0,
			}
		}
	}
}

// A proto Transport for the drill's PermissionManager round-trip. The supervisor is
// both the CALLER of the `run` op and the BROKER PermissionManager re-resolves its
// dead config grant through mid-request - a plain blocking call would deadlock the
// two single-threaded processes - so this transport serves the RESOLVE requests
// arriving on PermissionManager's control channel while it waits for the typed
// reply. (Only the drill wires this cycle; live callers - the shell, the console -
// are not the broker, so their calls stay plain ChannelTransport.)
struct DrillTransport<'a> {
	perm: u64,
	pm_ctrl: u64,
	broker: &'a Broker,
	state: &'a [State; N],
}

impl proto::codec::Transport for DrillTransport<'_> {
	fn call(&mut self, request: &[u8], request_handle: u64) -> Option<(Vec<u8>, u64)> {
		unsafe {
			if !send_blocking(self.perm, request, request_handle) {
				return None;
			}
			let mut buf: [u8; 64] = [0u8; 64];
			loop {
				let pair: [u64; 2] = [self.perm, self.pm_ctrl];
				match wait_any(&pair, 0) {
					1 => {
						if let Polled::Message { len, .. } = try_recv(self.pm_ctrl, &mut buf) {
							if is_resolve(&buf[..len]) {
								serve_resolve(self.pm_ctrl, b"permission_manager", &buf[..len], self.broker, self.state);
							}
						}
					}
					0 => match recv_vec_blocking(self.perm) {
						ReceivedVec::Message { bytes, handle } => return Some((bytes, handle)),
						ReceivedVec::Closed => return None,
					},
					_ => return None,
				}
			}
		}
	}
}

// Sleep for `ticks` by waiting on the never-written `park` channel until the deadline
// passes. A bounded one-shot wait that sleeps the thread at ~0% CPU; the test scheduler
// advances the finite deadline, so the sleep is deterministic under test.
unsafe fn sleep_ticks(park: u64, ticks: u64) {
	unsafe {
		if park == 0 {
			return;
		}
		wait(park, clock() + ticks);
	}
}

// Stand as the supervisor after bring-up. Each iteration builds a wait set from every
// live control channel - the Running services' (kind 0), the canary's (kind 1), the
// shell's admin channel (kind 2), and SystemGraphService's stats channel (kind 3) - and
// blocks on all of them at once with no deadline, so the supervisor sleeps at ~0% CPU
// until one needs attention. A control channel MESSAGE is a broker RESOLVE (a component
// re-resolving a granted service name - answered with a fresh connection to the live
// instance); a service or the canary peer-closing means it crashed. A crashed service
// under the transparent restart policy (ConfigService) is restarted per the ladder and
// its clients reconnect through the broker; any other service is recorded Failed and
// dropped from the wait set. The canary is restarted per policy; an admin message
// drives a reverse-dependency stop; a stats request is answered over the `supervisor`
// interface. Returns when nothing is left to watch.
unsafe fn supervise(state: &mut [State; N], channels: &mut [u64; N], sup: &mut [Supervised; N], reason: &[String; N], procs: &mut [u64; N], package: &Package, broker: &mut Broker, canary_proc: &mut u64, canary_ctrl: &mut u64, canary_sup: &mut Supervised, policy: &Policy, admin_server: u64, admin_server2: u64, stats_server: u64, stats_server2: u64, drivers: &[(&'static [u8], bool)], log_client: u64, park: u64, buf: &mut [u8]) {
	unsafe {
		let mut admin: u64 = admin_server;
		let mut admin2: u64 = admin_server2;
		let mut stats: u64 = stats_server;
		let mut stats2: u64 = stats_server2;
		loop {
			let mut handles: [u64; N + 5] = [0u64; N + 5];
			let mut kinds: [u8; N + 5] = [0u8; N + 5];
			let mut idxs: [usize; N + 5] = [0usize; N + 5];
			let mut count: usize = 0;
			let mut i: usize = 0;
			while i < N {
				if state[i] == State::Running && channels[i] != 0 {
					handles[count] = channels[i];
					kinds[count] = 0;
					idxs[count] = i;
					count += 1;
				}
				i += 1;
			}
			if *canary_ctrl != 0 {
				handles[count] = *canary_ctrl;
				kinds[count] = 1;
				count += 1;
			}
			if admin != 0 {
				handles[count] = admin;
				kinds[count] = 2;
				count += 1;
			}
			if stats != 0 {
				handles[count] = stats;
				kinds[count] = 3;
				count += 1;
			}
			if admin2 != 0 {
				handles[count] = admin2;
				kinds[count] = 4;
				count += 1;
			}
			if stats2 != 0 {
				handles[count] = stats2;
				kinds[count] = 5;
				count += 1;
			}
			if count == 0 {
				return;
			}
			let ready: i64 = wait_any(&handles[..count], 0);
			if ready < 0 {
				return;
			}
			let r: usize = ready as usize;
			match kinds[r] {
				0 => {
					// A real service's control channel fired: a message is a broker RESOLVE
					// (answered with a fresh connection); a peer-close means it crashed - a
					// service under the transparent restart policy is restarted per the
					// ladder (its clients reconnect through the broker), any other is
					// recorded Failed and dropped from the wait set.
					let idx: usize = idxs[r];
					match try_recv(channels[idx], buf) {
						Polled::Message { len, .. } if is_resolve(&buf[..len]) => {
							// Copy the request out of `buf`: serve_resolve reuses it.
							let mut req: [u8; 64] = [0u8; 64];
							let rlen: usize = len.min(req.len());
							req[..rlen].copy_from_slice(&buf[..rlen]);
							serve_resolve(channels[idx], MANIFEST[idx].name, &req[..rlen], broker, state);
						}
						Polled::Message { len, .. } if is_goodbye(&buf[..len]) => {
							// A deliberate exit (the shell on logout), not a crash: record a
							// clean stop and drop it from the wait set. ConsoleService reloads a
							// fresh shell on the VT, so nothing here restarts it.
							emit_event(log_client, MANIFEST[idx].name, b"exited");
							state[idx] = State::Stopped;
							channels[idx] = 0;
						}
						Polled::Closed => {
							emit_event(log_client, MANIFEST[idx].name, b"crashed");
							console_report(MANIFEST[idx].name, b"crashed");
							if MANIFEST[idx].restart == Restart::Transparent {
								if restart_service(broker, idx, state, channels, procs, sup, policy.restart_budget, park, buf) {
									emit_event(log_client, MANIFEST[idx].name, b"restarted");
									console_report(MANIFEST[idx].name, b"restarted");
								} else {
									emit_event(log_client, MANIFEST[idx].name, b"escalated");
									console_report(MANIFEST[idx].name, b"escalated");
								}
							} else {
								state[idx] = State::Failed;
								sup[idx].failure = Failure::Crashed;
								channels[idx] = 0;
							}
						}
						_ => {}
					}
				}
				1 => {
					// The canary's control channel fired: a message is a broker RESOLVE (the
					// canary is a standing client too); a peer-close means it crashed, so
					// restart it per policy (escalating once the budget is spent).
					match try_recv(*canary_ctrl, buf) {
						Polled::Message { len, .. } if is_resolve(&buf[..len]) => {
							let mut req: [u8; 64] = [0u8; 64];
							let rlen: usize = len.min(req.len());
							req[..rlen].copy_from_slice(&buf[..rlen]);
							serve_resolve(*canary_ctrl, b"watchdog_probe", &req[..rlen], broker, state);
						}
						Polled::Closed => {
							if restart_canary(package, canary_proc, canary_ctrl, canary_sup, Failure::Crashed, policy.restart_budget, park, buf) {
								emit_event(log_client, b"watchdog_probe", b"restarted");
								console_report(b"watchdog_probe", b"restarted");
							} else {
								emit_event(log_client, b"watchdog_probe", b"escalated");
								console_report(b"watchdog_probe", b"escalated");
							}
						}
						_ => {}
					}
				}
				2 => {
					// The shell asked to stop a service; tear down its dependents first.
					if !handle_admin(admin, state, channels, sup, procs, log_client, buf) {
						admin = 0;
					}
				}
				3 => {
					// SystemGraphService queried the supervisor state; answer one request.
					if !serve_stats_once(stats, state, sup, reason, canary_sup, drivers, buf) {
						stats = 0;
					}
				}
				4 => {
					// The sandboxed `stop` tool (granted the supervisor capability) asked to
					// stop a service over its own admin channel; tear down its dependents first.
					if !handle_admin(admin2, state, channels, sup, procs, log_client, buf) {
						admin2 = 0;
					}
				}
				_ => {
					// The sandboxed `lssvc` tool (granted the services capability) queried the
					// supervisor state over its own status channel; answer one request.
					if !serve_stats_once(stats2, state, sup, reason, canary_sup, drivers, buf) {
						stats2 = 0;
					}
				}
			}
		}
	}
}

// Handle one admin request from the shell: the bare name of a service to stop. An
// unknown name (or one already down) gets a NOTFOUND reply; otherwise the service and
// its dependents are torn down and the newline-joined list of what stopped is replied
// for the shell to print. Returns false once the admin channel's peer (the shell) is
// gone, so the supervisor drops it from its wait set.
unsafe fn handle_admin(admin: u64, state: &mut [State; N], channels: &mut [u64; N], sup: &mut [Supervised; N], procs: &[u64; N], log_client: u64, buf: &mut [u8]) -> bool {
	unsafe {
		let len: usize = match recv_blocking(admin, buf) {
			Received::Message { len, .. } => len,
			Received::Closed => return false,
		};
		// Copy the name out of `buf`, since the teardown reuses it to drain control channels.
		let mut namebuf: [u8; 64] = [0u8; 64];
		let nlen: usize = len.min(namebuf.len()).min(buf.len());
		namebuf[..nlen].copy_from_slice(&buf[..nlen]);
		let name: &[u8] = &namebuf[..nlen];
		// A power verb (the shell's graceful `poweroff` / `reboot`): the reserved names
		// `!poweroff` / `!reboot` (a real service name can never start with `!`) mean tear
		// the whole service tree down in reverse-dependency order - flushing LogService's
		// last journal batch first - then power the machine off (or reboot) from here, so no
		// service is killed while a dependent still needs it. system_power does not return;
		// if it somehow does (an unsupported machine), the loop stays alive.
		if name == b"!poweroff" || name == b"!reboot" {
			let action: u64 = if name == b"!reboot" { POWER_REBOOT } else { POWER_OFF };
			shutdown_all(state, channels, sup, procs, log_client, buf);
			system_power(action);
			return true;
		}
		match index_of(name) {
			Some(target) if state[target] == State::Running => {
				let stopped: Vec<u8> = stop_subtree(target, state, channels, sup, procs, log_client, buf);
				let mut reply: Vec<u8> = Vec::new();
				reply.extend_from_slice(b"STOPPED\n");
				reply.extend_from_slice(&stopped);
				send_blocking(admin, &reply, 0);
			}
			_ => {
				send_blocking(admin, b"NOTFOUND", 0);
			}
		}
		true
	}
}

// Tear down a service and every component that transitively depends on it, dependents
// first. The scope is the target plus its reverse-dependency closure, minus the shell
// (the controlling terminal is exempt: force-killing the issuing client is hostile, and
// its Process handle is not held here anyway). Components are stopped in reverse-
// topological order - repeatedly a current leaf of the scoped subgraph, one nothing in
// scope still depends on - so a dependent always stops before its dependency. A service
// is stopped by killing its process (services serve on their SERVE channels and ignore
// their bootstrap, so the cooperative STOP protocol does not reach them) and draining
// its control channel to the peer-close. Returns the newline-joined names of everything
// stopped, in teardown order.
unsafe fn stop_subtree(target: usize, state: &mut [State; N], channels: &mut [u64; N], sup: &mut [Supervised; N], procs: &[u64; N], log_client: u64, buf: &mut [u8]) -> Vec<u8> {
	unsafe {
		let mut scope: [bool; N] = [false; N];
		scope[target] = true;
		// Fixpoint: add any Running component that depends on something already in scope,
		// until nothing new is added - the full reverse-dependency closure of the target.
		loop {
			let mut grew: bool = false;
			let mut i: usize = 0;
			while i < N {
				if !scope[i] && state[i] == State::Running && depends_on_scoped(i, &scope) {
					scope[i] = true;
					grew = true;
				}
				i += 1;
			}
			if !grew {
				break;
			}
		}
		// Exempt the shell: it transitively depends on everything, so it would always be in
		// scope, but the issuing terminal must survive (and procs[shell] == 0 regardless).
		if let Some(sh) = index_of(b"shell") {
			scope[sh] = false;
		}
		let mut stopped: Vec<u8> = Vec::new();
		loop {
			let mut progress: bool = false;
			let mut i: usize = 0;
			while i < N {
				if scope[i] && state[i] == State::Running && !has_running_dependent(i, &scope, state) {
					if procs[i] != 0 {
						signal(procs[i], SIG_KILL);
					}
					drain_closed(channels[i], buf);
					if channels[i] != 0 {
						close(channels[i]);
						channels[i] = 0;
					}
					state[i] = State::Stopped;
					sup[i].failure = Failure::Stopped;
					emit_event(log_client, MANIFEST[i].name, b"stopped");
					console_report(MANIFEST[i].name, b"stopped");
					if !stopped.is_empty() {
						stopped.push(b'\n');
					}
					stopped.extend_from_slice(MANIFEST[i].name);
					progress = true;
				}
				i += 1;
			}
			if !progress {
				break;
			}
		}
		stopped
	}
}
