//! `Scene3D Extended 1`: THE EQUATIONS THAT MAKE TWO RENDERERS AGREE ABOUT A SURFACE.
//!
//! Everything here is optional to conform to and exact to implement. A physically based material is
//! four or five functions multiplied together, and every published renderer chooses slightly
//! different ones - a different normal distribution, a different visibility term, a different
//! roughness remapping - so two implementations of "PBR" produce visibly different metal. The
//! difference is not a quality setting; it is a different material.
//!
//! IT IS A SEPARATE PROFILE WITH A SEPARATE HASH, so an implementation conforms to `Scene3D Core
//! Profile 1` without claiming any of this, and a scene that uses it says so.

use crate::render3d_spec::Rule;

/// One term of the physically based material, written as the equation rather than named.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub struct Term {
	pub name: &'static str,
	pub equation: &'static str,
	pub why: &'static str,
}

pub const PBR_TERMS: &[Term] = &[
	Term { name: "normal distribution (GGX / Trowbridge-Reitz)", equation: "D(h) = a^2 / (pi * ((dot(N,H)^2 * (a^2 - 1) + 1))^2), with a = roughness^2", why: "GGX rather than Beckmann because its tail is longer, which is what makes a rough metal look rough rather than plastic; `a = roughness^2` is the remapping that makes the perceptual slider linear" },
	Term { name: "visibility (Smith height-correlated)", equation: "V = 0.5 / (dot(N,L) * sqrt(dot(N,V)^2 * (1 - a^2) + a^2) + dot(N,V) * sqrt(dot(N,L)^2 * (1 - a^2) + a^2))", why: "the height-correlated form, and it INCLUDES the 1/(4 dot(N,L) dot(N,V)) denominator of the specular BRDF - which is why the whole specular term is D * V * F and not D * G * F / (4 ...). Stating which convention the term carries is the difference between a correct highlight and one four times too bright" },
	Term { name: "Fresnel (Schlick)", equation: "F = F0 + (1 - F0) * (1 - dot(V,H))^5, with F0 = mix(vec3(0.04), base_colour, metallic)", why: "the 0.04 is the reflectance of an ordinary dielectric at normal incidence; a metal's F0 IS its base colour, which is what `metallic` selects between" },
	Term { name: "diffuse (Lambert)", equation: "diffuse = (1 - metallic) * base_colour / pi, multiplied by (1 - F) so energy is not created", why: "Lambert rather than Oren-Nayar or Disney: it is the one every reference implementation shares, and the others are a different material" },
	Term { name: "the whole direct term", equation: "colour = (diffuse + D * V * F) * light_colour * dot(N,L) * attenuation", why: "written out because the order and the placement of `dot(N,L)` is exactly what implementations differ about" },
];

pub const PBR_CONSTANTS: &[Rule] = &[
	Rule { question: "the minimum roughness", answer: "0.045, clamped before `a = roughness^2` is taken. A roughness of zero makes `D` a delta function, which is an infinite highlight at one pixel and a NaN in a filtered environment lookup" },
	Rule { question: "the roughness remapping", answer: "`a = roughness^2`, and the material's roughness input is PERCEPTUAL. A renderer that fed the perceptual value straight into `D` produces a material that goes from mirror to matte in the first quarter of the slider" },
	Rule { question: "the dielectric F0", answer: "0.04 for every dielectric. A per-material specular level is Extended-of-Extended; one constant covers every non-metal a scene actually has" },
	Rule { question: "clamping", answer: "every dot product in the equations above is clamped to [0, 1] before use, and `dot(N,V)` is clamped to at least 1e-4 so the visibility term cannot divide by zero at a grazing angle" },
	Rule { question: "the colour space", answer: "LINEAR throughout, as in the core profile" },
];

/// Environment lighting: the prefilter and the lookup table, which are two halves of one
/// approximation and are useless if the two ends disagree.
pub const ENVIRONMENT_RULES: &[Rule] = &[
	Rule { question: "the split-sum approximation", answer: "the environment term is `prefiltered(R, roughness) * (F0 * brdf.x + brdf.y)`, where `brdf` is looked up by `(dot(N,V), roughness)`. Both halves are stated because a prefilter built for one lookup table is wrong with another" },
	Rule { question: "the prefilter", answer: "a cube map whose mip level i is the GGX-importance-sampled radiance at `roughness = i / (levels - 1)`, with 1024 samples per texel and the source sampled at a mip chosen by the sample's own solid angle - which is what removes the fireflies a naive prefilter has" },
	Rule { question: "the number of levels", answer: "as many as the cube's size allows down to 8x8; below that the filter is wider than the face and the result is the average of the whole environment anyway" },
	Rule { question: "the BRDF lookup table", answer: "a 2-channel 16-bit table, 256 by 256, `x` = dot(N,V) and `y` = roughness, generated by the same GGX and Smith terms above. Its generation is part of this profile, so two implementations produce the same table" },
	Rule { question: "the irradiance term", answer: "a separate cube map holding the cosine-convolved irradiance, sampled by `N`. Nine spherical-harmonic coefficients are the permitted alternative and produce the same result to within the conformance threshold" },
];

/// Shadows.
pub const SHADOW_RULES: &[Rule] = &[
	Rule { question: "the map format", answer: "`Depth32F`, with the comparison rule the 3D profile fixes: the stored floats are compared and the incoming depth is not quantised" },
	Rule { question: "the bias", answer: "constant 0.0015 and slope 2.0, applied through the 3D profile's depth-bias equation, with a clamp of 0.01. Named values rather than 'tune it': a scene tuned against an unstated bias acnes on the next implementation" },
	Rule { question: "the filter", answer: "a 3x3 percentage-closer kernel at the map's texel size with EQUAL weights, using the compare-then-filter rule the sampler contract fixes. Equal weights rather than a Gaussian because the sample positions are already a box" },
	Rule { question: "the cascade decision", answer: "by VIEW-SPACE DEPTH against fixed split distances, computed as a blend of the uniform and logarithmic splits with lambda 0.5, and the cascade index is chosen by the fragment's own depth rather than by the drawable's - a large object spans cascades" },
	Rule { question: "the cascade count", answer: "up to `max_shadow_cascades`, and a scene that asks for more is REFUSED rather than silently given fewer" },
	Rule { question: "the transition between cascades", answer: "a blend over the last 10 per cent of each cascade's range, so the seam is a gradient rather than a line" },
	Rule { question: "what is outside the last cascade", answer: "UNSHADOWED. Extending the last cascade to infinity makes its texels useless everywhere; saying so lets a scene choose its far distance" },
	Rule { question: "a point light's shadow", answer: "a cube map with the same bias and filter, its face chosen by the major axis of the light-to-fragment vector as the 3D profile's cube orientation defines" },
];

/// Post-processing.
pub const POSTPROCESS_RULES: &[Rule] = &[
	Rule { question: "the bloom threshold", answer: "a soft knee at luminance 1.0 with a knee width of 0.5: below 0.5 nothing, above 1.5 the whole excess, and a quadratic between. A hard threshold makes a moving highlight pop in and out" },
	Rule { question: "the luminance used", answer: "`dot(colour, vec3(0.2126, 0.7152, 0.0722))` in linear Rec. 709 primaries, which is the same luminance the image-colour profile uses" },
	Rule { question: "the bloom kernel", answer: "a progressive downsample with a 13-tap filter and an upsample with a 9-tap tent, six levels, combined with weight 0.04 by default. Stated because a bloom built from a different pyramid has a different shape at the same 'intensity'" },
	Rule { question: "tone mapping", answer: "the SAME operator the 2D image-colour profile fixes - extended Reinhard with WHITE = 4.0 - applied in linear space before encoding. Two operators in one system is two systems" },
	Rule { question: "the fog equation", answer: "exponential-squared: `f = exp(-(density * distance)^2)`, with distance the view-space depth and the result mixing toward the fog colour. Squared rather than linear because it has no visible start plane" },
	Rule { question: "the order", answer: "tone mapping is LAST, after bloom and fog, because both are defined on linear radiance and a tone-mapped input would compress the highlights they exist to spread" },
];

/// Animation and skinning.
pub const ANIMATION_RULES: &[Rule] = &[
	Rule { question: "the skinning model", answer: "linear blend skinning with up to four influences per vertex, weights normalised to sum to one at load - not at draw, because a shader that normalised every frame would be paying for an authoring error every frame" },
	Rule { question: "the joint transform", answer: "`joint_world * inverse_bind`, composed on the host once per frame per skeleton; the vertex stage multiplies and adds" },
	Rule { question: "morph targets", answer: "additive displacement, up to `max_morph_targets` per mesh, applied BEFORE skinning - a morph that moved a vertex after skinning would move it out of the pose" },
	Rule { question: "interpolation", answer: "linear for translation and scale, SPHERICAL LINEAR for rotation, along the shorter arc. Interpolating quaternions linearly and normalising is the cheaper alternative and produces a different, visibly uneven, rotation speed" },
	Rule { question: "the root-motion policy", answer: "CHOSEN RATHER THAN REQUIRED: root motion is EXTRACTED by default - the root joint's translation is removed from the pose and handed to the application as a delta - and a clip may declare that it keeps it. Extraction by default because an application that does not ask for root motion should not have its character drift" },
	Rule { question: "looping", answer: "a clip declares whether it loops, and a looping clip's last keyframe must equal its first within the conformance threshold or the clip is REFUSED at load rather than popping once a cycle" },
];

/// One guaranteed minimum for the extended profile.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub struct ExtendedLimit {
	pub name: &'static str,
	pub minimum: u32,
	pub why: &'static str,
}

pub const SCENE3D_EXTENDED_1_MIN_LIMITS: &[ExtendedLimit] = &[
	ExtendedLimit { name: "max_shadow_cascades", minimum: 4, why: "four is what covers a walkable view distance at a usable texel density" },
	ExtendedLimit { name: "max_shadow_maps", minimum: 8, why: "one cascaded directional light and a few local ones" },
	ExtendedLimit { name: "max_skeleton_joints", minimum: 128, why: "a humanoid with fingers" },
	ExtendedLimit { name: "max_morph_targets", minimum: 32, why: "a facial rig's expressions" },
	ExtendedLimit { name: "max_animation_tracks", minimum: 256, why: "two joints' worth of curves per joint on the skeleton above" },
	ExtendedLimit { name: "environment_prefilter_levels", minimum: 6, why: "a 256-texel face down to 8, which is where the filter stops meaning anything" },
];
