// @generated by lsidl-gen from ../../idl/system.lsidl (package liber:system@1).
// Do not edit by hand; regenerate with `just gen`.
#![allow(dead_code, unused_imports, clippy::all)]

use crate::codec::{Reader, Writer};
use alloc::string::String;
use alloc::vec::Vec;

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[repr(u8)]
pub enum Error {
	Denied = 0,
	NotFound = 1,
	Invalid = 2,
	Again = 3,
	Closed = 4,
}

impl Error {
	pub fn encode(&self, out: &mut [u8]) -> Option<usize> {
		let mut w = Writer::new(out);
		self.write(&mut w)?;
		Some(w.pos())
	}
	pub fn decode(bytes: &[u8]) -> Option<Error> {
		Error::read(&mut Reader::new(bytes))
	}
	pub(crate) fn write(&self, w: &mut Writer) -> Option<()> {
		w.u8(*self as u8)
	}
	pub(crate) fn read(r: &mut Reader) -> Option<Error> {
		match r.u8()? {
			0 => Some(Error::Denied),
			1 => Some(Error::NotFound),
			2 => Some(Error::Invalid),
			3 => Some(Error::Again),
			4 => Some(Error::Closed),
			_ => None,
		}
	}
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[repr(u8)]
pub enum Severity {
	Trace = 0,
	Debug = 1,
	Info = 2,
	Warn = 3,
	Error = 4,
	Fatal = 5,
}

impl Severity {
	pub fn encode(&self, out: &mut [u8]) -> Option<usize> {
		let mut w = Writer::new(out);
		self.write(&mut w)?;
		Some(w.pos())
	}
	pub fn decode(bytes: &[u8]) -> Option<Severity> {
		Severity::read(&mut Reader::new(bytes))
	}
	pub(crate) fn write(&self, w: &mut Writer) -> Option<()> {
		w.u8(*self as u8)
	}
	pub(crate) fn read(r: &mut Reader) -> Option<Severity> {
		match r.u8()? {
			0 => Some(Severity::Trace),
			1 => Some(Severity::Debug),
			2 => Some(Severity::Info),
			3 => Some(Severity::Warn),
			4 => Some(Severity::Error),
			5 => Some(Severity::Fatal),
			_ => None,
		}
	}
}

#[derive(Clone, Debug, PartialEq)]
pub struct Field {
	pub key: String,
	pub value: String,
}

impl Field {
	pub fn encode(&self, out: &mut [u8]) -> Option<usize> {
		let mut w = Writer::new(out);
		self.write(&mut w)?;
		Some(w.pos())
	}
	pub fn decode(bytes: &[u8]) -> Option<Field> {
		Field::read(&mut Reader::new(bytes))
	}
	pub(crate) fn write(&self, w: &mut Writer) -> Option<()> {
		w.bytes_lp(self.key.as_bytes())?;
		w.bytes_lp(self.value.as_bytes())?;
		Some(())
	}
	pub(crate) fn read(r: &mut Reader) -> Option<Field> {
		let key = r.string_lp()?;
		let value = r.string_lp()?;
		Some(Field { key, value })
	}
}

#[derive(Clone, Debug, PartialEq)]
pub struct Entry {
	pub timestamp: u64,
	pub severity: Severity,
	pub source: String,
	pub fields: Vec<Field>,
}

impl Entry {
	pub fn encode(&self, out: &mut [u8]) -> Option<usize> {
		let mut w = Writer::new(out);
		self.write(&mut w)?;
		Some(w.pos())
	}
	pub fn decode(bytes: &[u8]) -> Option<Entry> {
		Entry::read(&mut Reader::new(bytes))
	}
	pub(crate) fn write(&self, w: &mut Writer) -> Option<()> {
		w.u64(self.timestamp)?;
		self.severity.write(w)?;
		w.bytes_lp(self.source.as_bytes())?;
		if self.fields.len() > u16::MAX as usize {
			return None;
		}
		w.u16(self.fields.len() as u16)?;
		for v0 in self.fields.iter() {
			v0.write(w)?;
		}
		Some(())
	}
	pub(crate) fn read(r: &mut Reader) -> Option<Entry> {
		let timestamp = r.u64()?;
		let severity = Severity::read(r)?;
		let source = r.string_lp()?;
		let fields = {
			let v1 = r.u16()? as usize;
			let mut v2 = Vec::new();
			for _ in 0..v1 {
				v2.push(Field::read(r)?);
			}
			v2
		};
		Some(Entry { timestamp, severity, source, fields })
	}
}

#[derive(Clone, Debug, PartialEq)]
pub struct Query {
	pub since: Option<u64>,
	pub min_severity: Option<Severity>,
	pub source: Option<String>,
	pub limit: u32,
}

impl Query {
	pub fn encode(&self, out: &mut [u8]) -> Option<usize> {
		let mut w = Writer::new(out);
		self.write(&mut w)?;
		Some(w.pos())
	}
	pub fn decode(bytes: &[u8]) -> Option<Query> {
		Query::read(&mut Reader::new(bytes))
	}
	pub(crate) fn write(&self, w: &mut Writer) -> Option<()> {
		match &self.since {
			Some(v3) => {
				w.u8(1)?;
				w.u64(*v3)?;
			}
			None => {
				w.u8(0)?;
			}
		}
		match &self.min_severity {
			Some(v4) => {
				w.u8(1)?;
				v4.write(w)?;
			}
			None => {
				w.u8(0)?;
			}
		}
		match &self.source {
			Some(v5) => {
				w.u8(1)?;
				w.bytes_lp(v5.as_bytes())?;
			}
			None => {
				w.u8(0)?;
			}
		}
		w.u32(self.limit)?;
		Some(())
	}
	pub(crate) fn read(r: &mut Reader) -> Option<Query> {
		let since = if r.u8()? != 0 { Some(r.u64()?) } else { None };
		let min_severity = if r.u8()? != 0 { Some(Severity::read(r)?) } else { None };
		let source = if r.u8()? != 0 { Some(r.string_lp()?) } else { None };
		let limit = r.u32()?;
		Some(Query { since, min_severity, source, limit })
	}
}

// interface `log` - opcodes (client/server bindings are generated in a later step).
pub mod log {
	pub const OP_EMIT: u16 = 1;
	pub const OP_QUERY: u16 = 2;
	pub const OP_TAIL: u16 = 3;
}
