// @generated by lsidl-gen from ../../idl/system.lsidl (package liber:system@1).
// Do not edit by hand; regenerate with `just gen`.
#![allow(dead_code, unused_imports, unused_variables, unused_mut, clippy::all)]

use crate::codec::{Reader, Sink, SliceWriter, VecWriter};
use alloc::string::String;
use alloc::vec::Vec;
use core::fmt::Write as _;

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[repr(u8)]
pub enum Error {
	Denied = 0,
	NotFound = 1,
	Invalid = 2,
	Again = 3,
	Closed = 4,
}

impl Error {
	pub fn encode(&self, out: &mut [u8]) -> Option<usize> {
		let mut w = SliceWriter::new(out);
		self.write(&mut w)?;
		Some(w.pos())
	}
	pub fn encode_vec(&self) -> Vec<u8> {
		let mut w = VecWriter::new();
		let _ = self.write(&mut w);
		w.into_inner()
	}
	pub fn decode(bytes: &[u8]) -> Option<Error> {
		Error::read(&mut Reader::new(bytes))
	}
	pub(crate) fn write<W: Sink>(&self, w: &mut W) -> Option<()> {
		w.u8(*self as u8)
	}
	pub(crate) fn read(r: &mut Reader) -> Option<Error> {
		match r.u8()? {
			0 => Some(Error::Denied),
			1 => Some(Error::NotFound),
			2 => Some(Error::Invalid),
			3 => Some(Error::Again),
			4 => Some(Error::Closed),
			_ => None,
		}
	}
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[repr(u8)]
pub enum Severity {
	Trace = 0,
	Debug = 1,
	Info = 2,
	Warn = 3,
	Error = 4,
	Fatal = 5,
}

impl Severity {
	pub fn encode(&self, out: &mut [u8]) -> Option<usize> {
		let mut w = SliceWriter::new(out);
		self.write(&mut w)?;
		Some(w.pos())
	}
	pub fn encode_vec(&self) -> Vec<u8> {
		let mut w = VecWriter::new();
		let _ = self.write(&mut w);
		w.into_inner()
	}
	pub fn decode(bytes: &[u8]) -> Option<Severity> {
		Severity::read(&mut Reader::new(bytes))
	}
	pub(crate) fn write<W: Sink>(&self, w: &mut W) -> Option<()> {
		w.u8(*self as u8)
	}
	pub(crate) fn read(r: &mut Reader) -> Option<Severity> {
		match r.u8()? {
			0 => Some(Severity::Trace),
			1 => Some(Severity::Debug),
			2 => Some(Severity::Info),
			3 => Some(Severity::Warn),
			4 => Some(Severity::Error),
			5 => Some(Severity::Fatal),
			_ => None,
		}
	}
}

#[derive(Clone, Debug, PartialEq)]
pub struct Field {
	pub key: String,
	pub value: String,
}

impl Field {
	pub fn encode(&self, out: &mut [u8]) -> Option<usize> {
		let mut w = SliceWriter::new(out);
		self.write(&mut w)?;
		Some(w.pos())
	}
	pub fn encode_vec(&self) -> Vec<u8> {
		let mut w = VecWriter::new();
		let _ = self.write(&mut w);
		w.into_inner()
	}
	pub fn decode(bytes: &[u8]) -> Option<Field> {
		Field::read(&mut Reader::new(bytes))
	}
	pub(crate) fn write<W: Sink>(&self, w: &mut W) -> Option<()> {
		w.bytes_lp(self.key.as_bytes())?;
		w.bytes_lp(self.value.as_bytes())?;
		Some(())
	}
	pub(crate) fn read(r: &mut Reader) -> Option<Field> {
		let key = r.string_lp()?;
		let value = r.string_lp()?;
		Some(Field { key, value })
	}
}

#[derive(Clone, Debug, PartialEq)]
pub struct Entry {
	pub timestamp: u64,
	pub severity: Severity,
	pub source: String,
	pub fields: Vec<Field>,
}

impl Entry {
	pub fn encode(&self, out: &mut [u8]) -> Option<usize> {
		let mut w = SliceWriter::new(out);
		self.write(&mut w)?;
		Some(w.pos())
	}
	pub fn encode_vec(&self) -> Vec<u8> {
		let mut w = VecWriter::new();
		let _ = self.write(&mut w);
		w.into_inner()
	}
	pub fn decode(bytes: &[u8]) -> Option<Entry> {
		Entry::read(&mut Reader::new(bytes))
	}
	pub(crate) fn write<W: Sink>(&self, w: &mut W) -> Option<()> {
		w.u64(self.timestamp)?;
		self.severity.write(w)?;
		w.bytes_lp(self.source.as_bytes())?;
		if self.fields.len() > u16::MAX as usize {
			return None;
		}
		w.u16(self.fields.len() as u16)?;
		for v0 in self.fields.iter() {
			v0.write(w)?;
		}
		Some(())
	}
	pub(crate) fn read(r: &mut Reader) -> Option<Entry> {
		let timestamp = r.u64()?;
		let severity = Severity::read(r)?;
		let source = r.string_lp()?;
		let fields = {
			let v1 = r.u16()? as usize;
			let mut v2 = Vec::new();
			for _ in 0..v1 {
				v2.push(Field::read(r)?);
			}
			v2
		};
		Some(Entry { timestamp, severity, source, fields })
	}
}

#[derive(Clone, Debug, PartialEq)]
pub struct Query {
	pub since: Option<u64>,
	pub min_severity: Option<Severity>,
	pub source: Option<String>,
	pub limit: u32,
}

impl Query {
	pub fn encode(&self, out: &mut [u8]) -> Option<usize> {
		let mut w = SliceWriter::new(out);
		self.write(&mut w)?;
		Some(w.pos())
	}
	pub fn encode_vec(&self) -> Vec<u8> {
		let mut w = VecWriter::new();
		let _ = self.write(&mut w);
		w.into_inner()
	}
	pub fn decode(bytes: &[u8]) -> Option<Query> {
		Query::read(&mut Reader::new(bytes))
	}
	pub(crate) fn write<W: Sink>(&self, w: &mut W) -> Option<()> {
		match &self.since {
			Some(v3) => {
				w.u8(1)?;
				w.u64(*v3)?;
			}
			None => {
				w.u8(0)?;
			}
		}
		match &self.min_severity {
			Some(v4) => {
				w.u8(1)?;
				v4.write(w)?;
			}
			None => {
				w.u8(0)?;
			}
		}
		match &self.source {
			Some(v5) => {
				w.u8(1)?;
				w.bytes_lp(v5.as_bytes())?;
			}
			None => {
				w.u8(0)?;
			}
		}
		w.u32(self.limit)?;
		Some(())
	}
	pub(crate) fn read(r: &mut Reader) -> Option<Query> {
		let since = if r.u8()? != 0 { Some(r.u64()?) } else { None };
		let min_severity = if r.u8()? != 0 { Some(Severity::read(r)?) } else { None };
		let source = if r.u8()? != 0 { Some(r.string_lp()?) } else { None };
		let limit = r.u32()?;
		Some(Query { since, min_severity, source, limit })
	}
}

// interface `log` over a channel: opcodes, a Service trait + dispatch, and a Client.
pub mod log {
	use super::*;
	use crate::codec::{Reader, Sink, SliceWriter, Transport, VecWriter};
	use alloc::vec::Vec;

	pub const OP_EMIT: u16 = 1;
	pub const OP_QUERY: u16 = 2;
	pub const OP_TAIL: u16 = 3;

	pub trait Service {
		fn emit(&mut self, e: Entry) -> Result<(), Error>;
		fn query(&mut self, q: Query) -> Result<Vec<Entry>, Error>;
		fn tail(&mut self, q: Query) -> Vec<Entry>;
	}

	pub fn dispatch<S: Service>(service: &mut S, request: &[u8], request_handle: u64, out: &mut [u8], reply_handle: &mut u64) -> Option<usize> {
		let mut reader = Reader::with_handle(request, request_handle);
		let r = &mut reader;
		let op = r.u16()?;
		let corr = r.u32()?;
		let mut writer = SliceWriter::new(out);
		let w = &mut writer;
		w.u32(corr)?;
		match op {
			OP_EMIT => {
				let e = Entry::read(r)?;
				let result = service.emit(e);
				match &result {
					Ok(v6) => {
						w.u8(1)?;
					}
					Err(v7) => {
						w.u8(0)?;
						v7.write(w)?;
					}
				}
			}
			OP_QUERY => {
				let q = Query::read(r)?;
				let result = service.query(q);
				match &result {
					Ok(v8) => {
						w.u8(1)?;
						if v8.len() > u16::MAX as usize {
							return None;
						}
						w.u16(v8.len() as u16)?;
						for v10 in v8.iter() {
							v10.write(w)?;
						}
					}
					Err(v9) => {
						w.u8(0)?;
						v9.write(w)?;
					}
				}
			}
			_ => return None,
		}
		*reply_handle = writer.handle();
		Some(writer.pos())
	}

	pub fn tail_open<S: Service>(service: &mut S, request: &[u8]) -> Option<(u32, Vec<Entry>)> {
		let mut reader = Reader::new(request);
		let r = &mut reader;
		let _op = r.u16()?;
		let corr = r.u32()?;
		let q = Query::read(r)?;
		let items = service.tail(q);
		Some((corr, items))
	}
	pub fn tail_frame(seq: u32, item: &Entry, out: &mut [u8]) -> Option<usize> {
		let mut writer = SliceWriter::new(out);
		let w = &mut writer;
		w.u32(seq)?;
		item.write(w)?;
		Some(writer.pos())
	}
	pub fn tail_read(msg: &[u8]) -> Option<Entry> {
		let mut reader = Reader::new(msg);
		let r = &mut reader;
		let _seq = r.u32()?;
		Some(Entry::read(r)?)
	}

	pub struct Client<T: Transport> {
		transport: T,
		corr: u32,
	}

	impl<T: Transport> Client<T> {
		pub fn new(transport: T) -> Client<T> {
			Client { transport, corr: 0 }
		}
		pub fn into_transport(self) -> T {
			self.transport
		}
		fn next_corr(&mut self) -> u32 {
			let c = self.corr;
			self.corr = self.corr.wrapping_add(1);
			c
		}
		pub fn emit(&mut self, e: &Entry) -> Option<Result<(), Error>> {
			let corr = self.next_corr();
			let mut writer = VecWriter::new();
			let w = &mut writer;
			w.u16(OP_EMIT)?;
			w.u32(corr)?;
			e.write(w)?;
			let request_handle = writer.handle();
			let request = writer.into_inner();
			let (reply, reply_handle) = self.transport.call(&request, request_handle)?;
			let mut reader = Reader::with_handle(&reply, reply_handle);
			let r = &mut reader;
			if r.u32()? != corr {
				return None;
			}
			Some(if r.u8()? != 0 { Ok(()) } else { Err(Error::read(r)?) })
		}
		pub fn query(&mut self, q: &Query) -> Option<Result<Vec<Entry>, Error>> {
			let corr = self.next_corr();
			let mut writer = VecWriter::new();
			let w = &mut writer;
			w.u16(OP_QUERY)?;
			w.u32(corr)?;
			q.write(w)?;
			let request_handle = writer.handle();
			let request = writer.into_inner();
			let (reply, reply_handle) = self.transport.call(&request, request_handle)?;
			let mut reader = Reader::with_handle(&reply, reply_handle);
			let r = &mut reader;
			if r.u32()? != corr {
				return None;
			}
			Some(if r.u8()? != 0 {
				Ok({
					let v11 = r.u16()? as usize;
					let mut v12 = Vec::new();
					for _ in 0..v11 {
						v12.push(Entry::read(r)?);
					}
					v12
				})
			} else {
				Err(Error::read(r)?)
			})
		}
		pub fn tail(&mut self, q: &Query) -> Option<u64> {
			let corr = self.next_corr();
			let mut writer = VecWriter::new();
			let w = &mut writer;
			w.u16(OP_TAIL)?;
			w.u32(corr)?;
			q.write(w)?;
			let request = writer.into_inner();
			let (reply, reply_handle) = self.transport.call(&request, 0)?;
			let mut reader = Reader::new(&reply);
			let r = &mut reader;
			if r.u32()? != corr || reply_handle == 0 {
				return None;
			}
			Some(reply_handle)
		}
	}
}

#[derive(Clone, Debug, PartialEq)]
pub struct OpenOpts {
	pub path: String,
	pub write: bool,
	pub create: bool,
}

impl OpenOpts {
	pub fn encode(&self, out: &mut [u8]) -> Option<usize> {
		let mut w = SliceWriter::new(out);
		self.write(&mut w)?;
		Some(w.pos())
	}
	pub fn encode_vec(&self) -> Vec<u8> {
		let mut w = VecWriter::new();
		let _ = self.write(&mut w);
		w.into_inner()
	}
	pub fn decode(bytes: &[u8]) -> Option<OpenOpts> {
		OpenOpts::read(&mut Reader::new(bytes))
	}
	pub(crate) fn write<W: Sink>(&self, w: &mut W) -> Option<()> {
		w.bytes_lp(self.path.as_bytes())?;
		w.boolean(self.write)?;
		w.boolean(self.create)?;
		Some(())
	}
	pub(crate) fn read(r: &mut Reader) -> Option<OpenOpts> {
		let path = r.string_lp()?;
		let write = r.boolean()?;
		let create = r.boolean()?;
		Some(OpenOpts { path, write, create })
	}
}

#[derive(Clone, Debug, PartialEq)]
pub struct OpenResult {
	pub file: u64,
	pub size: u64,
}

impl OpenResult {
	pub fn encode(&self, out: &mut [u8]) -> Option<usize> {
		let mut w = SliceWriter::new(out);
		self.write(&mut w)?;
		Some(w.pos())
	}
	pub fn encode_vec(&self) -> Vec<u8> {
		let mut w = VecWriter::new();
		let _ = self.write(&mut w);
		w.into_inner()
	}
	pub fn decode(bytes: &[u8]) -> Option<OpenResult> {
		OpenResult::read(&mut Reader::new(bytes))
	}
	pub(crate) fn write<W: Sink>(&self, w: &mut W) -> Option<()> {
		w.set_handle(self.file);
		w.u32(0)?;
		w.u64(self.size)?;
		Some(())
	}
	pub(crate) fn read(r: &mut Reader) -> Option<OpenResult> {
		let file = {
			let _ = r.u32()?;
			r.take_handle()
		};
		let size = r.u64()?;
		Some(OpenResult { file, size })
	}
}

#[derive(Clone, Debug, PartialEq)]
pub struct FileInfo {
	pub name: String,
	pub size: u64,
}

impl FileInfo {
	pub fn encode(&self, out: &mut [u8]) -> Option<usize> {
		let mut w = SliceWriter::new(out);
		self.write(&mut w)?;
		Some(w.pos())
	}
	pub fn encode_vec(&self) -> Vec<u8> {
		let mut w = VecWriter::new();
		let _ = self.write(&mut w);
		w.into_inner()
	}
	pub fn decode(bytes: &[u8]) -> Option<FileInfo> {
		FileInfo::read(&mut Reader::new(bytes))
	}
	pub(crate) fn write<W: Sink>(&self, w: &mut W) -> Option<()> {
		w.bytes_lp(self.name.as_bytes())?;
		w.u64(self.size)?;
		Some(())
	}
	pub(crate) fn read(r: &mut Reader) -> Option<FileInfo> {
		let name = r.string_lp()?;
		let size = r.u64()?;
		Some(FileInfo { name, size })
	}
}

// interface `volume` over a channel: opcodes, a Service trait + dispatch, and a Client.
pub mod volume {
	use super::*;
	use crate::codec::{Reader, Sink, SliceWriter, Transport, VecWriter};
	use alloc::vec::Vec;

	pub const OP_OPEN: u16 = 1;
	pub const OP_LIST: u16 = 2;

	pub trait Service {
		fn open(&mut self, o: OpenOpts) -> Result<OpenResult, Error>;
		fn list(&mut self) -> Result<Vec<FileInfo>, Error>;
	}

	pub fn dispatch<S: Service>(service: &mut S, request: &[u8], request_handle: u64, out: &mut [u8], reply_handle: &mut u64) -> Option<usize> {
		let mut reader = Reader::with_handle(request, request_handle);
		let r = &mut reader;
		let op = r.u16()?;
		let corr = r.u32()?;
		let mut writer = SliceWriter::new(out);
		let w = &mut writer;
		w.u32(corr)?;
		match op {
			OP_OPEN => {
				let o = OpenOpts::read(r)?;
				let result = service.open(o);
				match &result {
					Ok(v13) => {
						w.u8(1)?;
						v13.write(w)?;
					}
					Err(v14) => {
						w.u8(0)?;
						v14.write(w)?;
					}
				}
			}
			OP_LIST => {
				let result = service.list();
				match &result {
					Ok(v15) => {
						w.u8(1)?;
						if v15.len() > u16::MAX as usize {
							return None;
						}
						w.u16(v15.len() as u16)?;
						for v17 in v15.iter() {
							v17.write(w)?;
						}
					}
					Err(v16) => {
						w.u8(0)?;
						v16.write(w)?;
					}
				}
			}
			_ => return None,
		}
		*reply_handle = writer.handle();
		Some(writer.pos())
	}

	pub struct Client<T: Transport> {
		transport: T,
		corr: u32,
	}

	impl<T: Transport> Client<T> {
		pub fn new(transport: T) -> Client<T> {
			Client { transport, corr: 0 }
		}
		pub fn into_transport(self) -> T {
			self.transport
		}
		fn next_corr(&mut self) -> u32 {
			let c = self.corr;
			self.corr = self.corr.wrapping_add(1);
			c
		}
		pub fn open(&mut self, o: &OpenOpts) -> Option<Result<OpenResult, Error>> {
			let corr = self.next_corr();
			let mut writer = VecWriter::new();
			let w = &mut writer;
			w.u16(OP_OPEN)?;
			w.u32(corr)?;
			o.write(w)?;
			let request_handle = writer.handle();
			let request = writer.into_inner();
			let (reply, reply_handle) = self.transport.call(&request, request_handle)?;
			let mut reader = Reader::with_handle(&reply, reply_handle);
			let r = &mut reader;
			if r.u32()? != corr {
				return None;
			}
			Some(if r.u8()? != 0 { Ok(OpenResult::read(r)?) } else { Err(Error::read(r)?) })
		}
		pub fn list(&mut self) -> Option<Result<Vec<FileInfo>, Error>> {
			let corr = self.next_corr();
			let mut writer = VecWriter::new();
			let w = &mut writer;
			w.u16(OP_LIST)?;
			w.u32(corr)?;
			let request_handle = writer.handle();
			let request = writer.into_inner();
			let (reply, reply_handle) = self.transport.call(&request, request_handle)?;
			let mut reader = Reader::with_handle(&reply, reply_handle);
			let r = &mut reader;
			if r.u32()? != corr {
				return None;
			}
			Some(if r.u8()? != 0 {
				Ok({
					let v18 = r.u16()? as usize;
					let mut v19 = Vec::new();
					for _ in 0..v18 {
						v19.push(FileInfo::read(r)?);
					}
					v19
				})
			} else {
				Err(Error::read(r)?)
			})
		}
	}
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[repr(u8)]
pub enum DeviceKind {
	Unknown = 0,
	Net = 1,
	Block = 2,
	Console = 3,
}

impl DeviceKind {
	pub fn encode(&self, out: &mut [u8]) -> Option<usize> {
		let mut w = SliceWriter::new(out);
		self.write(&mut w)?;
		Some(w.pos())
	}
	pub fn encode_vec(&self) -> Vec<u8> {
		let mut w = VecWriter::new();
		let _ = self.write(&mut w);
		w.into_inner()
	}
	pub fn decode(bytes: &[u8]) -> Option<DeviceKind> {
		DeviceKind::read(&mut Reader::new(bytes))
	}
	pub(crate) fn write<W: Sink>(&self, w: &mut W) -> Option<()> {
		w.u8(*self as u8)
	}
	pub(crate) fn read(r: &mut Reader) -> Option<DeviceKind> {
		match r.u8()? {
			0 => Some(DeviceKind::Unknown),
			1 => Some(DeviceKind::Net),
			2 => Some(DeviceKind::Block),
			3 => Some(DeviceKind::Console),
			_ => None,
		}
	}
}

#[derive(Clone, Debug, PartialEq)]
pub struct DeviceEntry {
	pub index: u32,
	pub kind: DeviceKind,
	pub mmio_len: u64,
}

impl DeviceEntry {
	pub fn encode(&self, out: &mut [u8]) -> Option<usize> {
		let mut w = SliceWriter::new(out);
		self.write(&mut w)?;
		Some(w.pos())
	}
	pub fn encode_vec(&self) -> Vec<u8> {
		let mut w = VecWriter::new();
		let _ = self.write(&mut w);
		w.into_inner()
	}
	pub fn decode(bytes: &[u8]) -> Option<DeviceEntry> {
		DeviceEntry::read(&mut Reader::new(bytes))
	}
	pub(crate) fn write<W: Sink>(&self, w: &mut W) -> Option<()> {
		w.u32(self.index)?;
		self.kind.write(w)?;
		w.u64(self.mmio_len)?;
		Some(())
	}
	pub(crate) fn read(r: &mut Reader) -> Option<DeviceEntry> {
		let index = r.u32()?;
		let kind = DeviceKind::read(r)?;
		let mmio_len = r.u64()?;
		Some(DeviceEntry { index, kind, mmio_len })
	}
}

// interface `device` over a channel: opcodes, a Service trait + dispatch, and a Client.
pub mod device {
	use super::*;
	use crate::codec::{Reader, Sink, SliceWriter, Transport, VecWriter};
	use alloc::vec::Vec;

	pub const OP_LIST: u16 = 1;
	pub const OP_GET: u16 = 2;

	pub trait Service {
		fn list(&mut self) -> Result<Vec<DeviceEntry>, Error>;
		fn get(&mut self, index: u32) -> Result<DeviceEntry, Error>;
	}

	pub fn dispatch<S: Service>(service: &mut S, request: &[u8], request_handle: u64, out: &mut [u8], reply_handle: &mut u64) -> Option<usize> {
		let mut reader = Reader::with_handle(request, request_handle);
		let r = &mut reader;
		let op = r.u16()?;
		let corr = r.u32()?;
		let mut writer = SliceWriter::new(out);
		let w = &mut writer;
		w.u32(corr)?;
		match op {
			OP_LIST => {
				let result = service.list();
				match &result {
					Ok(v20) => {
						w.u8(1)?;
						if v20.len() > u16::MAX as usize {
							return None;
						}
						w.u16(v20.len() as u16)?;
						for v22 in v20.iter() {
							v22.write(w)?;
						}
					}
					Err(v21) => {
						w.u8(0)?;
						v21.write(w)?;
					}
				}
			}
			OP_GET => {
				let index = r.u32()?;
				let result = service.get(index);
				match &result {
					Ok(v23) => {
						w.u8(1)?;
						v23.write(w)?;
					}
					Err(v24) => {
						w.u8(0)?;
						v24.write(w)?;
					}
				}
			}
			_ => return None,
		}
		*reply_handle = writer.handle();
		Some(writer.pos())
	}

	pub struct Client<T: Transport> {
		transport: T,
		corr: u32,
	}

	impl<T: Transport> Client<T> {
		pub fn new(transport: T) -> Client<T> {
			Client { transport, corr: 0 }
		}
		pub fn into_transport(self) -> T {
			self.transport
		}
		fn next_corr(&mut self) -> u32 {
			let c = self.corr;
			self.corr = self.corr.wrapping_add(1);
			c
		}
		pub fn list(&mut self) -> Option<Result<Vec<DeviceEntry>, Error>> {
			let corr = self.next_corr();
			let mut writer = VecWriter::new();
			let w = &mut writer;
			w.u16(OP_LIST)?;
			w.u32(corr)?;
			let request_handle = writer.handle();
			let request = writer.into_inner();
			let (reply, reply_handle) = self.transport.call(&request, request_handle)?;
			let mut reader = Reader::with_handle(&reply, reply_handle);
			let r = &mut reader;
			if r.u32()? != corr {
				return None;
			}
			Some(if r.u8()? != 0 {
				Ok({
					let v25 = r.u16()? as usize;
					let mut v26 = Vec::new();
					for _ in 0..v25 {
						v26.push(DeviceEntry::read(r)?);
					}
					v26
				})
			} else {
				Err(Error::read(r)?)
			})
		}
		pub fn get(&mut self, index: &u32) -> Option<Result<DeviceEntry, Error>> {
			let corr = self.next_corr();
			let mut writer = VecWriter::new();
			let w = &mut writer;
			w.u16(OP_GET)?;
			w.u32(corr)?;
			w.u32(*index)?;
			let request_handle = writer.handle();
			let request = writer.into_inner();
			let (reply, reply_handle) = self.transport.call(&request, request_handle)?;
			let mut reader = Reader::with_handle(&reply, reply_handle);
			let r = &mut reader;
			if r.u32()? != corr {
				return None;
			}
			Some(if r.u8()? != 0 { Ok(DeviceEntry::read(r)?) } else { Err(Error::read(r)?) })
		}
	}
}

#[derive(Clone, Debug, PartialEq)]
pub struct ProcessInfo {
	pub koid: u64,
	pub name: String,
}

impl ProcessInfo {
	pub fn encode(&self, out: &mut [u8]) -> Option<usize> {
		let mut w = SliceWriter::new(out);
		self.write(&mut w)?;
		Some(w.pos())
	}
	pub fn encode_vec(&self) -> Vec<u8> {
		let mut w = VecWriter::new();
		let _ = self.write(&mut w);
		w.into_inner()
	}
	pub fn decode(bytes: &[u8]) -> Option<ProcessInfo> {
		ProcessInfo::read(&mut Reader::new(bytes))
	}
	pub(crate) fn write<W: Sink>(&self, w: &mut W) -> Option<()> {
		w.u64(self.koid)?;
		w.bytes_lp(self.name.as_bytes())?;
		Some(())
	}
	pub(crate) fn read(r: &mut Reader) -> Option<ProcessInfo> {
		let koid = r.u64()?;
		let name = r.string_lp()?;
		Some(ProcessInfo { koid, name })
	}
}

// interface `process` over a channel: opcodes, a Service trait + dispatch, and a Client.
pub mod process {
	use super::*;
	use crate::codec::{Reader, Sink, SliceWriter, Transport, VecWriter};
	use alloc::vec::Vec;

	pub const OP_START: u16 = 1;
	pub const OP_LIST: u16 = 2;

	pub trait Service {
		fn start(&mut self, name: String) -> Result<ProcessInfo, Error>;
		fn list(&mut self) -> Result<Vec<ProcessInfo>, Error>;
	}

	pub fn dispatch<S: Service>(service: &mut S, request: &[u8], request_handle: u64, out: &mut [u8], reply_handle: &mut u64) -> Option<usize> {
		let mut reader = Reader::with_handle(request, request_handle);
		let r = &mut reader;
		let op = r.u16()?;
		let corr = r.u32()?;
		let mut writer = SliceWriter::new(out);
		let w = &mut writer;
		w.u32(corr)?;
		match op {
			OP_START => {
				let name = r.string_lp()?;
				let result = service.start(name);
				match &result {
					Ok(v27) => {
						w.u8(1)?;
						v27.write(w)?;
					}
					Err(v28) => {
						w.u8(0)?;
						v28.write(w)?;
					}
				}
			}
			OP_LIST => {
				let result = service.list();
				match &result {
					Ok(v29) => {
						w.u8(1)?;
						if v29.len() > u16::MAX as usize {
							return None;
						}
						w.u16(v29.len() as u16)?;
						for v31 in v29.iter() {
							v31.write(w)?;
						}
					}
					Err(v30) => {
						w.u8(0)?;
						v30.write(w)?;
					}
				}
			}
			_ => return None,
		}
		*reply_handle = writer.handle();
		Some(writer.pos())
	}

	pub struct Client<T: Transport> {
		transport: T,
		corr: u32,
	}

	impl<T: Transport> Client<T> {
		pub fn new(transport: T) -> Client<T> {
			Client { transport, corr: 0 }
		}
		pub fn into_transport(self) -> T {
			self.transport
		}
		fn next_corr(&mut self) -> u32 {
			let c = self.corr;
			self.corr = self.corr.wrapping_add(1);
			c
		}
		pub fn start(&mut self, name: &str) -> Option<Result<ProcessInfo, Error>> {
			let corr = self.next_corr();
			let mut writer = VecWriter::new();
			let w = &mut writer;
			w.u16(OP_START)?;
			w.u32(corr)?;
			w.bytes_lp(name.as_bytes())?;
			let request_handle = writer.handle();
			let request = writer.into_inner();
			let (reply, reply_handle) = self.transport.call(&request, request_handle)?;
			let mut reader = Reader::with_handle(&reply, reply_handle);
			let r = &mut reader;
			if r.u32()? != corr {
				return None;
			}
			Some(if r.u8()? != 0 { Ok(ProcessInfo::read(r)?) } else { Err(Error::read(r)?) })
		}
		pub fn list(&mut self) -> Option<Result<Vec<ProcessInfo>, Error>> {
			let corr = self.next_corr();
			let mut writer = VecWriter::new();
			let w = &mut writer;
			w.u16(OP_LIST)?;
			w.u32(corr)?;
			let request_handle = writer.handle();
			let request = writer.into_inner();
			let (reply, reply_handle) = self.transport.call(&request, request_handle)?;
			let mut reader = Reader::with_handle(&reply, reply_handle);
			let r = &mut reader;
			if r.u32()? != corr {
				return None;
			}
			Some(if r.u8()? != 0 {
				Ok({
					let v32 = r.u16()? as usize;
					let mut v33 = Vec::new();
					for _ in 0..v32 {
						v33.push(ProcessInfo::read(r)?);
					}
					v33
				})
			} else {
				Err(Error::read(r)?)
			})
		}
	}
}

#[derive(Clone, Debug, PartialEq)]
pub struct ConfigEntry {
	pub key: String,
	pub value: String,
}

impl ConfigEntry {
	pub fn encode(&self, out: &mut [u8]) -> Option<usize> {
		let mut w = SliceWriter::new(out);
		self.write(&mut w)?;
		Some(w.pos())
	}
	pub fn encode_vec(&self) -> Vec<u8> {
		let mut w = VecWriter::new();
		let _ = self.write(&mut w);
		w.into_inner()
	}
	pub fn decode(bytes: &[u8]) -> Option<ConfigEntry> {
		ConfigEntry::read(&mut Reader::new(bytes))
	}
	pub(crate) fn write<W: Sink>(&self, w: &mut W) -> Option<()> {
		w.bytes_lp(self.key.as_bytes())?;
		w.bytes_lp(self.value.as_bytes())?;
		Some(())
	}
	pub(crate) fn read(r: &mut Reader) -> Option<ConfigEntry> {
		let key = r.string_lp()?;
		let value = r.string_lp()?;
		Some(ConfigEntry { key, value })
	}
}

// interface `config` over a channel: opcodes, a Service trait + dispatch, and a Client.
pub mod config {
	use super::*;
	use crate::codec::{Reader, Sink, SliceWriter, Transport, VecWriter};
	use alloc::vec::Vec;

	pub const OP_GET: u16 = 1;
	pub const OP_LIST: u16 = 2;
	pub const OP_SET: u16 = 3;

	pub trait Service {
		fn get(&mut self, key: String) -> Result<String, Error>;
		fn list(&mut self) -> Result<Vec<ConfigEntry>, Error>;
		fn set(&mut self, entry: ConfigEntry) -> Result<(), Error>;
	}

	pub fn dispatch<S: Service>(service: &mut S, request: &[u8], request_handle: u64, out: &mut [u8], reply_handle: &mut u64) -> Option<usize> {
		let mut reader = Reader::with_handle(request, request_handle);
		let r = &mut reader;
		let op = r.u16()?;
		let corr = r.u32()?;
		let mut writer = SliceWriter::new(out);
		let w = &mut writer;
		w.u32(corr)?;
		match op {
			OP_GET => {
				let key = r.string_lp()?;
				let result = service.get(key);
				match &result {
					Ok(v34) => {
						w.u8(1)?;
						w.bytes_lp(v34.as_bytes())?;
					}
					Err(v35) => {
						w.u8(0)?;
						v35.write(w)?;
					}
				}
			}
			OP_LIST => {
				let result = service.list();
				match &result {
					Ok(v36) => {
						w.u8(1)?;
						if v36.len() > u16::MAX as usize {
							return None;
						}
						w.u16(v36.len() as u16)?;
						for v38 in v36.iter() {
							v38.write(w)?;
						}
					}
					Err(v37) => {
						w.u8(0)?;
						v37.write(w)?;
					}
				}
			}
			OP_SET => {
				let entry = ConfigEntry::read(r)?;
				let result = service.set(entry);
				match &result {
					Ok(v39) => {
						w.u8(1)?;
					}
					Err(v40) => {
						w.u8(0)?;
						v40.write(w)?;
					}
				}
			}
			_ => return None,
		}
		*reply_handle = writer.handle();
		Some(writer.pos())
	}

	pub struct Client<T: Transport> {
		transport: T,
		corr: u32,
	}

	impl<T: Transport> Client<T> {
		pub fn new(transport: T) -> Client<T> {
			Client { transport, corr: 0 }
		}
		pub fn into_transport(self) -> T {
			self.transport
		}
		fn next_corr(&mut self) -> u32 {
			let c = self.corr;
			self.corr = self.corr.wrapping_add(1);
			c
		}
		pub fn get(&mut self, key: &str) -> Option<Result<String, Error>> {
			let corr = self.next_corr();
			let mut writer = VecWriter::new();
			let w = &mut writer;
			w.u16(OP_GET)?;
			w.u32(corr)?;
			w.bytes_lp(key.as_bytes())?;
			let request_handle = writer.handle();
			let request = writer.into_inner();
			let (reply, reply_handle) = self.transport.call(&request, request_handle)?;
			let mut reader = Reader::with_handle(&reply, reply_handle);
			let r = &mut reader;
			if r.u32()? != corr {
				return None;
			}
			Some(if r.u8()? != 0 { Ok(r.string_lp()?) } else { Err(Error::read(r)?) })
		}
		pub fn list(&mut self) -> Option<Result<Vec<ConfigEntry>, Error>> {
			let corr = self.next_corr();
			let mut writer = VecWriter::new();
			let w = &mut writer;
			w.u16(OP_LIST)?;
			w.u32(corr)?;
			let request_handle = writer.handle();
			let request = writer.into_inner();
			let (reply, reply_handle) = self.transport.call(&request, request_handle)?;
			let mut reader = Reader::with_handle(&reply, reply_handle);
			let r = &mut reader;
			if r.u32()? != corr {
				return None;
			}
			Some(if r.u8()? != 0 {
				Ok({
					let v41 = r.u16()? as usize;
					let mut v42 = Vec::new();
					for _ in 0..v41 {
						v42.push(ConfigEntry::read(r)?);
					}
					v42
				})
			} else {
				Err(Error::read(r)?)
			})
		}
		pub fn set(&mut self, entry: &ConfigEntry) -> Option<Result<(), Error>> {
			let corr = self.next_corr();
			let mut writer = VecWriter::new();
			let w = &mut writer;
			w.u16(OP_SET)?;
			w.u32(corr)?;
			entry.write(w)?;
			let request_handle = writer.handle();
			let request = writer.into_inner();
			let (reply, reply_handle) = self.transport.call(&request, request_handle)?;
			let mut reader = Reader::with_handle(&reply, reply_handle);
			let r = &mut reader;
			if r.u32()? != corr {
				return None;
			}
			Some(if r.u8()? != 0 { Ok(()) } else { Err(Error::read(r)?) })
		}
	}
}

#[derive(Clone, Debug, PartialEq)]
pub struct Picked {
	pub file: u64,
	pub size: u64,
	pub name: String,
}

impl Picked {
	pub fn encode(&self, out: &mut [u8]) -> Option<usize> {
		let mut w = SliceWriter::new(out);
		self.write(&mut w)?;
		Some(w.pos())
	}
	pub fn encode_vec(&self) -> Vec<u8> {
		let mut w = VecWriter::new();
		let _ = self.write(&mut w);
		w.into_inner()
	}
	pub fn decode(bytes: &[u8]) -> Option<Picked> {
		Picked::read(&mut Reader::new(bytes))
	}
	pub(crate) fn write<W: Sink>(&self, w: &mut W) -> Option<()> {
		w.set_handle(self.file);
		w.u32(0)?;
		w.u64(self.size)?;
		w.bytes_lp(self.name.as_bytes())?;
		Some(())
	}
	pub(crate) fn read(r: &mut Reader) -> Option<Picked> {
		let file = {
			let _ = r.u32()?;
			r.take_handle()
		};
		let size = r.u64()?;
		let name = r.string_lp()?;
		Some(Picked { file, size, name })
	}
}

// interface `picker` over a channel: opcodes, a Service trait + dispatch, and a Client.
pub mod picker {
	use super::*;
	use crate::codec::{Reader, Sink, SliceWriter, Transport, VecWriter};
	use alloc::vec::Vec;

	pub const OP_PICK: u16 = 1;

	pub trait Service {
		fn pick(&mut self) -> Result<Picked, Error>;
	}

	pub fn dispatch<S: Service>(service: &mut S, request: &[u8], request_handle: u64, out: &mut [u8], reply_handle: &mut u64) -> Option<usize> {
		let mut reader = Reader::with_handle(request, request_handle);
		let r = &mut reader;
		let op = r.u16()?;
		let corr = r.u32()?;
		let mut writer = SliceWriter::new(out);
		let w = &mut writer;
		w.u32(corr)?;
		match op {
			OP_PICK => {
				let result = service.pick();
				match &result {
					Ok(v43) => {
						w.u8(1)?;
						v43.write(w)?;
					}
					Err(v44) => {
						w.u8(0)?;
						v44.write(w)?;
					}
				}
			}
			_ => return None,
		}
		*reply_handle = writer.handle();
		Some(writer.pos())
	}

	pub struct Client<T: Transport> {
		transport: T,
		corr: u32,
	}

	impl<T: Transport> Client<T> {
		pub fn new(transport: T) -> Client<T> {
			Client { transport, corr: 0 }
		}
		pub fn into_transport(self) -> T {
			self.transport
		}
		fn next_corr(&mut self) -> u32 {
			let c = self.corr;
			self.corr = self.corr.wrapping_add(1);
			c
		}
		pub fn pick(&mut self) -> Option<Result<Picked, Error>> {
			let corr = self.next_corr();
			let mut writer = VecWriter::new();
			let w = &mut writer;
			w.u16(OP_PICK)?;
			w.u32(corr)?;
			let request_handle = writer.handle();
			let request = writer.into_inner();
			let (reply, reply_handle) = self.transport.call(&request, request_handle)?;
			let mut reader = Reader::with_handle(&reply, reply_handle);
			let r = &mut reader;
			if r.u32()? != corr {
				return None;
			}
			Some(if r.u8()? != 0 { Ok(Picked::read(r)?) } else { Err(Error::read(r)?) })
		}
	}
}

#[derive(Clone, Debug, PartialEq)]
pub struct Ipv4Addr {
	pub a: u8,
	pub b: u8,
	pub c: u8,
	pub d: u8,
}

impl Ipv4Addr {
	pub fn encode(&self, out: &mut [u8]) -> Option<usize> {
		let mut w = SliceWriter::new(out);
		self.write(&mut w)?;
		Some(w.pos())
	}
	pub fn encode_vec(&self) -> Vec<u8> {
		let mut w = VecWriter::new();
		let _ = self.write(&mut w);
		w.into_inner()
	}
	pub fn decode(bytes: &[u8]) -> Option<Ipv4Addr> {
		Ipv4Addr::read(&mut Reader::new(bytes))
	}
	pub(crate) fn write<W: Sink>(&self, w: &mut W) -> Option<()> {
		w.u8(self.a)?;
		w.u8(self.b)?;
		w.u8(self.c)?;
		w.u8(self.d)?;
		Some(())
	}
	pub(crate) fn read(r: &mut Reader) -> Option<Ipv4Addr> {
		let a = r.u8()?;
		let b = r.u8()?;
		let c = r.u8()?;
		let d = r.u8()?;
		Some(Ipv4Addr { a, b, c, d })
	}
}

#[derive(Clone, Debug, PartialEq)]
pub struct Endpoint {
	pub addr: Ipv4Addr,
	pub port: u16,
}

impl Endpoint {
	pub fn encode(&self, out: &mut [u8]) -> Option<usize> {
		let mut w = SliceWriter::new(out);
		self.write(&mut w)?;
		Some(w.pos())
	}
	pub fn encode_vec(&self) -> Vec<u8> {
		let mut w = VecWriter::new();
		let _ = self.write(&mut w);
		w.into_inner()
	}
	pub fn decode(bytes: &[u8]) -> Option<Endpoint> {
		Endpoint::read(&mut Reader::new(bytes))
	}
	pub(crate) fn write<W: Sink>(&self, w: &mut W) -> Option<()> {
		self.addr.write(w)?;
		w.u16(self.port)?;
		Some(())
	}
	pub(crate) fn read(r: &mut Reader) -> Option<Endpoint> {
		let addr = Ipv4Addr::read(r)?;
		let port = r.u16()?;
		Some(Endpoint { addr, port })
	}
}

#[derive(Clone, Debug, PartialEq)]
pub struct Neighbor {
	pub addr: Ipv4Addr,
	pub mac: Vec<u8>,
}

impl Neighbor {
	pub fn encode(&self, out: &mut [u8]) -> Option<usize> {
		let mut w = SliceWriter::new(out);
		self.write(&mut w)?;
		Some(w.pos())
	}
	pub fn encode_vec(&self) -> Vec<u8> {
		let mut w = VecWriter::new();
		let _ = self.write(&mut w);
		w.into_inner()
	}
	pub fn decode(bytes: &[u8]) -> Option<Neighbor> {
		Neighbor::read(&mut Reader::new(bytes))
	}
	pub(crate) fn write<W: Sink>(&self, w: &mut W) -> Option<()> {
		self.addr.write(w)?;
		if self.mac.len() > u16::MAX as usize {
			return None;
		}
		w.u16(self.mac.len() as u16)?;
		for v45 in self.mac.iter() {
			w.u8(*v45)?;
		}
		Some(())
	}
	pub(crate) fn read(r: &mut Reader) -> Option<Neighbor> {
		let addr = Ipv4Addr::read(r)?;
		let mac = {
			let v46 = r.u16()? as usize;
			let mut v47 = Vec::new();
			for _ in 0..v46 {
				v47.push(r.u8()?);
			}
			v47
		};
		Some(Neighbor { addr, mac })
	}
}

#[derive(Clone, Debug, PartialEq)]
pub struct NetInfo {
	pub addr: Ipv4Addr,
	pub mac: Vec<u8>,
	pub gateway: Ipv4Addr,
	pub neighbors: Vec<Neighbor>,
}

impl NetInfo {
	pub fn encode(&self, out: &mut [u8]) -> Option<usize> {
		let mut w = SliceWriter::new(out);
		self.write(&mut w)?;
		Some(w.pos())
	}
	pub fn encode_vec(&self) -> Vec<u8> {
		let mut w = VecWriter::new();
		let _ = self.write(&mut w);
		w.into_inner()
	}
	pub fn decode(bytes: &[u8]) -> Option<NetInfo> {
		NetInfo::read(&mut Reader::new(bytes))
	}
	pub(crate) fn write<W: Sink>(&self, w: &mut W) -> Option<()> {
		self.addr.write(w)?;
		if self.mac.len() > u16::MAX as usize {
			return None;
		}
		w.u16(self.mac.len() as u16)?;
		for v48 in self.mac.iter() {
			w.u8(*v48)?;
		}
		self.gateway.write(w)?;
		if self.neighbors.len() > u16::MAX as usize {
			return None;
		}
		w.u16(self.neighbors.len() as u16)?;
		for v49 in self.neighbors.iter() {
			v49.write(w)?;
		}
		Some(())
	}
	pub(crate) fn read(r: &mut Reader) -> Option<NetInfo> {
		let addr = Ipv4Addr::read(r)?;
		let mac = {
			let v50 = r.u16()? as usize;
			let mut v51 = Vec::new();
			for _ in 0..v50 {
				v51.push(r.u8()?);
			}
			v51
		};
		let gateway = Ipv4Addr::read(r)?;
		let neighbors = {
			let v52 = r.u16()? as usize;
			let mut v53 = Vec::new();
			for _ in 0..v52 {
				v53.push(Neighbor::read(r)?);
			}
			v53
		};
		Some(NetInfo { addr, mac, gateway, neighbors })
	}
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[repr(u8)]
pub enum PingStatus {
	Reply = 0,
	Timeout = 1,
	Unreachable = 2,
}

impl PingStatus {
	pub fn encode(&self, out: &mut [u8]) -> Option<usize> {
		let mut w = SliceWriter::new(out);
		self.write(&mut w)?;
		Some(w.pos())
	}
	pub fn encode_vec(&self) -> Vec<u8> {
		let mut w = VecWriter::new();
		let _ = self.write(&mut w);
		w.into_inner()
	}
	pub fn decode(bytes: &[u8]) -> Option<PingStatus> {
		PingStatus::read(&mut Reader::new(bytes))
	}
	pub(crate) fn write<W: Sink>(&self, w: &mut W) -> Option<()> {
		w.u8(*self as u8)
	}
	pub(crate) fn read(r: &mut Reader) -> Option<PingStatus> {
		match r.u8()? {
			0 => Some(PingStatus::Reply),
			1 => Some(PingStatus::Timeout),
			2 => Some(PingStatus::Unreachable),
			_ => None,
		}
	}
}

#[derive(Clone, Debug, PartialEq)]
pub struct TcpRequest {
	pub ep: Endpoint,
	pub request: Vec<u8>,
}

impl TcpRequest {
	pub fn encode(&self, out: &mut [u8]) -> Option<usize> {
		let mut w = SliceWriter::new(out);
		self.write(&mut w)?;
		Some(w.pos())
	}
	pub fn encode_vec(&self) -> Vec<u8> {
		let mut w = VecWriter::new();
		let _ = self.write(&mut w);
		w.into_inner()
	}
	pub fn decode(bytes: &[u8]) -> Option<TcpRequest> {
		TcpRequest::read(&mut Reader::new(bytes))
	}
	pub(crate) fn write<W: Sink>(&self, w: &mut W) -> Option<()> {
		self.ep.write(w)?;
		if self.request.len() > u16::MAX as usize {
			return None;
		}
		w.u16(self.request.len() as u16)?;
		for v54 in self.request.iter() {
			w.u8(*v54)?;
		}
		Some(())
	}
	pub(crate) fn read(r: &mut Reader) -> Option<TcpRequest> {
		let ep = Endpoint::read(r)?;
		let request = {
			let v55 = r.u16()? as usize;
			let mut v56 = Vec::new();
			for _ in 0..v55 {
				v56.push(r.u8()?);
			}
			v56
		};
		Some(TcpRequest { ep, request })
	}
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[repr(u8)]
pub enum SockState {
	Closed = 0,
	SynSent = 1,
	SynRcvd = 2,
	Established = 3,
	FinWait = 4,
	Listen = 5,
}

impl SockState {
	pub fn encode(&self, out: &mut [u8]) -> Option<usize> {
		let mut w = SliceWriter::new(out);
		self.write(&mut w)?;
		Some(w.pos())
	}
	pub fn encode_vec(&self) -> Vec<u8> {
		let mut w = VecWriter::new();
		let _ = self.write(&mut w);
		w.into_inner()
	}
	pub fn decode(bytes: &[u8]) -> Option<SockState> {
		SockState::read(&mut Reader::new(bytes))
	}
	pub(crate) fn write<W: Sink>(&self, w: &mut W) -> Option<()> {
		w.u8(*self as u8)
	}
	pub(crate) fn read(r: &mut Reader) -> Option<SockState> {
		match r.u8()? {
			0 => Some(SockState::Closed),
			1 => Some(SockState::SynSent),
			2 => Some(SockState::SynRcvd),
			3 => Some(SockState::Established),
			4 => Some(SockState::FinWait),
			5 => Some(SockState::Listen),
			_ => None,
		}
	}
}

#[derive(Clone, Debug, PartialEq)]
pub struct SockInfo {
	pub local_port: u16,
	pub remote: Endpoint,
	pub state: SockState,
}

impl SockInfo {
	pub fn encode(&self, out: &mut [u8]) -> Option<usize> {
		let mut w = SliceWriter::new(out);
		self.write(&mut w)?;
		Some(w.pos())
	}
	pub fn encode_vec(&self) -> Vec<u8> {
		let mut w = VecWriter::new();
		let _ = self.write(&mut w);
		w.into_inner()
	}
	pub fn decode(bytes: &[u8]) -> Option<SockInfo> {
		SockInfo::read(&mut Reader::new(bytes))
	}
	pub(crate) fn write<W: Sink>(&self, w: &mut W) -> Option<()> {
		w.u16(self.local_port)?;
		self.remote.write(w)?;
		self.state.write(w)?;
		Some(())
	}
	pub(crate) fn read(r: &mut Reader) -> Option<SockInfo> {
		let local_port = r.u16()?;
		let remote = Endpoint::read(r)?;
		let state = SockState::read(r)?;
		Some(SockInfo { local_port, remote, state })
	}
}

// interface `network` over a channel: opcodes, a Service trait + dispatch, and a Client.
pub mod network {
	use super::*;
	use crate::codec::{Reader, Sink, SliceWriter, Transport, VecWriter};
	use alloc::vec::Vec;

	pub const OP_INFO: u16 = 1;
	pub const OP_RESOLVE: u16 = 2;
	pub const OP_PING: u16 = 3;
	pub const OP_FETCH: u16 = 4;
	pub const OP_CONNECT: u16 = 5;
	pub const OP_OPEN: u16 = 6;
	pub const OP_LISTEN: u16 = 7;
	pub const OP_SOCKETS: u16 = 8;
	pub const OP_SNTP: u16 = 9;

	pub trait Service {
		fn info(&mut self) -> Result<NetInfo, Error>;
		fn resolve(&mut self, name: String) -> Result<Ipv4Addr, Error>;
		fn ping(&mut self, addr: Ipv4Addr) -> Result<PingStatus, Error>;
		fn fetch(&mut self, req: TcpRequest) -> Result<Vec<u8>, Error>;
		fn connect(&mut self, ep: Endpoint) -> Result<u64, Error>;
		fn open(&mut self) -> Result<u64, Error>;
		fn listen(&mut self, port: u16) -> Result<u64, Error>;
		fn sockets(&mut self) -> Result<Vec<SockInfo>, Error>;
		fn sntp(&mut self, server: Ipv4Addr) -> Result<u64, Error>;
	}

	pub fn dispatch<S: Service>(service: &mut S, request: &[u8], request_handle: u64, out: &mut [u8], reply_handle: &mut u64) -> Option<usize> {
		let mut reader = Reader::with_handle(request, request_handle);
		let r = &mut reader;
		let op = r.u16()?;
		let corr = r.u32()?;
		let mut writer = SliceWriter::new(out);
		let w = &mut writer;
		w.u32(corr)?;
		match op {
			OP_INFO => {
				let result = service.info();
				match &result {
					Ok(v57) => {
						w.u8(1)?;
						v57.write(w)?;
					}
					Err(v58) => {
						w.u8(0)?;
						v58.write(w)?;
					}
				}
			}
			OP_RESOLVE => {
				let name = r.string_lp()?;
				let result = service.resolve(name);
				match &result {
					Ok(v59) => {
						w.u8(1)?;
						v59.write(w)?;
					}
					Err(v60) => {
						w.u8(0)?;
						v60.write(w)?;
					}
				}
			}
			OP_PING => {
				let addr = Ipv4Addr::read(r)?;
				let result = service.ping(addr);
				match &result {
					Ok(v61) => {
						w.u8(1)?;
						v61.write(w)?;
					}
					Err(v62) => {
						w.u8(0)?;
						v62.write(w)?;
					}
				}
			}
			OP_FETCH => {
				let req = TcpRequest::read(r)?;
				let result = service.fetch(req);
				match &result {
					Ok(v63) => {
						w.u8(1)?;
						if v63.len() > u16::MAX as usize {
							return None;
						}
						w.u16(v63.len() as u16)?;
						for v65 in v63.iter() {
							w.u8(*v65)?;
						}
					}
					Err(v64) => {
						w.u8(0)?;
						v64.write(w)?;
					}
				}
			}
			OP_CONNECT => {
				let ep = Endpoint::read(r)?;
				let result = service.connect(ep);
				match &result {
					Ok(v66) => {
						w.u8(1)?;
						w.set_handle(*v66);
						w.u32(0)?;
					}
					Err(v67) => {
						w.u8(0)?;
						v67.write(w)?;
					}
				}
			}
			OP_OPEN => {
				let result = service.open();
				match &result {
					Ok(v68) => {
						w.u8(1)?;
						w.set_handle(*v68);
						w.u32(0)?;
					}
					Err(v69) => {
						w.u8(0)?;
						v69.write(w)?;
					}
				}
			}
			OP_LISTEN => {
				let port = r.u16()?;
				let result = service.listen(port);
				match &result {
					Ok(v70) => {
						w.u8(1)?;
						w.set_handle(*v70);
						w.u32(0)?;
					}
					Err(v71) => {
						w.u8(0)?;
						v71.write(w)?;
					}
				}
			}
			OP_SOCKETS => {
				let result = service.sockets();
				match &result {
					Ok(v72) => {
						w.u8(1)?;
						if v72.len() > u16::MAX as usize {
							return None;
						}
						w.u16(v72.len() as u16)?;
						for v74 in v72.iter() {
							v74.write(w)?;
						}
					}
					Err(v73) => {
						w.u8(0)?;
						v73.write(w)?;
					}
				}
			}
			OP_SNTP => {
				let server = Ipv4Addr::read(r)?;
				let result = service.sntp(server);
				match &result {
					Ok(v75) => {
						w.u8(1)?;
						w.u64(*v75)?;
					}
					Err(v76) => {
						w.u8(0)?;
						v76.write(w)?;
					}
				}
			}
			_ => return None,
		}
		*reply_handle = writer.handle();
		Some(writer.pos())
	}

	pub struct Client<T: Transport> {
		transport: T,
		corr: u32,
	}

	impl<T: Transport> Client<T> {
		pub fn new(transport: T) -> Client<T> {
			Client { transport, corr: 0 }
		}
		pub fn into_transport(self) -> T {
			self.transport
		}
		fn next_corr(&mut self) -> u32 {
			let c = self.corr;
			self.corr = self.corr.wrapping_add(1);
			c
		}
		pub fn info(&mut self) -> Option<Result<NetInfo, Error>> {
			let corr = self.next_corr();
			let mut writer = VecWriter::new();
			let w = &mut writer;
			w.u16(OP_INFO)?;
			w.u32(corr)?;
			let request_handle = writer.handle();
			let request = writer.into_inner();
			let (reply, reply_handle) = self.transport.call(&request, request_handle)?;
			let mut reader = Reader::with_handle(&reply, reply_handle);
			let r = &mut reader;
			if r.u32()? != corr {
				return None;
			}
			Some(if r.u8()? != 0 { Ok(NetInfo::read(r)?) } else { Err(Error::read(r)?) })
		}
		pub fn resolve(&mut self, name: &str) -> Option<Result<Ipv4Addr, Error>> {
			let corr = self.next_corr();
			let mut writer = VecWriter::new();
			let w = &mut writer;
			w.u16(OP_RESOLVE)?;
			w.u32(corr)?;
			w.bytes_lp(name.as_bytes())?;
			let request_handle = writer.handle();
			let request = writer.into_inner();
			let (reply, reply_handle) = self.transport.call(&request, request_handle)?;
			let mut reader = Reader::with_handle(&reply, reply_handle);
			let r = &mut reader;
			if r.u32()? != corr {
				return None;
			}
			Some(if r.u8()? != 0 { Ok(Ipv4Addr::read(r)?) } else { Err(Error::read(r)?) })
		}
		pub fn ping(&mut self, addr: &Ipv4Addr) -> Option<Result<PingStatus, Error>> {
			let corr = self.next_corr();
			let mut writer = VecWriter::new();
			let w = &mut writer;
			w.u16(OP_PING)?;
			w.u32(corr)?;
			addr.write(w)?;
			let request_handle = writer.handle();
			let request = writer.into_inner();
			let (reply, reply_handle) = self.transport.call(&request, request_handle)?;
			let mut reader = Reader::with_handle(&reply, reply_handle);
			let r = &mut reader;
			if r.u32()? != corr {
				return None;
			}
			Some(if r.u8()? != 0 { Ok(PingStatus::read(r)?) } else { Err(Error::read(r)?) })
		}
		pub fn fetch(&mut self, req: &TcpRequest) -> Option<Result<Vec<u8>, Error>> {
			let corr = self.next_corr();
			let mut writer = VecWriter::new();
			let w = &mut writer;
			w.u16(OP_FETCH)?;
			w.u32(corr)?;
			req.write(w)?;
			let request_handle = writer.handle();
			let request = writer.into_inner();
			let (reply, reply_handle) = self.transport.call(&request, request_handle)?;
			let mut reader = Reader::with_handle(&reply, reply_handle);
			let r = &mut reader;
			if r.u32()? != corr {
				return None;
			}
			Some(if r.u8()? != 0 {
				Ok({
					let v77 = r.u16()? as usize;
					let mut v78 = Vec::new();
					for _ in 0..v77 {
						v78.push(r.u8()?);
					}
					v78
				})
			} else {
				Err(Error::read(r)?)
			})
		}
		pub fn connect(&mut self, ep: &Endpoint) -> Option<Result<u64, Error>> {
			let corr = self.next_corr();
			let mut writer = VecWriter::new();
			let w = &mut writer;
			w.u16(OP_CONNECT)?;
			w.u32(corr)?;
			ep.write(w)?;
			let request_handle = writer.handle();
			let request = writer.into_inner();
			let (reply, reply_handle) = self.transport.call(&request, request_handle)?;
			let mut reader = Reader::with_handle(&reply, reply_handle);
			let r = &mut reader;
			if r.u32()? != corr {
				return None;
			}
			Some(if r.u8()? != 0 {
				Ok({
					let _ = r.u32()?;
					r.take_handle()
				})
			} else {
				Err(Error::read(r)?)
			})
		}
		pub fn open(&mut self) -> Option<Result<u64, Error>> {
			let corr = self.next_corr();
			let mut writer = VecWriter::new();
			let w = &mut writer;
			w.u16(OP_OPEN)?;
			w.u32(corr)?;
			let request_handle = writer.handle();
			let request = writer.into_inner();
			let (reply, reply_handle) = self.transport.call(&request, request_handle)?;
			let mut reader = Reader::with_handle(&reply, reply_handle);
			let r = &mut reader;
			if r.u32()? != corr {
				return None;
			}
			Some(if r.u8()? != 0 {
				Ok({
					let _ = r.u32()?;
					r.take_handle()
				})
			} else {
				Err(Error::read(r)?)
			})
		}
		pub fn listen(&mut self, port: &u16) -> Option<Result<u64, Error>> {
			let corr = self.next_corr();
			let mut writer = VecWriter::new();
			let w = &mut writer;
			w.u16(OP_LISTEN)?;
			w.u32(corr)?;
			w.u16(*port)?;
			let request_handle = writer.handle();
			let request = writer.into_inner();
			let (reply, reply_handle) = self.transport.call(&request, request_handle)?;
			let mut reader = Reader::with_handle(&reply, reply_handle);
			let r = &mut reader;
			if r.u32()? != corr {
				return None;
			}
			Some(if r.u8()? != 0 {
				Ok({
					let _ = r.u32()?;
					r.take_handle()
				})
			} else {
				Err(Error::read(r)?)
			})
		}
		pub fn sockets(&mut self) -> Option<Result<Vec<SockInfo>, Error>> {
			let corr = self.next_corr();
			let mut writer = VecWriter::new();
			let w = &mut writer;
			w.u16(OP_SOCKETS)?;
			w.u32(corr)?;
			let request_handle = writer.handle();
			let request = writer.into_inner();
			let (reply, reply_handle) = self.transport.call(&request, request_handle)?;
			let mut reader = Reader::with_handle(&reply, reply_handle);
			let r = &mut reader;
			if r.u32()? != corr {
				return None;
			}
			Some(if r.u8()? != 0 {
				Ok({
					let v79 = r.u16()? as usize;
					let mut v80 = Vec::new();
					for _ in 0..v79 {
						v80.push(SockInfo::read(r)?);
					}
					v80
				})
			} else {
				Err(Error::read(r)?)
			})
		}
		pub fn sntp(&mut self, server: &Ipv4Addr) -> Option<Result<u64, Error>> {
			let corr = self.next_corr();
			let mut writer = VecWriter::new();
			let w = &mut writer;
			w.u16(OP_SNTP)?;
			w.u32(corr)?;
			server.write(w)?;
			let request_handle = writer.handle();
			let request = writer.into_inner();
			let (reply, reply_handle) = self.transport.call(&request, request_handle)?;
			let mut reader = Reader::with_handle(&reply, reply_handle);
			let r = &mut reader;
			if r.u32()? != corr {
				return None;
			}
			Some(if r.u8()? != 0 { Ok(r.u64()?) } else { Err(Error::read(r)?) })
		}
	}
}

// interface `socket` over a channel: opcodes, a Service trait + dispatch, and a Client.
pub mod socket {
	use super::*;
	use crate::codec::{Reader, Sink, SliceWriter, Transport, VecWriter};
	use alloc::vec::Vec;

	pub const OP_SEND: u16 = 1;
	pub const OP_RECV: u16 = 2;
	pub const OP_CLOSE: u16 = 3;

	pub trait Service {
		fn send(&mut self, data: crate::codec::Buffer) -> Result<u32, Error>;
		fn recv(&mut self) -> Vec<Chunk>;
		fn close(&mut self) -> Result<(), Error>;
	}

	pub fn dispatch<S: Service>(service: &mut S, request: &[u8], request_handle: u64, out: &mut [u8], reply_handle: &mut u64) -> Option<usize> {
		let mut reader = Reader::with_handle(request, request_handle);
		let r = &mut reader;
		let op = r.u16()?;
		let corr = r.u32()?;
		let mut writer = SliceWriter::new(out);
		let w = &mut writer;
		w.u32(corr)?;
		match op {
			OP_SEND => {
				let data = {
					let len = r.u64()?;
					let handle = r.take_handle();
					crate::codec::Buffer { handle, len }
				};
				let result = service.send(data);
				match &result {
					Ok(v81) => {
						w.u8(1)?;
						w.u32(*v81)?;
					}
					Err(v82) => {
						w.u8(0)?;
						v82.write(w)?;
					}
				}
			}
			OP_CLOSE => {
				let result = service.close();
				match &result {
					Ok(v83) => {
						w.u8(1)?;
					}
					Err(v84) => {
						w.u8(0)?;
						v84.write(w)?;
					}
				}
			}
			_ => return None,
		}
		*reply_handle = writer.handle();
		Some(writer.pos())
	}

	pub fn recv_open<S: Service>(service: &mut S, request: &[u8]) -> Option<(u32, Vec<Chunk>)> {
		let mut reader = Reader::new(request);
		let r = &mut reader;
		let _op = r.u16()?;
		let corr = r.u32()?;
		let items = service.recv();
		Some((corr, items))
	}
	pub fn recv_frame(seq: u32, item: &Chunk, out: &mut [u8]) -> Option<usize> {
		let mut writer = SliceWriter::new(out);
		let w = &mut writer;
		w.u32(seq)?;
		item.write(w)?;
		Some(writer.pos())
	}
	pub fn recv_read(msg: &[u8]) -> Option<Chunk> {
		let mut reader = Reader::new(msg);
		let r = &mut reader;
		let _seq = r.u32()?;
		Some(Chunk::read(r)?)
	}

	pub struct Client<T: Transport> {
		transport: T,
		corr: u32,
	}

	impl<T: Transport> Client<T> {
		pub fn new(transport: T) -> Client<T> {
			Client { transport, corr: 0 }
		}
		pub fn into_transport(self) -> T {
			self.transport
		}
		fn next_corr(&mut self) -> u32 {
			let c = self.corr;
			self.corr = self.corr.wrapping_add(1);
			c
		}
		pub fn send(&mut self, data: &crate::codec::Buffer) -> Option<Result<u32, Error>> {
			let corr = self.next_corr();
			let mut writer = VecWriter::new();
			let w = &mut writer;
			w.u16(OP_SEND)?;
			w.u32(corr)?;
			w.set_handle(data.handle);
			w.u64(data.len)?;
			let request_handle = writer.handle();
			let request = writer.into_inner();
			let (reply, reply_handle) = self.transport.call(&request, request_handle)?;
			let mut reader = Reader::with_handle(&reply, reply_handle);
			let r = &mut reader;
			if r.u32()? != corr {
				return None;
			}
			Some(if r.u8()? != 0 { Ok(r.u32()?) } else { Err(Error::read(r)?) })
		}
		pub fn recv(&mut self) -> Option<u64> {
			let corr = self.next_corr();
			let mut writer = VecWriter::new();
			let w = &mut writer;
			w.u16(OP_RECV)?;
			w.u32(corr)?;
			let request = writer.into_inner();
			let (reply, reply_handle) = self.transport.call(&request, 0)?;
			let mut reader = Reader::new(&reply);
			let r = &mut reader;
			if r.u32()? != corr || reply_handle == 0 {
				return None;
			}
			Some(reply_handle)
		}
		pub fn close(&mut self) -> Option<Result<(), Error>> {
			let corr = self.next_corr();
			let mut writer = VecWriter::new();
			let w = &mut writer;
			w.u16(OP_CLOSE)?;
			w.u32(corr)?;
			let request_handle = writer.handle();
			let request = writer.into_inner();
			let (reply, reply_handle) = self.transport.call(&request, request_handle)?;
			let mut reader = Reader::with_handle(&reply, reply_handle);
			let r = &mut reader;
			if r.u32()? != corr {
				return None;
			}
			Some(if r.u8()? != 0 { Ok(()) } else { Err(Error::read(r)?) })
		}
	}
}

#[derive(Clone, Debug, PartialEq)]
pub struct Chunk {
	pub data: Vec<u8>,
}

impl Chunk {
	pub fn encode(&self, out: &mut [u8]) -> Option<usize> {
		let mut w = SliceWriter::new(out);
		self.write(&mut w)?;
		Some(w.pos())
	}
	pub fn encode_vec(&self) -> Vec<u8> {
		let mut w = VecWriter::new();
		let _ = self.write(&mut w);
		w.into_inner()
	}
	pub fn decode(bytes: &[u8]) -> Option<Chunk> {
		Chunk::read(&mut Reader::new(bytes))
	}
	pub(crate) fn write<W: Sink>(&self, w: &mut W) -> Option<()> {
		if self.data.len() > u16::MAX as usize {
			return None;
		}
		w.u16(self.data.len() as u16)?;
		for v85 in self.data.iter() {
			w.u8(*v85)?;
		}
		Some(())
	}
	pub(crate) fn read(r: &mut Reader) -> Option<Chunk> {
		let data = {
			let v86 = r.u16()? as usize;
			let mut v87 = Vec::new();
			for _ in 0..v86 {
				v87.push(r.u8()?);
			}
			v87
		};
		Some(Chunk { data })
	}
}

// interface `listener` over a channel: opcodes, a Service trait + dispatch, and a Client.
pub mod listener {
	use super::*;
	use crate::codec::{Reader, Sink, SliceWriter, Transport, VecWriter};
	use alloc::vec::Vec;

	pub const OP_ACCEPT: u16 = 1;

	pub trait Service {
		fn accept(&mut self) -> Result<u64, Error>;
	}

	pub fn dispatch<S: Service>(service: &mut S, request: &[u8], request_handle: u64, out: &mut [u8], reply_handle: &mut u64) -> Option<usize> {
		let mut reader = Reader::with_handle(request, request_handle);
		let r = &mut reader;
		let op = r.u16()?;
		let corr = r.u32()?;
		let mut writer = SliceWriter::new(out);
		let w = &mut writer;
		w.u32(corr)?;
		match op {
			OP_ACCEPT => {
				let result = service.accept();
				match &result {
					Ok(v88) => {
						w.u8(1)?;
						w.set_handle(*v88);
						w.u32(0)?;
					}
					Err(v89) => {
						w.u8(0)?;
						v89.write(w)?;
					}
				}
			}
			_ => return None,
		}
		*reply_handle = writer.handle();
		Some(writer.pos())
	}

	pub struct Client<T: Transport> {
		transport: T,
		corr: u32,
	}

	impl<T: Transport> Client<T> {
		pub fn new(transport: T) -> Client<T> {
			Client { transport, corr: 0 }
		}
		pub fn into_transport(self) -> T {
			self.transport
		}
		fn next_corr(&mut self) -> u32 {
			let c = self.corr;
			self.corr = self.corr.wrapping_add(1);
			c
		}
		pub fn accept(&mut self) -> Option<Result<u64, Error>> {
			let corr = self.next_corr();
			let mut writer = VecWriter::new();
			let w = &mut writer;
			w.u16(OP_ACCEPT)?;
			w.u32(corr)?;
			let request_handle = writer.handle();
			let request = writer.into_inner();
			let (reply, reply_handle) = self.transport.call(&request, request_handle)?;
			let mut reader = Reader::with_handle(&reply, reply_handle);
			let r = &mut reader;
			if r.u32()? != corr {
				return None;
			}
			Some(if r.u8()? != 0 {
				Ok({
					let _ = r.u32()?;
					r.take_handle()
				})
			} else {
				Err(Error::read(r)?)
			})
		}
	}
}

#[derive(Clone, Debug, PartialEq)]
pub struct Timestamp {
	pub unix_secs: u64,
}

impl Timestamp {
	pub fn encode(&self, out: &mut [u8]) -> Option<usize> {
		let mut w = SliceWriter::new(out);
		self.write(&mut w)?;
		Some(w.pos())
	}
	pub fn encode_vec(&self) -> Vec<u8> {
		let mut w = VecWriter::new();
		let _ = self.write(&mut w);
		w.into_inner()
	}
	pub fn decode(bytes: &[u8]) -> Option<Timestamp> {
		Timestamp::read(&mut Reader::new(bytes))
	}
	pub(crate) fn write<W: Sink>(&self, w: &mut W) -> Option<()> {
		w.u64(self.unix_secs)?;
		Some(())
	}
	pub(crate) fn read(r: &mut Reader) -> Option<Timestamp> {
		let unix_secs = r.u64()?;
		Some(Timestamp { unix_secs })
	}
}

// interface `time` over a channel: opcodes, a Service trait + dispatch, and a Client.
pub mod time {
	use super::*;
	use crate::codec::{Reader, Sink, SliceWriter, Transport, VecWriter};
	use alloc::vec::Vec;

	pub const OP_NOW: u16 = 1;

	pub trait Service {
		fn now(&mut self) -> Result<Timestamp, Error>;
	}

	pub fn dispatch<S: Service>(service: &mut S, request: &[u8], request_handle: u64, out: &mut [u8], reply_handle: &mut u64) -> Option<usize> {
		let mut reader = Reader::with_handle(request, request_handle);
		let r = &mut reader;
		let op = r.u16()?;
		let corr = r.u32()?;
		let mut writer = SliceWriter::new(out);
		let w = &mut writer;
		w.u32(corr)?;
		match op {
			OP_NOW => {
				let result = service.now();
				match &result {
					Ok(v90) => {
						w.u8(1)?;
						v90.write(w)?;
					}
					Err(v91) => {
						w.u8(0)?;
						v91.write(w)?;
					}
				}
			}
			_ => return None,
		}
		*reply_handle = writer.handle();
		Some(writer.pos())
	}

	pub struct Client<T: Transport> {
		transport: T,
		corr: u32,
	}

	impl<T: Transport> Client<T> {
		pub fn new(transport: T) -> Client<T> {
			Client { transport, corr: 0 }
		}
		pub fn into_transport(self) -> T {
			self.transport
		}
		fn next_corr(&mut self) -> u32 {
			let c = self.corr;
			self.corr = self.corr.wrapping_add(1);
			c
		}
		pub fn now(&mut self) -> Option<Result<Timestamp, Error>> {
			let corr = self.next_corr();
			let mut writer = VecWriter::new();
			let w = &mut writer;
			w.u16(OP_NOW)?;
			w.u32(corr)?;
			let request_handle = writer.handle();
			let request = writer.into_inner();
			let (reply, reply_handle) = self.transport.call(&request, request_handle)?;
			let mut reader = Reader::with_handle(&reply, reply_handle);
			let r = &mut reader;
			if r.u32()? != corr {
				return None;
			}
			Some(if r.u8()? != 0 { Ok(Timestamp::read(r)?) } else { Err(Error::read(r)?) })
		}
	}
}

// interface `audio` over a channel: opcodes, a Service trait + dispatch, and a Client.
pub mod audio {
	use super::*;
	use crate::codec::{Reader, Sink, SliceWriter, Transport, VecWriter};
	use alloc::vec::Vec;

	pub const OP_BEEP: u16 = 1;

	pub trait Service {
		fn beep(&mut self, freq: u16, millis: u32) -> Result<(), Error>;
	}

	pub fn dispatch<S: Service>(service: &mut S, request: &[u8], request_handle: u64, out: &mut [u8], reply_handle: &mut u64) -> Option<usize> {
		let mut reader = Reader::with_handle(request, request_handle);
		let r = &mut reader;
		let op = r.u16()?;
		let corr = r.u32()?;
		let mut writer = SliceWriter::new(out);
		let w = &mut writer;
		w.u32(corr)?;
		match op {
			OP_BEEP => {
				let freq = r.u16()?;
				let millis = r.u32()?;
				let result = service.beep(freq, millis);
				match &result {
					Ok(v92) => {
						w.u8(1)?;
					}
					Err(v93) => {
						w.u8(0)?;
						v93.write(w)?;
					}
				}
			}
			_ => return None,
		}
		*reply_handle = writer.handle();
		Some(writer.pos())
	}

	pub struct Client<T: Transport> {
		transport: T,
		corr: u32,
	}

	impl<T: Transport> Client<T> {
		pub fn new(transport: T) -> Client<T> {
			Client { transport, corr: 0 }
		}
		pub fn into_transport(self) -> T {
			self.transport
		}
		fn next_corr(&mut self) -> u32 {
			let c = self.corr;
			self.corr = self.corr.wrapping_add(1);
			c
		}
		pub fn beep(&mut self, freq: &u16, millis: &u32) -> Option<Result<(), Error>> {
			let corr = self.next_corr();
			let mut writer = VecWriter::new();
			let w = &mut writer;
			w.u16(OP_BEEP)?;
			w.u32(corr)?;
			w.u16(*freq)?;
			w.u32(*millis)?;
			let request_handle = writer.handle();
			let request = writer.into_inner();
			let (reply, reply_handle) = self.transport.call(&request, request_handle)?;
			let mut reader = Reader::with_handle(&reply, reply_handle);
			let r = &mut reader;
			if r.u32()? != corr {
				return None;
			}
			Some(if r.u8()? != 0 { Ok(()) } else { Err(Error::read(r)?) })
		}
	}
}

impl Error {
	pub fn to_json(&self) -> String {
		let mut s = String::new();
		self.to_json_into(&mut s);
		s
	}
	pub fn to_text(&self) -> String {
		let mut s = String::new();
		self.to_text_into(&mut s);
		s
	}
	pub(crate) fn to_json_into(&self, out: &mut String) {
		match self {
			Error::Denied => out.push_str("\"denied\""),
			Error::NotFound => out.push_str("\"not-found\""),
			Error::Invalid => out.push_str("\"invalid\""),
			Error::Again => out.push_str("\"again\""),
			Error::Closed => out.push_str("\"closed\""),
		}
	}
	pub(crate) fn to_text_into(&self, out: &mut String) {
		match self {
			Error::Denied => out.push_str("denied"),
			Error::NotFound => out.push_str("not-found"),
			Error::Invalid => out.push_str("invalid"),
			Error::Again => out.push_str("again"),
			Error::Closed => out.push_str("closed"),
		}
	}
}

impl Severity {
	pub fn to_json(&self) -> String {
		let mut s = String::new();
		self.to_json_into(&mut s);
		s
	}
	pub fn to_text(&self) -> String {
		let mut s = String::new();
		self.to_text_into(&mut s);
		s
	}
	pub(crate) fn to_json_into(&self, out: &mut String) {
		match self {
			Severity::Trace => out.push_str("\"trace\""),
			Severity::Debug => out.push_str("\"debug\""),
			Severity::Info => out.push_str("\"info\""),
			Severity::Warn => out.push_str("\"warn\""),
			Severity::Error => out.push_str("\"error\""),
			Severity::Fatal => out.push_str("\"fatal\""),
		}
	}
	pub(crate) fn to_text_into(&self, out: &mut String) {
		match self {
			Severity::Trace => out.push_str("trace"),
			Severity::Debug => out.push_str("debug"),
			Severity::Info => out.push_str("info"),
			Severity::Warn => out.push_str("warn"),
			Severity::Error => out.push_str("error"),
			Severity::Fatal => out.push_str("fatal"),
		}
	}
}

impl Field {
	pub fn to_json(&self) -> String {
		let mut s = String::new();
		self.to_json_into(&mut s);
		s
	}
	pub fn to_text(&self) -> String {
		let mut s = String::new();
		self.to_text_into(&mut s);
		s
	}
	pub(crate) fn to_json_into(&self, out: &mut String) {
		out.push('{');
		out.push_str("\"key\":");
		crate::codec::json_escape(&self.key, out);
		out.push(',');
		out.push_str("\"value\":");
		crate::codec::json_escape(&self.value, out);
		out.push('}');
	}
	pub(crate) fn to_text_into(&self, out: &mut String) {
		out.push('{');
		out.push_str("key=");
		out.push_str(&self.key);
		out.push_str(", ");
		out.push_str("value=");
		out.push_str(&self.value);
		out.push('}');
	}
}

impl Entry {
	pub fn to_json(&self) -> String {
		let mut s = String::new();
		self.to_json_into(&mut s);
		s
	}
	pub fn to_text(&self) -> String {
		let mut s = String::new();
		self.to_text_into(&mut s);
		s
	}
	pub(crate) fn to_json_into(&self, out: &mut String) {
		out.push('{');
		out.push_str("\"timestamp\":");
		let _ = write!(out, "{}", self.timestamp);
		out.push(',');
		out.push_str("\"severity\":");
		self.severity.to_json_into(out);
		out.push(',');
		out.push_str("\"source\":");
		crate::codec::json_escape(&self.source, out);
		out.push(',');
		out.push_str("\"fields\":");
		out.push('[');
		let mut v95 = true;
		for v94 in self.fields.iter() {
			if !v95 {
				out.push(',');
			}
			v95 = false;
			v94.to_json_into(out);
		}
		out.push(']');
		out.push('}');
	}
	pub(crate) fn to_text_into(&self, out: &mut String) {
		out.push('{');
		out.push_str("timestamp=");
		let _ = write!(out, "{}", self.timestamp);
		out.push_str(", ");
		out.push_str("severity=");
		self.severity.to_text_into(out);
		out.push_str(", ");
		out.push_str("source=");
		out.push_str(&self.source);
		out.push_str(", ");
		out.push_str("fields=");
		out.push('[');
		let mut v97 = true;
		for v96 in self.fields.iter() {
			if !v97 {
				out.push_str(", ");
			}
			v97 = false;
			v96.to_text_into(out);
		}
		out.push(']');
		out.push('}');
	}
}

impl Query {
	pub fn to_json(&self) -> String {
		let mut s = String::new();
		self.to_json_into(&mut s);
		s
	}
	pub fn to_text(&self) -> String {
		let mut s = String::new();
		self.to_text_into(&mut s);
		s
	}
	pub(crate) fn to_json_into(&self, out: &mut String) {
		out.push('{');
		out.push_str("\"since\":");
		match &self.since {
			Some(v98) => {
				let _ = write!(out, "{}", v98);
			}
			None => {
				out.push_str("null");
			}
		}
		out.push(',');
		out.push_str("\"min-severity\":");
		match &self.min_severity {
			Some(v99) => {
				v99.to_json_into(out);
			}
			None => {
				out.push_str("null");
			}
		}
		out.push(',');
		out.push_str("\"source\":");
		match &self.source {
			Some(v100) => {
				crate::codec::json_escape(v100, out);
			}
			None => {
				out.push_str("null");
			}
		}
		out.push(',');
		out.push_str("\"limit\":");
		let _ = write!(out, "{}", self.limit);
		out.push('}');
	}
	pub(crate) fn to_text_into(&self, out: &mut String) {
		out.push('{');
		out.push_str("since=");
		match &self.since {
			Some(v101) => {
				let _ = write!(out, "{}", v101);
			}
			None => {
				out.push('-');
			}
		}
		out.push_str(", ");
		out.push_str("min-severity=");
		match &self.min_severity {
			Some(v102) => {
				v102.to_text_into(out);
			}
			None => {
				out.push('-');
			}
		}
		out.push_str(", ");
		out.push_str("source=");
		match &self.source {
			Some(v103) => {
				out.push_str(v103);
			}
			None => {
				out.push('-');
			}
		}
		out.push_str(", ");
		out.push_str("limit=");
		let _ = write!(out, "{}", self.limit);
		out.push('}');
	}
}

impl OpenOpts {
	pub fn to_json(&self) -> String {
		let mut s = String::new();
		self.to_json_into(&mut s);
		s
	}
	pub fn to_text(&self) -> String {
		let mut s = String::new();
		self.to_text_into(&mut s);
		s
	}
	pub(crate) fn to_json_into(&self, out: &mut String) {
		out.push('{');
		out.push_str("\"path\":");
		crate::codec::json_escape(&self.path, out);
		out.push(',');
		out.push_str("\"write\":");
		if self.write {
			out.push_str("true");
		} else {
			out.push_str("false");
		}
		out.push(',');
		out.push_str("\"create\":");
		if self.create {
			out.push_str("true");
		} else {
			out.push_str("false");
		}
		out.push('}');
	}
	pub(crate) fn to_text_into(&self, out: &mut String) {
		out.push('{');
		out.push_str("path=");
		out.push_str(&self.path);
		out.push_str(", ");
		out.push_str("write=");
		if self.write {
			out.push_str("true");
		} else {
			out.push_str("false");
		}
		out.push_str(", ");
		out.push_str("create=");
		if self.create {
			out.push_str("true");
		} else {
			out.push_str("false");
		}
		out.push('}');
	}
}

impl OpenResult {
	pub fn to_json(&self) -> String {
		let mut s = String::new();
		self.to_json_into(&mut s);
		s
	}
	pub fn to_text(&self) -> String {
		let mut s = String::new();
		self.to_text_into(&mut s);
		s
	}
	pub(crate) fn to_json_into(&self, out: &mut String) {
		out.push('{');
		out.push_str("\"file\":");
		let _ = write!(out, "{}", self.file);
		out.push(',');
		out.push_str("\"size\":");
		let _ = write!(out, "{}", self.size);
		out.push('}');
	}
	pub(crate) fn to_text_into(&self, out: &mut String) {
		out.push('{');
		out.push_str("file=");
		let _ = write!(out, "{}", self.file);
		out.push_str(", ");
		out.push_str("size=");
		let _ = write!(out, "{}", self.size);
		out.push('}');
	}
}

impl FileInfo {
	pub fn to_json(&self) -> String {
		let mut s = String::new();
		self.to_json_into(&mut s);
		s
	}
	pub fn to_text(&self) -> String {
		let mut s = String::new();
		self.to_text_into(&mut s);
		s
	}
	pub(crate) fn to_json_into(&self, out: &mut String) {
		out.push('{');
		out.push_str("\"name\":");
		crate::codec::json_escape(&self.name, out);
		out.push(',');
		out.push_str("\"size\":");
		let _ = write!(out, "{}", self.size);
		out.push('}');
	}
	pub(crate) fn to_text_into(&self, out: &mut String) {
		out.push('{');
		out.push_str("name=");
		out.push_str(&self.name);
		out.push_str(", ");
		out.push_str("size=");
		let _ = write!(out, "{}", self.size);
		out.push('}');
	}
}

impl DeviceKind {
	pub fn to_json(&self) -> String {
		let mut s = String::new();
		self.to_json_into(&mut s);
		s
	}
	pub fn to_text(&self) -> String {
		let mut s = String::new();
		self.to_text_into(&mut s);
		s
	}
	pub(crate) fn to_json_into(&self, out: &mut String) {
		match self {
			DeviceKind::Unknown => out.push_str("\"unknown\""),
			DeviceKind::Net => out.push_str("\"net\""),
			DeviceKind::Block => out.push_str("\"block\""),
			DeviceKind::Console => out.push_str("\"console\""),
		}
	}
	pub(crate) fn to_text_into(&self, out: &mut String) {
		match self {
			DeviceKind::Unknown => out.push_str("unknown"),
			DeviceKind::Net => out.push_str("net"),
			DeviceKind::Block => out.push_str("block"),
			DeviceKind::Console => out.push_str("console"),
		}
	}
}

impl DeviceEntry {
	pub fn to_json(&self) -> String {
		let mut s = String::new();
		self.to_json_into(&mut s);
		s
	}
	pub fn to_text(&self) -> String {
		let mut s = String::new();
		self.to_text_into(&mut s);
		s
	}
	pub(crate) fn to_json_into(&self, out: &mut String) {
		out.push('{');
		out.push_str("\"index\":");
		let _ = write!(out, "{}", self.index);
		out.push(',');
		out.push_str("\"kind\":");
		self.kind.to_json_into(out);
		out.push(',');
		out.push_str("\"mmio-len\":");
		let _ = write!(out, "{}", self.mmio_len);
		out.push('}');
	}
	pub(crate) fn to_text_into(&self, out: &mut String) {
		out.push('{');
		out.push_str("index=");
		let _ = write!(out, "{}", self.index);
		out.push_str(", ");
		out.push_str("kind=");
		self.kind.to_text_into(out);
		out.push_str(", ");
		out.push_str("mmio-len=");
		let _ = write!(out, "{}", self.mmio_len);
		out.push('}');
	}
}

impl ProcessInfo {
	pub fn to_json(&self) -> String {
		let mut s = String::new();
		self.to_json_into(&mut s);
		s
	}
	pub fn to_text(&self) -> String {
		let mut s = String::new();
		self.to_text_into(&mut s);
		s
	}
	pub(crate) fn to_json_into(&self, out: &mut String) {
		out.push('{');
		out.push_str("\"koid\":");
		let _ = write!(out, "{}", self.koid);
		out.push(',');
		out.push_str("\"name\":");
		crate::codec::json_escape(&self.name, out);
		out.push('}');
	}
	pub(crate) fn to_text_into(&self, out: &mut String) {
		out.push('{');
		out.push_str("koid=");
		let _ = write!(out, "{}", self.koid);
		out.push_str(", ");
		out.push_str("name=");
		out.push_str(&self.name);
		out.push('}');
	}
}

impl ConfigEntry {
	pub fn to_json(&self) -> String {
		let mut s = String::new();
		self.to_json_into(&mut s);
		s
	}
	pub fn to_text(&self) -> String {
		let mut s = String::new();
		self.to_text_into(&mut s);
		s
	}
	pub(crate) fn to_json_into(&self, out: &mut String) {
		out.push('{');
		out.push_str("\"key\":");
		crate::codec::json_escape(&self.key, out);
		out.push(',');
		out.push_str("\"value\":");
		crate::codec::json_escape(&self.value, out);
		out.push('}');
	}
	pub(crate) fn to_text_into(&self, out: &mut String) {
		out.push('{');
		out.push_str("key=");
		out.push_str(&self.key);
		out.push_str(", ");
		out.push_str("value=");
		out.push_str(&self.value);
		out.push('}');
	}
}

impl Picked {
	pub fn to_json(&self) -> String {
		let mut s = String::new();
		self.to_json_into(&mut s);
		s
	}
	pub fn to_text(&self) -> String {
		let mut s = String::new();
		self.to_text_into(&mut s);
		s
	}
	pub(crate) fn to_json_into(&self, out: &mut String) {
		out.push('{');
		out.push_str("\"file\":");
		let _ = write!(out, "{}", self.file);
		out.push(',');
		out.push_str("\"size\":");
		let _ = write!(out, "{}", self.size);
		out.push(',');
		out.push_str("\"name\":");
		crate::codec::json_escape(&self.name, out);
		out.push('}');
	}
	pub(crate) fn to_text_into(&self, out: &mut String) {
		out.push('{');
		out.push_str("file=");
		let _ = write!(out, "{}", self.file);
		out.push_str(", ");
		out.push_str("size=");
		let _ = write!(out, "{}", self.size);
		out.push_str(", ");
		out.push_str("name=");
		out.push_str(&self.name);
		out.push('}');
	}
}

impl Ipv4Addr {
	pub fn to_json(&self) -> String {
		let mut s = String::new();
		self.to_json_into(&mut s);
		s
	}
	pub fn to_text(&self) -> String {
		let mut s = String::new();
		self.to_text_into(&mut s);
		s
	}
	pub(crate) fn to_json_into(&self, out: &mut String) {
		out.push('{');
		out.push_str("\"a\":");
		let _ = write!(out, "{}", self.a);
		out.push(',');
		out.push_str("\"b\":");
		let _ = write!(out, "{}", self.b);
		out.push(',');
		out.push_str("\"c\":");
		let _ = write!(out, "{}", self.c);
		out.push(',');
		out.push_str("\"d\":");
		let _ = write!(out, "{}", self.d);
		out.push('}');
	}
	pub(crate) fn to_text_into(&self, out: &mut String) {
		out.push('{');
		out.push_str("a=");
		let _ = write!(out, "{}", self.a);
		out.push_str(", ");
		out.push_str("b=");
		let _ = write!(out, "{}", self.b);
		out.push_str(", ");
		out.push_str("c=");
		let _ = write!(out, "{}", self.c);
		out.push_str(", ");
		out.push_str("d=");
		let _ = write!(out, "{}", self.d);
		out.push('}');
	}
}

impl Endpoint {
	pub fn to_json(&self) -> String {
		let mut s = String::new();
		self.to_json_into(&mut s);
		s
	}
	pub fn to_text(&self) -> String {
		let mut s = String::new();
		self.to_text_into(&mut s);
		s
	}
	pub(crate) fn to_json_into(&self, out: &mut String) {
		out.push('{');
		out.push_str("\"addr\":");
		self.addr.to_json_into(out);
		out.push(',');
		out.push_str("\"port\":");
		let _ = write!(out, "{}", self.port);
		out.push('}');
	}
	pub(crate) fn to_text_into(&self, out: &mut String) {
		out.push('{');
		out.push_str("addr=");
		self.addr.to_text_into(out);
		out.push_str(", ");
		out.push_str("port=");
		let _ = write!(out, "{}", self.port);
		out.push('}');
	}
}

impl Neighbor {
	pub fn to_json(&self) -> String {
		let mut s = String::new();
		self.to_json_into(&mut s);
		s
	}
	pub fn to_text(&self) -> String {
		let mut s = String::new();
		self.to_text_into(&mut s);
		s
	}
	pub(crate) fn to_json_into(&self, out: &mut String) {
		out.push('{');
		out.push_str("\"addr\":");
		self.addr.to_json_into(out);
		out.push(',');
		out.push_str("\"mac\":");
		out.push('[');
		let mut v105 = true;
		for v104 in self.mac.iter() {
			if !v105 {
				out.push(',');
			}
			v105 = false;
			let _ = write!(out, "{}", v104);
		}
		out.push(']');
		out.push('}');
	}
	pub(crate) fn to_text_into(&self, out: &mut String) {
		out.push('{');
		out.push_str("addr=");
		self.addr.to_text_into(out);
		out.push_str(", ");
		out.push_str("mac=");
		out.push('[');
		let mut v107 = true;
		for v106 in self.mac.iter() {
			if !v107 {
				out.push_str(", ");
			}
			v107 = false;
			let _ = write!(out, "{}", v106);
		}
		out.push(']');
		out.push('}');
	}
}

impl NetInfo {
	pub fn to_json(&self) -> String {
		let mut s = String::new();
		self.to_json_into(&mut s);
		s
	}
	pub fn to_text(&self) -> String {
		let mut s = String::new();
		self.to_text_into(&mut s);
		s
	}
	pub(crate) fn to_json_into(&self, out: &mut String) {
		out.push('{');
		out.push_str("\"addr\":");
		self.addr.to_json_into(out);
		out.push(',');
		out.push_str("\"mac\":");
		out.push('[');
		let mut v109 = true;
		for v108 in self.mac.iter() {
			if !v109 {
				out.push(',');
			}
			v109 = false;
			let _ = write!(out, "{}", v108);
		}
		out.push(']');
		out.push(',');
		out.push_str("\"gateway\":");
		self.gateway.to_json_into(out);
		out.push(',');
		out.push_str("\"neighbors\":");
		out.push('[');
		let mut v111 = true;
		for v110 in self.neighbors.iter() {
			if !v111 {
				out.push(',');
			}
			v111 = false;
			v110.to_json_into(out);
		}
		out.push(']');
		out.push('}');
	}
	pub(crate) fn to_text_into(&self, out: &mut String) {
		out.push('{');
		out.push_str("addr=");
		self.addr.to_text_into(out);
		out.push_str(", ");
		out.push_str("mac=");
		out.push('[');
		let mut v113 = true;
		for v112 in self.mac.iter() {
			if !v113 {
				out.push_str(", ");
			}
			v113 = false;
			let _ = write!(out, "{}", v112);
		}
		out.push(']');
		out.push_str(", ");
		out.push_str("gateway=");
		self.gateway.to_text_into(out);
		out.push_str(", ");
		out.push_str("neighbors=");
		out.push('[');
		let mut v115 = true;
		for v114 in self.neighbors.iter() {
			if !v115 {
				out.push_str(", ");
			}
			v115 = false;
			v114.to_text_into(out);
		}
		out.push(']');
		out.push('}');
	}
}

impl PingStatus {
	pub fn to_json(&self) -> String {
		let mut s = String::new();
		self.to_json_into(&mut s);
		s
	}
	pub fn to_text(&self) -> String {
		let mut s = String::new();
		self.to_text_into(&mut s);
		s
	}
	pub(crate) fn to_json_into(&self, out: &mut String) {
		match self {
			PingStatus::Reply => out.push_str("\"reply\""),
			PingStatus::Timeout => out.push_str("\"timeout\""),
			PingStatus::Unreachable => out.push_str("\"unreachable\""),
		}
	}
	pub(crate) fn to_text_into(&self, out: &mut String) {
		match self {
			PingStatus::Reply => out.push_str("reply"),
			PingStatus::Timeout => out.push_str("timeout"),
			PingStatus::Unreachable => out.push_str("unreachable"),
		}
	}
}

impl TcpRequest {
	pub fn to_json(&self) -> String {
		let mut s = String::new();
		self.to_json_into(&mut s);
		s
	}
	pub fn to_text(&self) -> String {
		let mut s = String::new();
		self.to_text_into(&mut s);
		s
	}
	pub(crate) fn to_json_into(&self, out: &mut String) {
		out.push('{');
		out.push_str("\"ep\":");
		self.ep.to_json_into(out);
		out.push(',');
		out.push_str("\"request\":");
		out.push('[');
		let mut v117 = true;
		for v116 in self.request.iter() {
			if !v117 {
				out.push(',');
			}
			v117 = false;
			let _ = write!(out, "{}", v116);
		}
		out.push(']');
		out.push('}');
	}
	pub(crate) fn to_text_into(&self, out: &mut String) {
		out.push('{');
		out.push_str("ep=");
		self.ep.to_text_into(out);
		out.push_str(", ");
		out.push_str("request=");
		out.push('[');
		let mut v119 = true;
		for v118 in self.request.iter() {
			if !v119 {
				out.push_str(", ");
			}
			v119 = false;
			let _ = write!(out, "{}", v118);
		}
		out.push(']');
		out.push('}');
	}
}

impl SockState {
	pub fn to_json(&self) -> String {
		let mut s = String::new();
		self.to_json_into(&mut s);
		s
	}
	pub fn to_text(&self) -> String {
		let mut s = String::new();
		self.to_text_into(&mut s);
		s
	}
	pub(crate) fn to_json_into(&self, out: &mut String) {
		match self {
			SockState::Closed => out.push_str("\"closed\""),
			SockState::SynSent => out.push_str("\"syn-sent\""),
			SockState::SynRcvd => out.push_str("\"syn-rcvd\""),
			SockState::Established => out.push_str("\"established\""),
			SockState::FinWait => out.push_str("\"fin-wait\""),
			SockState::Listen => out.push_str("\"listen\""),
		}
	}
	pub(crate) fn to_text_into(&self, out: &mut String) {
		match self {
			SockState::Closed => out.push_str("closed"),
			SockState::SynSent => out.push_str("syn-sent"),
			SockState::SynRcvd => out.push_str("syn-rcvd"),
			SockState::Established => out.push_str("established"),
			SockState::FinWait => out.push_str("fin-wait"),
			SockState::Listen => out.push_str("listen"),
		}
	}
}

impl SockInfo {
	pub fn to_json(&self) -> String {
		let mut s = String::new();
		self.to_json_into(&mut s);
		s
	}
	pub fn to_text(&self) -> String {
		let mut s = String::new();
		self.to_text_into(&mut s);
		s
	}
	pub(crate) fn to_json_into(&self, out: &mut String) {
		out.push('{');
		out.push_str("\"local-port\":");
		let _ = write!(out, "{}", self.local_port);
		out.push(',');
		out.push_str("\"remote\":");
		self.remote.to_json_into(out);
		out.push(',');
		out.push_str("\"state\":");
		self.state.to_json_into(out);
		out.push('}');
	}
	pub(crate) fn to_text_into(&self, out: &mut String) {
		out.push('{');
		out.push_str("local-port=");
		let _ = write!(out, "{}", self.local_port);
		out.push_str(", ");
		out.push_str("remote=");
		self.remote.to_text_into(out);
		out.push_str(", ");
		out.push_str("state=");
		self.state.to_text_into(out);
		out.push('}');
	}
}

impl Chunk {
	pub fn to_json(&self) -> String {
		let mut s = String::new();
		self.to_json_into(&mut s);
		s
	}
	pub fn to_text(&self) -> String {
		let mut s = String::new();
		self.to_text_into(&mut s);
		s
	}
	pub(crate) fn to_json_into(&self, out: &mut String) {
		out.push('{');
		out.push_str("\"data\":");
		out.push('[');
		let mut v121 = true;
		for v120 in self.data.iter() {
			if !v121 {
				out.push(',');
			}
			v121 = false;
			let _ = write!(out, "{}", v120);
		}
		out.push(']');
		out.push('}');
	}
	pub(crate) fn to_text_into(&self, out: &mut String) {
		out.push('{');
		out.push_str("data=");
		out.push('[');
		let mut v123 = true;
		for v122 in self.data.iter() {
			if !v123 {
				out.push_str(", ");
			}
			v123 = false;
			let _ = write!(out, "{}", v122);
		}
		out.push(']');
		out.push('}');
	}
}

impl Timestamp {
	pub fn to_json(&self) -> String {
		let mut s = String::new();
		self.to_json_into(&mut s);
		s
	}
	pub fn to_text(&self) -> String {
		let mut s = String::new();
		self.to_text_into(&mut s);
		s
	}
	pub(crate) fn to_json_into(&self, out: &mut String) {
		out.push('{');
		out.push_str("\"unix-secs\":");
		let _ = write!(out, "{}", self.unix_secs);
		out.push('}');
	}
	pub(crate) fn to_text_into(&self, out: &mut String) {
		out.push('{');
		out.push_str("unix-secs=");
		let _ = write!(out, "{}", self.unix_secs);
		out.push('}');
	}
}

#[cfg(test)]
mod compat {
	use super::*;
	use alloc::string::String;

	#[test]
	fn error_wire_is_stable() {
		let sample = Error::Denied;
		let bytes = sample.encode_vec();
		let golden: &[u8] = &[0];
		assert_eq!(bytes, golden);
		assert_eq!(Error::decode(&bytes).unwrap(), sample);
	}
	#[test]
	fn severity_wire_is_stable() {
		let sample = Severity::Trace;
		let bytes = sample.encode_vec();
		let golden: &[u8] = &[0];
		assert_eq!(bytes, golden);
		assert_eq!(Severity::decode(&bytes).unwrap(), sample);
	}
	#[test]
	fn field_wire_is_stable() {
		let sample = Field { key: String::from("x"), value: String::from("x") };
		let bytes = sample.encode_vec();
		let golden: &[u8] = &[1, 0, 120, 1, 0, 120];
		assert_eq!(bytes, golden);
		assert_eq!(Field::decode(&bytes).unwrap(), sample);
	}
	#[test]
	fn entry_wire_is_stable() {
		let sample = Entry { timestamp: 7, severity: Severity::Trace, source: String::from("x"), fields: alloc::vec![Field { key: String::from("x"), value: String::from("x") }] };
		let bytes = sample.encode_vec();
		let golden: &[u8] = &[7, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 120, 1, 0, 1, 0, 120, 1, 0, 120];
		assert_eq!(bytes, golden);
		assert_eq!(Entry::decode(&bytes).unwrap(), sample);
	}
	#[test]
	fn query_wire_is_stable() {
		let sample = Query { since: Some(7), min_severity: Some(Severity::Trace), source: Some(String::from("x")), limit: 7 };
		let bytes = sample.encode_vec();
		let golden: &[u8] = &[1, 7, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 120, 7, 0, 0, 0];
		assert_eq!(bytes, golden);
		assert_eq!(Query::decode(&bytes).unwrap(), sample);
	}
	#[test]
	fn open_opts_wire_is_stable() {
		let sample = OpenOpts { path: String::from("x"), write: true, create: true };
		let bytes = sample.encode_vec();
		let golden: &[u8] = &[1, 0, 120, 1, 1];
		assert_eq!(bytes, golden);
		assert_eq!(OpenOpts::decode(&bytes).unwrap(), sample);
	}
	#[test]
	fn file_info_wire_is_stable() {
		let sample = FileInfo { name: String::from("x"), size: 7 };
		let bytes = sample.encode_vec();
		let golden: &[u8] = &[1, 0, 120, 7, 0, 0, 0, 0, 0, 0, 0];
		assert_eq!(bytes, golden);
		assert_eq!(FileInfo::decode(&bytes).unwrap(), sample);
	}
	#[test]
	fn device_kind_wire_is_stable() {
		let sample = DeviceKind::Unknown;
		let bytes = sample.encode_vec();
		let golden: &[u8] = &[0];
		assert_eq!(bytes, golden);
		assert_eq!(DeviceKind::decode(&bytes).unwrap(), sample);
	}
	#[test]
	fn device_entry_wire_is_stable() {
		let sample = DeviceEntry { index: 7, kind: DeviceKind::Unknown, mmio_len: 7 };
		let bytes = sample.encode_vec();
		let golden: &[u8] = &[7, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0];
		assert_eq!(bytes, golden);
		assert_eq!(DeviceEntry::decode(&bytes).unwrap(), sample);
	}
	#[test]
	fn process_info_wire_is_stable() {
		let sample = ProcessInfo { koid: 7, name: String::from("x") };
		let bytes = sample.encode_vec();
		let golden: &[u8] = &[7, 0, 0, 0, 0, 0, 0, 0, 1, 0, 120];
		assert_eq!(bytes, golden);
		assert_eq!(ProcessInfo::decode(&bytes).unwrap(), sample);
	}
	#[test]
	fn config_entry_wire_is_stable() {
		let sample = ConfigEntry { key: String::from("x"), value: String::from("x") };
		let bytes = sample.encode_vec();
		let golden: &[u8] = &[1, 0, 120, 1, 0, 120];
		assert_eq!(bytes, golden);
		assert_eq!(ConfigEntry::decode(&bytes).unwrap(), sample);
	}
	#[test]
	fn ipv4_addr_wire_is_stable() {
		let sample = Ipv4Addr { a: 7, b: 7, c: 7, d: 7 };
		let bytes = sample.encode_vec();
		let golden: &[u8] = &[7, 7, 7, 7];
		assert_eq!(bytes, golden);
		assert_eq!(Ipv4Addr::decode(&bytes).unwrap(), sample);
	}
	#[test]
	fn endpoint_wire_is_stable() {
		let sample = Endpoint { addr: Ipv4Addr { a: 7, b: 7, c: 7, d: 7 }, port: 7 };
		let bytes = sample.encode_vec();
		let golden: &[u8] = &[7, 7, 7, 7, 7, 0];
		assert_eq!(bytes, golden);
		assert_eq!(Endpoint::decode(&bytes).unwrap(), sample);
	}
	#[test]
	fn neighbor_wire_is_stable() {
		let sample = Neighbor { addr: Ipv4Addr { a: 7, b: 7, c: 7, d: 7 }, mac: alloc::vec![7] };
		let bytes = sample.encode_vec();
		let golden: &[u8] = &[7, 7, 7, 7, 1, 0, 7];
		assert_eq!(bytes, golden);
		assert_eq!(Neighbor::decode(&bytes).unwrap(), sample);
	}
	#[test]
	fn net_info_wire_is_stable() {
		let sample = NetInfo { addr: Ipv4Addr { a: 7, b: 7, c: 7, d: 7 }, mac: alloc::vec![7], gateway: Ipv4Addr { a: 7, b: 7, c: 7, d: 7 }, neighbors: alloc::vec![Neighbor { addr: Ipv4Addr { a: 7, b: 7, c: 7, d: 7 }, mac: alloc::vec![7] }] };
		let bytes = sample.encode_vec();
		let golden: &[u8] = &[7, 7, 7, 7, 1, 0, 7, 7, 7, 7, 7, 1, 0, 7, 7, 7, 7, 1, 0, 7];
		assert_eq!(bytes, golden);
		assert_eq!(NetInfo::decode(&bytes).unwrap(), sample);
	}
	#[test]
	fn ping_status_wire_is_stable() {
		let sample = PingStatus::Reply;
		let bytes = sample.encode_vec();
		let golden: &[u8] = &[0];
		assert_eq!(bytes, golden);
		assert_eq!(PingStatus::decode(&bytes).unwrap(), sample);
	}
	#[test]
	fn tcp_request_wire_is_stable() {
		let sample = TcpRequest { ep: Endpoint { addr: Ipv4Addr { a: 7, b: 7, c: 7, d: 7 }, port: 7 }, request: alloc::vec![7] };
		let bytes = sample.encode_vec();
		let golden: &[u8] = &[7, 7, 7, 7, 7, 0, 1, 0, 7];
		assert_eq!(bytes, golden);
		assert_eq!(TcpRequest::decode(&bytes).unwrap(), sample);
	}
	#[test]
	fn sock_state_wire_is_stable() {
		let sample = SockState::Closed;
		let bytes = sample.encode_vec();
		let golden: &[u8] = &[0];
		assert_eq!(bytes, golden);
		assert_eq!(SockState::decode(&bytes).unwrap(), sample);
	}
	#[test]
	fn sock_info_wire_is_stable() {
		let sample = SockInfo { local_port: 7, remote: Endpoint { addr: Ipv4Addr { a: 7, b: 7, c: 7, d: 7 }, port: 7 }, state: SockState::Closed };
		let bytes = sample.encode_vec();
		let golden: &[u8] = &[7, 0, 7, 7, 7, 7, 7, 0, 0];
		assert_eq!(bytes, golden);
		assert_eq!(SockInfo::decode(&bytes).unwrap(), sample);
	}
	#[test]
	fn chunk_wire_is_stable() {
		let sample = Chunk { data: alloc::vec![7] };
		let bytes = sample.encode_vec();
		let golden: &[u8] = &[1, 0, 7];
		assert_eq!(bytes, golden);
		assert_eq!(Chunk::decode(&bytes).unwrap(), sample);
	}
	#[test]
	fn timestamp_wire_is_stable() {
		let sample = Timestamp { unix_secs: 7 };
		let bytes = sample.encode_vec();
		let golden: &[u8] = &[7, 0, 0, 0, 0, 0, 0, 0];
		assert_eq!(bytes, golden);
		assert_eq!(Timestamp::decode(&bytes).unwrap(), sample);
	}
}
