//! Golden and round-trip tests for the generated `system` bindings.
//!
//! The golden test pins the `entry` encoding to the existing `abi::log` wire
//! layout, byte for byte, so the generated codec stays a drop-in replacement.
//!
//! WHICH SIDE OWNS THE FORMAT: `abi::log` does, and `liber:log@1` mirrors it. The duplication is
//! kept deliberately rather than left undecided. Generating `abi::log` from the IDL would put the
//! code generator into the kernel's build path, and `abi` is the crate whose whole point is being
//! small and dependency-free - it is what the kernel and every userspace binary agree on before any
//! generated code exists. Deleting the IDL side is not open either: the bindings userspace uses are
//! generated from it.
//!
//! So the agreement is held by a test, and the test now compares against the OWNER rather than
//! against a third hand-typed copy of the same bytes. That is the difference between a golden test
//! and two independently maintained answers that happen to match.

use crate::codec::{Sink, VecWriter};
use crate::system::*;
use alloc::string::String;
use alloc::vec::Vec;

#[test]
fn entry_matches_abi_log_layout() {
	let e = Entry { timestamp: 42, severity: Severity::Info, source: String::from("kernel"), fields: Vec::new() };
	let mut buf = [0u8; 64];
	let n = e.encode(&mut buf).expect("encode");
	// AGAINST THE OWNER. `abi::log` defines this wire format and the IDL mirrors it; encoding the
	// same record with both and comparing is what makes "byte for byte" a checked claim rather than
	// a comment. The literal below stays as well: it is what says the format itself did not move,
	// which two encoders agreeing with each other cannot.
	let mut owner = [0u8; 64];
	let owned = abi::log::encode(42, abi::log::Severity::Info, b"kernel", &[], &mut owner).expect("the owning encoder");
	assert_eq!(&buf[..n], &owner[..owned], "the generated codec and `abi::log` disagree about the record they both claim to write");
	let expected: &[u8] = &[
		0x2a,
		0,
		0,
		0,
		0,
		0,
		0,
		0,    // timestamp = 42
		0x02, // severity = info
		0x06,
		0x00, // source length = 6
		b'k',
		b'e',
		b'r',
		b'n',
		b'e',
		b'l', // "kernel"
		0x00,
		0x00, // field count = 0
	];
	assert_eq!(&buf[..n], expected);
}

#[test]
fn the_two_encoders_agree_about_a_record_with_fields_in_it() {
	// THE COMPARISON ABOVE COVERS THE HALF THE TWO ENCODERS CANNOT DISAGREE ABOUT. Encoding the
	// same record with `abi::log` and with the generated codec was the right fix, and the record it
	// uses has `fields` empty - so field count, key and value lengths, field order, duplicate keys
	// and multi-byte UTF-8 are all outside what it compares. Each side has its own field round
	// trip, and a round trip proves an encoder agrees with its own DECODER, not that two encoders
	// agree with each OTHER.
	//
	// One record closes it, chosen for what it exercises rather than for being realistic:
	//
	//   - a non-ASCII source, so the length prefix is BYTES and not characters on both sides;
	//   - two fields, so the count and the order are visible;
	//   - both fields sharing a key, which the wire format permits and a map-shaped encoder would
	//     silently collapse to one;
	//   - an empty value, which is a zero-length prefix rather than an absent field.
	let source = "jádro";
	let fields = alloc::vec![Field { key: String::from("k"), value: String::from("první") }, Field { key: String::from("k"), value: String::new() }];
	let entry = Entry { timestamp: 0x0102_0304_0506_0708, severity: Severity::Error, source: String::from(source), fields };
	let mut generated = [0u8; 256];
	let n = entry.encode(&mut generated).expect("the generated codec encodes it");

	let owned_fields: [(&[u8], &[u8]); 2] = [(b"k", "první".as_bytes()), (b"k", b"")];
	let mut owner = [0u8; 256];
	let owned = abi::log::encode(0x0102_0304_0506_0708, abi::log::Severity::Error, source.as_bytes(), &owned_fields, &mut owner).expect("the owning encoder encodes it");
	assert_eq!(&generated[..n], &owner[..owned], "the generated codec and `abi::log` disagree about a record with fields in it");

	// AND THE OWNER'S PARSER READS WHAT THE GENERATED ENCODER WROTE, which is the direction the
	// byte comparison alone does not establish: two encoders agreeing is not the same as either
	// side's decoder accepting the other's output.
	let parsed = abi::log::LogRecord::parse(&generated[..n]).expect("the owning parser reads the generated bytes");
	assert_eq!(parsed.ts(), 0x0102_0304_0506_0708);
	assert_eq!(parsed.source(), source.as_bytes(), "the source is compared as bytes, so a multi-byte character is not a character count");
	assert_eq!(parsed.field_count(), 2, "both fields survive, including the second with the duplicate key");
	let read: Vec<(Vec<u8>, Vec<u8>)> = parsed.fields().map(|(key, value)| (key.to_vec(), value.to_vec())).collect();
	assert_eq!(read, alloc::vec![(b"k".to_vec(), "první".as_bytes().to_vec()), (b"k".to_vec(), Vec::new())], "in order, with the empty value kept as an empty value");

	// And the generated decoder reads the OWNER's bytes, so neither side is only ever reading
	// itself.
	assert_eq!(Entry::decode(&owner[..owned]), Some(entry), "the generated decoder reads what `abi::log` wrote");
}

#[test]
fn entry_round_trips() {
	let e = Entry { timestamp: 7, severity: Severity::Warn, source: String::from("svc"), fields: alloc::vec![Field { key: String::from("k"), value: String::from("v") }] };
	let mut buf = [0u8; 128];
	let n = e.encode(&mut buf).unwrap();
	assert_eq!(Entry::decode(&buf[..n]).unwrap(), e);
}

#[test]
fn manifest_round_trips_with_requested_and_grants() {
	// The requested set (what the component - later its package - declares it
	// wants) travels separately from the granted set (the manager's audited
	// intersection), so a withheld capability stays visible in the record.
	let m = Manifest { component: String::from("probe"), requested: alloc::vec![Capability::Storage, Capability::Log, Capability::Network], grants: alloc::vec![Capability::Storage, Capability::Log] };
	let mut buf = [0u8; 128];
	let n = m.encode(&mut buf).unwrap();
	assert_eq!(Manifest::decode(&buf[..n]).unwrap(), m);
}

#[test]
fn query_options_round_trip() {
	let q = Query { since: Some(100), min_severity: Some(Severity::Error), source: None, boot: None, limit: 50 };
	let mut buf = [0u8; 128];
	let n = q.encode(&mut buf).unwrap();
	assert_eq!(Query::decode(&buf[..n]).unwrap(), q);
}

#[test]
fn a_malformed_option_or_result_tag_does_not_decode() {
	// THE GENERATOR'S TAG, THROUGH A REAL GENERATED CODEC. `Reader::boolean` was made strict after a
	// finding about exactly this - one encoding per value - and the generator kept comparing bytes:
	// `if r.u8()? != 0` for `option`, the same for `result`, and a third copy in the reply path. So
	// `0xff` decoded as `Some`, and in a result it decoded as `Ok`, which turns an error into a
	// success carrying whatever the error's bytes happened to be.
	//
	// The generator's own test asserts it emits `r.tag()?`; this asserts what that produces.
	let q = Query { since: Some(100), min_severity: None, source: None, boot: None, limit: 50 };
	let mut buf = [0u8; 128];
	let n = q.encode(&mut buf).unwrap();
	assert!(Query::decode(&buf[..n]).is_some(), "the well-formed message decodes");

	// The first byte is `since`'s presence tag, written as 1. Every other non-zero spelling of
	// "present" must be refused rather than accepted as another way of saying the same thing.
	assert_eq!(buf[0], 1, "the encoder writes the canonical present tag");
	for byte in 2..=255u8 {
		buf[0] = byte;
		assert!(Query::decode(&buf[..n]).is_none(), "{byte} is not a presence tag");
	}
	// And zero is a real value: absent, with no payload following it - which is a DIFFERENT message
	// length, so this one is expected not to decode either. The point of the sweep above is that
	// nothing between 2 and 255 is quietly folded into 1.
	buf[0] = 1;
	assert!(Query::decode(&buf[..n]).is_some(), "the canonical tag still decodes after the sweep");
}

#[test]
fn error_round_trips() {
	for e in [Error::Denied, Error::NotFound, Error::Invalid, Error::Again, Error::Closed] {
		let mut buf = [0u8; 4];
		let n = e.encode(&mut buf).unwrap();
		assert_eq!(Error::decode(&buf[..n]).unwrap(), e);
	}
}

#[test]
fn severity_ordinals_match_abi_log() {
	// Against `abi::log::Severity` itself, for the same reason: the IDL's comment says the ordinal
	// "matches abi::log::Severity byte for byte", and a test that repeats the numbers checks the
	// comment against itself.
	for (generated, owned) in [
		(Severity::Trace, abi::log::Severity::Trace),
		(Severity::Debug, abi::log::Severity::Debug),
		(Severity::Info, abi::log::Severity::Info),
		(Severity::Warn, abi::log::Severity::Warn),
		(Severity::Error, abi::log::Severity::Error),
		(Severity::Fatal, abi::log::Severity::Fatal),
	] {
		assert_eq!(generated as u8, owned as u8, "a severity ordinal moved apart from the one `abi::log` defines");
	}
	assert_eq!(Severity::Trace as u8, 0);
	assert_eq!(Severity::Fatal as u8, 5);
}

#[test]
fn opcodes_are_stable() {
	assert_eq!(log::OP_EMIT, 1);
	assert_eq!(log::OP_QUERY, 2);
	assert_eq!(log::OP_TAIL, 3);
}

#[test]
fn encode_rejects_small_buffer() {
	let e = Entry { timestamp: 1, severity: Severity::Trace, source: String::from("x"), fields: Vec::new() };
	let mut buf = [0u8; 4];
	assert_eq!(e.encode(&mut buf), None);
}

#[test]
fn codec_bounds_handle_writes_and_reads_them_in_order() {
	// A message used to carry exactly one capability, and this test asserted the second write
	// was refused. It now carries up to MAX_HANDLES, because a pipeline stage needs its stdin
	// and its stdout together. What is still refused - and what matters - is going PAST the
	// bound: dropping one silently would wire a stage to nothing.
	let mut writer = VecWriter::new();
	for (index, handle) in [11u64, 22, 33, 44].iter().enumerate() {
		assert_eq!(writer.set_handle(*handle), Some(()), "handle {index} fits within the bound");
	}
	assert_eq!(writer.set_handle(55), None, "one past the bound is refused, not dropped");
	assert_eq!(writer.handles(), &[11, 22, 33, 44]);
	assert_eq!(writer.handle(), 11, "the single-handle accessor still reads the first");

	// Order is the contract: they come back exactly as they were encoded, so a decoder cannot
	// swap a stage's stdin for its stdout by reading them in a different order.
	let mut reader = crate::codec::Reader::with_handles(&[], &crate::codec::Handles::try_from_slice(&[33, 44]).expect("two handles are within the bound"));
	assert_eq!(reader.take_handle(), Some(33));
	assert_eq!(reader.take_handle(), Some(44));
	assert_eq!(reader.take_handle(), None);

	let mut zero = crate::codec::Reader::with_handle(&[], 0);
	assert!(zero.has_handle(), "occupancy is explicit, not inferred from handle != 0");
	assert_eq!(zero.take_handle(), Some(0));
}

#[test]
fn malformed_dispatch_leaves_the_request_handle_with_the_host() {
	let mut service = MemLog::default();
	let mut request_handles = crate::codec::Handles::try_from_slice(&[77]).expect("one handle is within the bound");
	let mut reply_handles = crate::codec::Handles::new();
	let mut out = [0u8; 32];
	assert_eq!(log::dispatch(&mut service, &[1], &mut request_handles, &mut out, &mut reply_handles), None);
	assert_eq!(request_handles.as_slice(), &[77], "a refused dispatch leaves the capability with the host to close");
	assert!(reply_handles.is_empty());
}

#[test]
fn a_request_with_trailing_bytes_is_not_the_same_request() {
	// `Reader::finish` checks BOTH halves - every byte consumed and every capability taken - and it
	// was called at the codec boundary (`decode`) and at none of the FRAMING boundaries. Generated
	// dispatch read the opcode, the correlation id and the arguments and then asked only
	// `if r.has_handle()`, so `[OP][corr][args]` and `[OP][corr][args][DE AD BE EF]` were the same
	// request: a message its writer and its reader disagree about, accepted.
	//
	// That is the trailing-garbage finding closed for a standalone value and open for every message
	// this system actually sends.
	let entry = Entry { timestamp: 1, severity: Severity::Info, source: String::from("t"), fields: Vec::new() };
	let mut body = [0u8; 256];
	let mut w = crate::codec::SliceWriter::new(&mut body);
	{
		use crate::codec::Sink;
		w.u16(log::OP_EMIT).expect("opcode");
		w.u32(7).expect("correlation id");
	}
	entry.write(&mut w).expect("the entry encodes");
	let n = w.pos();

	let mut service = MemLog::default();
	let mut out = [0u8; 256];
	let well_formed = {
		let mut request_handles = crate::codec::Handles::new();
		let mut reply_handles = crate::codec::Handles::new();
		log::dispatch(&mut service, &body[..n], &mut request_handles, &mut out, &mut reply_handles)
	};
	assert!(well_formed.is_some(), "the well-formed request dispatches");

	for trailing in [1usize, 4] {
		let mut request_handles = crate::codec::Handles::new();
		let mut reply_handles = crate::codec::Handles::new();
		let refused = log::dispatch(&mut service, &body[..n + trailing], &mut request_handles, &mut out, &mut reply_handles);
		assert!(refused.is_none(), "{trailing} trailing byte(s) make a different request, and it is refused");
	}
	assert_eq!(service.entries.len(), 1, "and the refused requests never reached the service");
}

#[test]
fn a_reply_with_trailing_bytes_is_not_the_same_reply() {
	// The client half of the same boundary: the reply path checked `has_handle` and not the bytes,
	// so a reply could carry anything after its value and decode as though it had not.
	let mut client = log::Client::new(TrailingLoopback { service: MemLog::default(), trailing: 0 });
	assert!(client.emit(&Entry { timestamp: 1, severity: Severity::Info, source: String::from("t"), fields: Vec::new() }).is_some(), "the ordinary reply decodes");

	let mut client = log::Client::new(TrailingLoopback { service: MemLog::default(), trailing: 3 });
	assert!(client.emit(&Entry { timestamp: 1, severity: Severity::Info, source: String::from("t"), fields: Vec::new() }).is_none(), "a reply with three bytes after its value is refused");
}

// The loopback above, with `trailing` bytes appended to every reply - a server whose framing does
// not agree with its schema, which is what the reply-side `finish` exists to catch.
struct TrailingLoopback<S: log::Service> {
	service: S,
	trailing: usize,
}

impl<S: log::Service> crate::codec::Transport for TrailingLoopback<S> {
	fn discard_handles(&mut self, _handles: &[u64]) {}

	fn call(&mut self, request: &[u8], request_handles: &[u64], reply_handles: &mut crate::codec::Handles, _deadline: u64) -> Result<Vec<u8>, crate::codec::TransportError> {
		let mut out = [0u8; 4096];
		let mut request_handles = crate::codec::Handles::try_from_slice(request_handles).expect("the fixture stays within the bound");
		let n = log::dispatch(&mut self.service, request, &mut request_handles, &mut out, reply_handles).ok_or(crate::codec::TransportError::Malformed)?;
		let mut reply = out[..n].to_vec();
		reply.extend(core::iter::repeat_n(0xdd, self.trailing));
		Ok(reply)
	}
}

// An in-memory loopback transport that dispatches a request straight into a
// Service and returns the encoded reply - the host stand-in for a channel.
struct Loopback<S: log::Service> {
	service: S,
}

impl<S: log::Service> crate::codec::Transport for Loopback<S> {
	// Nothing to release: this loopback hands back handle NUMBERS it never opened, so there is no
	// kernel object behind them. Written out rather than inherited from a default body, which is
	// what let a real transport forget it and leak - see `Transport::discard_handles`.
	fn discard_handles(&mut self, _handles: &[u64]) {}

	fn call(&mut self, request: &[u8], request_handles: &[u64], reply_handles: &mut crate::codec::Handles, _deadline: u64) -> Result<Vec<u8>, crate::codec::TransportError> {
		let mut out = [0u8; 4096];
		let mut request_handles = crate::codec::Handles::try_from_slice(request_handles).expect("the fixture stays within the bound");
		let n = log::dispatch(&mut self.service, request, &mut request_handles, &mut out, reply_handles).ok_or(crate::codec::TransportError::Malformed)?;
		assert!(request_handles.is_empty(), "the dispatch consumed every capability the request carried");
		Ok(out[..n].to_vec())
	}
}

// A trivial in-memory Log service for the round-trip test.
#[derive(Default)]
struct MemLog {
	entries: Vec<Entry>,
}

impl log::Service for MemLog {
	fn emit(&mut self, e: Entry) -> Result<(), Error> {
		self.entries.push(e);
		Ok(())
	}

	fn query(&mut self, _q: Query) -> Result<Vec<Entry>, Error> {
		Ok(self.entries.clone())
	}

	fn tail(&mut self, _q: Query) -> Vec<Entry> {
		self.entries.clone()
	}
}

#[test]
fn client_server_round_trip() {
	let mut client = log::Client::new(Loopback { service: MemLog::default() });
	let e = Entry { timestamp: 9, severity: Severity::Error, source: String::from("svc"), fields: Vec::new() };
	assert_eq!(client.emit(&e), Some(Ok(())));
	let q = Query { since: None, min_severity: None, source: None, boot: None, limit: 0 };
	assert_eq!(client.query(&q), Some(Ok(alloc::vec![e])));
}

#[test]
fn tail_stream_round_trip() {
	// Drive the generated stream helpers directly: a producer opens the stream
	// (decoding the request, calling the service), frames each item with a
	// sequence number, and a consumer reads the frames back.
	let mut service = MemLog::default();
	let e0 = Entry { timestamp: 1, severity: Severity::Info, source: String::from("a"), fields: Vec::new() };
	let e1 = Entry { timestamp: 2, severity: Severity::Warn, source: String::from("b"), fields: Vec::new() };
	service.entries = alloc::vec![e0.clone(), e1.clone()];

	// Encode a tail request the way the client does (op + corr + query).
	let q = Query { since: None, min_severity: None, source: None, boot: None, limit: 0 };
	let mut writer = VecWriter::new();
	let w = &mut writer;
	w.u16(log::OP_TAIL).unwrap();
	w.u32(7).unwrap();
	q.write(w).unwrap();
	let request = writer.into_inner().unwrap();

	let mut request_handles = crate::codec::Handles::new();
	let (corr, items) = log::tail_open(&mut service, &request, &mut request_handles).unwrap();
	assert_eq!(corr, 7);
	assert_eq!(items.len(), 2);

	let mut frame = [0u8; 256];
	for (seq, item) in items.iter().enumerate() {
		// The frame carries a bounded LIST of capabilities, like every other message on this wire -
		// it carried exactly one until 2026-08-13, which is why a two-capability element would have
		// had its second dropped by the encoder.
		let mut frame_handles = crate::codec::Handles::new();
		let n = log::tail_frame(seq as u32, item, &mut frame, &mut frame_handles).unwrap();
		assert_eq!(log::tail_read(&frame[..n], &mut frame_handles), Some(item.clone()));
		assert!(frame_handles.is_empty(), "an entry carries no capabilities, so the frame carries none");
	}
}

// A volume stub whose `open` returns a non-zero handle value. The wire encodes
// only a u32 placeholder for the handle, so if the client recovers this value it
// must have travelled out-of-band (set_handle -> reply_handle -> take_handle).
struct VolStub;

impl volume::Service for VolStub {
	fn open(&mut self, o: OpenOpts) -> Result<OpenResult, Error> {
		if o.path.is_empty() { Err(Error::NotFound) } else { Ok(OpenResult { file: 0xCAFE, size: 42 }) }
	}

	fn list(&mut self, path: String) -> Result<Vec<FileInfo>, Error> {
		// The error arm the schema gained in 2026-08-12: a directory that is not there is a
		// refusal, not an empty listing. An empty PATH is the volume root, which is legitimately
		// empty here - the two answers are different and the stub can now say so.
		if path == "missing" { Err(Error::NotFound) } else { Ok(Vec::new()) }
	}

	fn write_stream(&mut self, path: String, data: u64) -> Result<(), Error> {
		// the data channel handle must have travelled out-of-band, like `write`'s
		// buffer handle.
		if path.is_empty() || data != 0xBEEF { Err(Error::Invalid) } else { Ok(()) }
	}

	fn write(&mut self, path: String, data: crate::codec::Buffer) -> Result<(), Error> {
		// the buffer handle must have travelled out-of-band (set_handle -> request_handle
		// -> take_handle); prove it by succeeding only when it arrives intact.
		if path.is_empty() || data.handle != 0xBEEF || data.len != 5 { Err(Error::Invalid) } else { Ok(()) }
	}

	fn remove(&mut self, path: String) -> Result<(), Error> {
		if path.is_empty() { Err(Error::NotFound) } else { Ok(()) }
	}

	// The seven path ops. Each answers from its arguments alone, because what this stub proves
	// is the CODEC: that the values a client sent arrive as themselves, and that a handle travelled
	// out-of-band rather than through the byte stream.
	fn stat(&mut self, path: String) -> Result<FileInfo, Error> {
		if path.is_empty() { Err(Error::NotFound) } else { Ok(FileInfo { name: String::from("stat"), size: 11, r#type: FileType::File, mtime: 3, ctime: 4 }) }
	}

	fn rename(&mut self, from: String, to: String) -> Result<(), Error> {
		if from.is_empty() || to.is_empty() || from == to { Err(Error::Invalid) } else { Ok(()) }
	}

	fn truncate(&mut self, path: String, length: u64) -> Result<(), Error> {
		if path.is_empty() || length > 1024 { Err(Error::Invalid) } else { Ok(()) }
	}

	fn touch(&mut self, path: String, create: bool, at: u64) -> Result<(), Error> {
		if path.is_empty() || (!create && at == 0) { Err(Error::NotFound) } else { Ok(()) }
	}

	fn read(&mut self, path: String, offset: u64, length: u32) -> Result<crate::codec::Buffer, Error> {
		// The window's length is echoed back as the buffer's, so a client that decodes a different
		// number is decoding the wrong field; the handle proves the out-of-band path.
		if path.is_empty() { Err(Error::NotFound) } else { Ok(crate::codec::Buffer { handle: 0xCAFE, len: offset + length as u64 }) }
	}

	fn watch(&mut self, path: String) -> Result<Vec<FileEvent>, Error> {
		if path.is_empty() { Err(Error::NotFound) } else { Ok(alloc::vec![FileEvent { path, kind: FileEventKind::Modified, size: 9 }]) }
	}

	fn open_writer(&mut self, path: String, mode: WriterMode) -> Result<u64, Error> {
		// The mode is a value the caller chose, and answering with a different handle for each is
		// what proves it survived the wire.
		match (path.is_empty(), mode) {
			(true, _) => Err(Error::NotFound),
			(false, WriterMode::Replace) => Ok(0x0BAD_0001),
			(false, WriterMode::Append) => Ok(0x0BAD_0002),
		}
	}

	// A fixed handle, because what this stub is asked to prove is that a `handle<channel>` return
	// survives the wire - not that anything is on the other end of it.
	fn connect(&mut self) -> Result<u64, Error> {
		Ok(0x0BAD_0003)
	}

	fn snap_create(&mut self, name: String) -> Result<(), Error> {
		if name.is_empty() { Err(Error::Invalid) } else { Ok(()) }
	}

	fn snap_list(&mut self) -> Result<Vec<SnapshotInfo>, Error> {
		Ok(alloc::vec![SnapshotInfo { name: String::from("backup"), generation: 7 }])
	}

	fn snap_delete(&mut self, name: String) -> Result<(), Error> {
		if name.is_empty() { Err(Error::NotFound) } else { Ok(()) }
	}

	fn snap_open(&mut self, snapshot: String, path: String) -> Result<OpenResult, Error> {
		// the file handle must travel out-of-band, exactly like `open`.
		if snapshot.is_empty() || path.is_empty() { Err(Error::NotFound) } else { Ok(OpenResult { file: 0xCAFE, size: 42 }) }
	}

	fn mkdir(&mut self, path: String) -> Result<(), Error> {
		if path.is_empty() { Err(Error::Invalid) } else { Ok(()) }
	}

	fn rmdir(&mut self, path: String) -> Result<(), Error> {
		if path.is_empty() { Err(Error::NotFound) } else { Ok(()) }
	}

	fn capacity(&mut self) -> Result<u64, Error> {
		Ok(0x100000)
	}

	fn status(&mut self) -> Result<VolumeStatus, Error> {
		Ok(VolumeStatus { label: String::from("system"), total_bytes: 0x100000, free_bytes: 0x80000, compression: false, read_only: false, filesystem: String::from("liberfs") })
	}

	fn set_compression(&mut self, _enabled: bool) -> Result<(), Error> {
		Ok(())
	}

	fn fsck(&mut self) -> Result<FsckReport, Error> {
		Ok(FsckReport { checksum_failures: 1, damaged: alloc::vec![String::from("docs/broken.txt")], structural_failures: 2, stream_failures: 3, io_failures: 4, faults: alloc::vec![String::from("a leaf outside the range that routes to it")] })
	}

	fn restore(&mut self, path: String, _snapshot: String) -> Result<(), Error> {
		if path.is_empty() { Err(Error::NotFound) } else { Ok(()) }
	}
}

struct VolLoopback<S: volume::Service> {
	service: S,
}

impl<S: volume::Service> crate::codec::Transport for VolLoopback<S> {
	// Nothing to release: this loopback hands back handle NUMBERS it never opened, so there is no
	// kernel object behind them. Written out rather than inherited from a default body, which is
	// what let a real transport forget it and leak - see `Transport::discard_handles`.
	fn discard_handles(&mut self, _handles: &[u64]) {}

	fn call(&mut self, request: &[u8], request_handles: &[u64], reply_handles: &mut crate::codec::Handles, _deadline: u64) -> Result<Vec<u8>, crate::codec::TransportError> {
		let mut out = [0u8; 256];
		let mut request_handles = crate::codec::Handles::try_from_slice(request_handles).expect("the fixture stays within the bound");
		let n = volume::dispatch(&mut self.service, request, &mut request_handles, &mut out, reply_handles).ok_or(crate::codec::TransportError::Malformed)?;
		assert!(request_handles.is_empty(), "the dispatch consumed every capability the request carried");
		Ok(out[..n].to_vec())
	}
}

#[test]
fn handle_return_crosses_out_of_band() {
	let mut client = volume::Client::new(VolLoopback { service: VolStub });
	let opts = OpenOpts { path: String::from("/x"), write: false, create: false };
	// the file handle (0xCAFE) crosses out-of-band; the size travels in the byte stream.
	assert_eq!(client.open(&opts), Some(Ok(OpenResult { file: 0xCAFE, size: 42 })));
	let empty = OpenOpts { path: String::new(), write: false, create: false };
	assert_eq!(client.open(&empty), Some(Err(Error::NotFound)));
}

#[test]
fn write_buffer_handle_crosses_out_of_band() {
	let mut client = volume::Client::new(VolLoopback { service: VolStub });
	let data = crate::codec::Buffer { handle: 0xBEEF, len: 5 };
	// the buffer handle (0xBEEF) crosses out-of-band; the length travels in-stream.
	assert_eq!(client.write("/x", &data), Some(Ok(())));
	// a missing path is rejected.
	assert_eq!(client.write("", &data), Some(Err(Error::Invalid)));
}

#[test]
fn remove_round_trips() {
	let mut client = volume::Client::new(VolLoopback { service: VolStub });
	assert_eq!(client.remove("/x"), Some(Ok(())));
	assert_eq!(client.remove(""), Some(Err(Error::NotFound)));
}

#[test]
fn oversized_reply_degrades_to_a_typed_error() {
	// A reply that outgrows the caller's buffer must not vanish (the client would
	// block forever waiting for it): the dispatch overflow fallback rewrites it as
	// a typed `again` error, which always fits. snap_list's Ok reply (a one-entry
	// snapshot list) needs more than the 6 bytes offered here; the fallback -
	// [corr u32][err tag][again] - is exactly 6.
	let mut request = Vec::new();
	request.extend_from_slice(&volume::OP_SNAP_LIST.to_le_bytes());
	request.extend_from_slice(&7u32.to_le_bytes()); // correlation id
	let mut out = [0u8; 6];
	let mut request_handles = crate::codec::Handles::new();
	let mut reply_handles = crate::codec::Handles::new();
	let n = volume::dispatch(&mut VolStub, &request, &mut request_handles, &mut out, &mut reply_handles).expect("the fallback reply should be produced");
	assert_eq!(&out[..4], &7u32.to_le_bytes(), "the fallback keeps the correlation id");
	assert_eq!(out[4], 0, "the fallback is the error arm");
	assert_eq!(Error::decode(&out[5..n]), Some(Error::Again), "the fallback error is `again`");
	// with room to spare the same call succeeds normally.
	let mut big = [0u8; 256];
	let n = volume::dispatch(&mut VolStub, &request, &mut request_handles, &mut big, &mut reply_handles).expect("the real reply fits");
	assert_eq!(big[4], 1, "the roomy reply is the ok arm");
	assert!(n > 6, "the ok reply carries the snapshot list");
}

#[test]
fn partial_reply_encode_returns_the_unsent_handle_to_the_host() {
	let opts = OpenOpts { path: String::from("/x"), write: false, create: false };
	let mut request = VecWriter::new();
	request.u16(volume::OP_OPEN).unwrap();
	request.u32(9).unwrap();
	opts.write(&mut request).unwrap();
	let request = request.into_inner().unwrap();
	let mut request_handles = crate::codec::Handles::new();
	let mut reply_handles = crate::codec::Handles::new();
	let mut out = [0u8; 9]; // corr + ok tag + handle placeholder fits; size does not
	assert_eq!(volume::dispatch(&mut VolStub, &request, &mut request_handles, &mut out, &mut reply_handles), None);
	assert_eq!(reply_handles.first(), 0xCAFE);
}

struct UnexpectedHandleTransport {
	discarded: u64,
}

// THE THREE FAILURES A CLIENT HAS TO TELL APART. `call` returned `Option`, so a refused send (the
// request never left - retrying is safe), a departed peer (retrying on this channel cannot work) and
// a deadline (the request may already have been acted on, so retrying is safe only if the operation
// is idempotent) were one `None`, and every caller had to guess. The generated client keeps its
// `Option`-returning methods - hundreds of call sites depend on them - and records the reason, which
// is the smallest shape that lets a caller decide.
struct FailingTransport {
	error: crate::codec::TransportError,
}

impl crate::codec::Transport for FailingTransport {
	fn call(&mut self, _request: &[u8], _request_handles: &[u64], _reply_handles: &mut crate::codec::Handles, _deadline: u64) -> Result<Vec<u8>, crate::codec::TransportError> {
		Err(self.error)
	}

	fn discard_handles(&mut self, _handles: &[u64]) {}
}

#[test]
fn a_failed_call_says_why_so_a_caller_can_decide_whether_to_retry() {
	use crate::codec::TransportError;
	for error in [TransportError::SendRefused, TransportError::PeerClosed, TransportError::TimedOut, TransportError::NoRoute] {
		let mut client = log::Client::new(FailingTransport { error });
		// The method still answers `None`: no existing caller changes.
		assert!(client.protocol_info().is_none(), "a failed transport still reports no reply");
		// And the reason is available to the caller that needs it.
		assert_eq!(client.last_error(), Some(error), "the transport's reason reaches the caller");
	}
}

// The deadline reaches the transport rather than being a promise the trait cannot keep: a live peer
// that accepts a request and never replies used to block the caller forever, because `call` had no
// way to be told when to give up.
#[test]
fn the_clients_deadline_is_handed_to_the_transport() {
	struct DeadlineSpy {
		seen: u64,
	}
	impl crate::codec::Transport for DeadlineSpy {
		fn call(&mut self, _request: &[u8], _request_handles: &[u64], _reply_handles: &mut crate::codec::Handles, deadline: u64) -> Result<Vec<u8>, crate::codec::TransportError> {
			self.seen = deadline;
			Err(crate::codec::TransportError::TimedOut)
		}
		fn discard_handles(&mut self, _handles: &[u64]) {}
	}

	let mut client = log::Client::with_deadline(DeadlineSpy { seen: 0 }, 4242);
	assert!(client.protocol_info().is_none());
	assert_eq!(client.into_transport().seen, 4242, "the transport was told when to give up");

	let mut client = log::Client::new(DeadlineSpy { seen: 0 });
	client.set_deadline(99);
	assert!(client.protocol_info().is_none());
	assert_eq!(client.into_transport().seen, 99);
}

impl crate::codec::Transport for UnexpectedHandleTransport {
	fn call(&mut self, request: &[u8], _request_handles: &[u64], reply_handles: &mut crate::codec::Handles, _deadline: u64) -> Result<Vec<u8>, crate::codec::TransportError> {
		let corr = u32::from_le_bytes(request[2..6].try_into().map_err(|_| crate::codec::TransportError::Malformed)?);
		let mut reply = corr.to_le_bytes().to_vec();
		reply.extend_from_slice(&[1, 0]); // Ok(()) for log.emit
		{
			*reply_handles = crate::codec::Handles::try_from_slice(&[0xBAD]).expect("one handle is within the bound");
			Ok(reply)
		}
	}

	fn discard_handles(&mut self, handles: &[u64]) {
		self.discarded = handles.first().copied().unwrap_or(0);
	}
}

#[test]
fn client_discards_an_unexpected_reply_handle() {
	let transport = UnexpectedHandleTransport { discarded: 0 };
	let mut client = log::Client::new(transport);
	let entry = Entry { timestamp: 1, severity: Severity::Info, source: String::new(), fields: Vec::new() };
	assert_eq!(client.emit(&entry), None);
	assert_eq!(client.into_transport().discarded, 0xBAD);
}

#[test]
fn mkdir_rmdir_round_trip() {
	let mut client = volume::Client::new(VolLoopback { service: VolStub });
	assert_eq!(client.mkdir("/d"), Some(Ok(())));
	assert_eq!(client.mkdir(""), Some(Err(Error::Invalid)));
	assert_eq!(client.rmdir("/d"), Some(Ok(())));
	assert_eq!(client.rmdir(""), Some(Err(Error::NotFound)));
}

#[test]
fn snapshot_ops_round_trip() {
	let mut client = volume::Client::new(VolLoopback { service: VolStub });
	// create / delete return unit results.
	assert_eq!(client.snap_create("backup"), Some(Ok(())));
	assert_eq!(client.snap_create(""), Some(Err(Error::Invalid)));
	assert_eq!(client.snap_delete("backup"), Some(Ok(())));
	assert_eq!(client.snap_delete(""), Some(Err(Error::NotFound)));
	// list carries the snapshot records in-stream.
	assert_eq!(client.snap_list(), Some(Ok(alloc::vec![SnapshotInfo { name: String::from("backup"), generation: 7 }])));
	// snap-open returns the file handle out-of-band, just like open.
	assert_eq!(client.snap_open("backup", "/x"), Some(Ok(OpenResult { file: 0xCAFE, size: 42 })));
	assert_eq!(client.snap_open("backup", ""), Some(Err(Error::NotFound)));
}

#[test]
fn entry_renders_json() {
	let e = Entry { timestamp: 42, severity: Severity::Info, source: String::from("kernel"), fields: Vec::new() };
	assert_eq!(e.to_json(), "{\"timestamp\":42,\"severity\":\"info\",\"source\":\"kernel\",\"fields\":[]}");
}

#[test]
fn entry_renders_json_with_fields() {
	let e = Entry { timestamp: 1, severity: Severity::Warn, source: String::from("s"), fields: alloc::vec![Field { key: String::from("k"), value: String::from("v") }] };
	assert_eq!(e.to_json(), "{\"timestamp\":1,\"severity\":\"warn\",\"source\":\"s\",\"fields\":[{\"key\":\"k\",\"value\":\"v\"}]}");
}

#[test]
fn query_renders_json_with_options_and_kebab_keys() {
	let q = Query { since: Some(5), min_severity: None, source: Some(String::from("svc")), boot: None, limit: 9 };
	assert_eq!(q.to_json(), "{\"since\":5,\"min-severity\":null,\"source\":\"svc\",\"boot\":null,\"limit\":9}");
}

#[test]
fn json_pretty_indents_a_minified_document() {
	let min = "{\"name\":\"a b\",\"n\":-3,\"ok\":true,\"none\":null,\"list\":[1,2],\"empty\":{},\"sub\":{\"k\":\"v\"}}";
	let want = "{\n  \"name\": \"a b\",\n  \"n\": -3,\n  \"ok\": true,\n  \"none\": null,\n  \"list\": [\n    1,\n    2\n  ],\n  \"empty\": {},\n  \"sub\": {\n    \"k\": \"v\"\n  }\n}";
	assert_eq!(crate::codec::json_pretty(min, false), want);
}

#[test]
fn json_pretty_keeps_escapes_and_embedded_brackets_intact() {
	// brackets, commas and colons inside string literals must not indent, and an
	// escaped quote must not end the string.
	let min = "{\"path\":\"a{b}[c],:d\",\"quote\":\"x\\\"y\"}";
	let want = "{\n  \"path\": \"a{b}[c],:d\",\n  \"quote\": \"x\\\"y\"\n}";
	assert_eq!(crate::codec::json_pretty(min, false), want);
}

#[test]
fn json_pretty_colors_keys_strings_numbers_and_literals() {
	let out = crate::codec::json_pretty("{\"k\":\"v\",\"n\":7,\"b\":false}", true);
	assert!(out.contains("\x1b[36m\"k\"\x1b[0m: \x1b[32m\"v\"\x1b[0m"));
	assert!(out.contains("\x1b[33m7\x1b[0m"));
	assert!(out.contains("\x1b[35mfalse\x1b[0m"));
}

#[test]
fn error_renders_json_kebab() {
	assert_eq!(Error::NotFound.to_json(), "\"not-found\"");
}

#[test]
fn entry_renders_text() {
	let e = Entry { timestamp: 42, severity: Severity::Info, source: String::from("kernel"), fields: Vec::new() };
	assert_eq!(e.to_text(), "{timestamp=42, severity=info, source=kernel, fields=[]}");
}

#[test]
fn entry_renders_text_with_fields() {
	let e = Entry { timestamp: 1, severity: Severity::Warn, source: String::from("s"), fields: alloc::vec![Field { key: String::from("k"), value: String::from("v") }] };
	assert_eq!(e.to_text(), "{timestamp=1, severity=warn, source=s, fields=[{key=k, value=v}]}");
}

#[test]
fn query_renders_text_with_option_none() {
	let q = Query { since: Some(5), min_severity: None, source: Some(String::from("svc")), boot: None, limit: 9 };
	assert_eq!(q.to_text(), "{since=5, min-severity=-, source=svc, boot=-, limit=9}");
}

// CBOR primitive heads use the canonical shortest argument encoding (RFC 8949):
// inline for n < 24, then 1/2/4/8 big-endian bytes.
#[test]
fn cbor_uint_uses_shortest_head() {
	use crate::codec::cbor;
	let mut v = Vec::new();
	cbor::uint(&mut v, 23);
	assert_eq!(v, [0x17]);
	v.clear();
	cbor::uint(&mut v, 24);
	assert_eq!(v, [0x18, 24]);
	v.clear();
	cbor::uint(&mut v, 255);
	assert_eq!(v, [0x18, 255]);
	v.clear();
	cbor::uint(&mut v, 256);
	assert_eq!(v, [0x19, 0x01, 0x00]);
	v.clear();
	cbor::uint(&mut v, 65535);
	assert_eq!(v, [0x19, 0xff, 0xff]);
	v.clear();
	cbor::uint(&mut v, 65536);
	assert_eq!(v, [0x1a, 0x00, 0x01, 0x00, 0x00]);
}

// Negative integers are major type 1 over `-1 - v`.
#[test]
fn cbor_int_encodes_negatives() {
	use crate::codec::cbor;
	let mut v = Vec::new();
	cbor::int(&mut v, -1);
	assert_eq!(v, [0x20]);
	v.clear();
	cbor::int(&mut v, -24);
	assert_eq!(v, [0x37]);
	v.clear();
	cbor::int(&mut v, -25);
	assert_eq!(v, [0x38, 24]);
	v.clear();
	cbor::int(&mut v, 9);
	assert_eq!(v, [0x09]);
}

// Simple values: booleans and null map to fixed major-type-7 bytes.
#[test]
fn cbor_simple_values() {
	use crate::codec::cbor;
	let mut v = Vec::new();
	cbor::boolean(&mut v, false);
	cbor::boolean(&mut v, true);
	cbor::null(&mut v);
	assert_eq!(v, [0xf4, 0xf5, 0xf6]);
}

// An enum case renders as a CBOR text string of its kebab-case name.
#[test]
fn severity_renders_cbor() {
	assert_eq!(Severity::Info.to_cbor(), [0x64, b'i', b'n', b'f', b'o']);
}

#[test]
fn error_renders_cbor_kebab() {
	assert_eq!(Error::NotFound.to_cbor(), [0x69, b'n', b'o', b't', b'-', b'f', b'o', b'u', b'n', b'd']);
}

// A record renders as a definite-length CBOR map keyed by field name, mirroring
// the JSON object structure.
#[test]
fn field_renders_cbor_map() {
	let f = Field { key: String::from("k"), value: String::from("v") };
	assert_eq!(f.to_cbor(), [0xa2, 0x63, b'k', b'e', b'y', 0x61, b'k', 0x65, b'v', b'a', b'l', b'u', b'e', 0x61, b'v']);
}

#[test]
fn entry_renders_cbor_map() {
	let e = Entry { timestamp: 42, severity: Severity::Info, source: String::from("kernel"), fields: Vec::new() };
	let mut want = Vec::new();
	want.push(0xa4); // map(4)
	want.push(0x69);
	want.extend_from_slice(b"timestamp");
	want.extend_from_slice(&[0x18, 42]); // uint 42
	want.push(0x68);
	want.extend_from_slice(b"severity");
	want.push(0x64);
	want.extend_from_slice(b"info");
	want.push(0x66);
	want.extend_from_slice(b"source");
	want.push(0x66);
	want.extend_from_slice(b"kernel");
	want.push(0x66);
	want.extend_from_slice(b"fields");
	want.push(0x80); // array(0)
	assert_eq!(e.to_cbor(), want);
}

// Options collapse to their value or `null`, and kebab-case keys are preserved.
#[test]
fn query_renders_cbor_with_options() {
	let q = Query { since: Some(5), min_severity: None, source: Some(String::from("svc")), boot: None, limit: 9 };
	let mut want = Vec::new();
	want.push(0xa5); // map(5)
	want.push(0x65);
	want.extend_from_slice(b"since");
	want.push(0x05); // uint 5
	want.push(0x6c);
	want.extend_from_slice(b"min-severity");
	want.push(0xf6); // null
	want.push(0x66);
	want.extend_from_slice(b"source");
	want.push(0x63);
	want.extend_from_slice(b"svc");
	want.push(0x64);
	want.extend_from_slice(b"boot");
	want.push(0xf6); // null
	want.push(0x65);
	want.extend_from_slice(b"limit");
	want.push(0x09); // uint 9
	assert_eq!(q.to_cbor(), want);
}

// The System Graph round-trips through its binary wire form: a component carrying
// its kind, state, dependency edges and counters, plus a trace span, survives an
// encode/decode unchanged.
#[test]
fn graph_round_trips() {
	let g = Graph {
		components: alloc::vec![
			Component { name: String::from("log-service"), r#type: ComponentType::Service, state: ComponentState::Running, deps: Vec::new(), counters: Counters { messages_sent: 7, messages_received: 3, handles: 5, memory_bytes: 8192, restarts: 0, watchdog_trips: 0, last_failure: String::new() } },
			Component { name: String::from("device-manager"), r#type: ComponentType::Service, state: ComponentState::Stopped, deps: alloc::vec![String::from("log-service")], counters: Counters { messages_sent: 1, messages_received: 1, handles: 2, memory_bytes: 4096, restarts: 1, watchdog_trips: 1, last_failure: String::from("hung") } },
		],
		spans: alloc::vec![TraceSpan { name: String::from("device.list"), duration_ns: 1234 }],
	};
	let bytes = g.encode_vec().expect("encode");
	assert_eq!(Graph::decode(&bytes), Some(g));
}

// A component renders to a CBOR map with kebab-case keys, its kind and state as text
// enums, its deps as an array, and its counters as a nested map.
#[test]
fn component_renders_cbor_map() {
	let c = Component { name: String::from("net"), r#type: ComponentType::Driver, state: ComponentState::Failed, deps: alloc::vec![String::from("device-manager")], counters: Counters { messages_sent: 0, messages_received: 0, handles: 1, memory_bytes: 0, restarts: 2, watchdog_trips: 0, last_failure: String::new() } };
	let mut want = Vec::new();
	want.push(0xa5); // map(5)
	want.push(0x64);
	want.extend_from_slice(b"name");
	want.push(0x63);
	want.extend_from_slice(b"net");
	want.push(0x64);
	want.extend_from_slice(b"type");
	want.push(0x66);
	want.extend_from_slice(b"driver");
	want.push(0x65);
	want.extend_from_slice(b"state");
	want.push(0x66);
	want.extend_from_slice(b"failed");
	want.push(0x64);
	want.extend_from_slice(b"deps");
	want.push(0x81); // array(1)
	want.push(0x6e);
	want.extend_from_slice(b"device-manager");
	want.push(0x68);
	want.extend_from_slice(b"counters");
	want.push(0xa7); // map(7)
	want.push(0x6d);
	want.extend_from_slice(b"messages-sent");
	want.push(0x00); // uint 0
	want.push(0x71);
	want.extend_from_slice(b"messages-received");
	want.push(0x00); // uint 0
	want.push(0x67);
	want.extend_from_slice(b"handles");
	want.push(0x01); // uint 1
	want.push(0x6c);
	want.extend_from_slice(b"memory-bytes");
	want.push(0x00); // uint 0
	want.push(0x68);
	want.extend_from_slice(b"restarts");
	want.push(0x02); // uint 2
	want.push(0x6e);
	want.extend_from_slice(b"watchdog-trips");
	want.push(0x00); // uint 0
	want.push(0x6c);
	want.extend_from_slice(b"last-failure");
	want.push(0x60); // text(0)
	assert_eq!(c.to_cbor(), want);
}

#[test]
fn protocol_info_answers_with_the_package_identity() {
	// The stateless identity query: no service state is touched, the reply is the package this
	// generated dispatch belongs to, and NO typed method frame is involved. It is answered by
	// the generated code because rt's serve loops serve every interface and cannot know which
	// package a given service implements.
	let mut service = MemLog::default();
	let mut request = Vec::new();
	request.extend_from_slice(&crate::codec::PROTOCOL_INFO_OP.to_le_bytes());
	request.extend_from_slice(&99u32.to_le_bytes());
	let mut out = [0u8; 64];
	let mut request_handles = crate::codec::Handles::new();
	let mut reply_handles = crate::codec::Handles::new();
	let n = log::dispatch(&mut service, &request, &mut request_handles, &mut out, &mut reply_handles).expect("the identity query is answered");

	let mut reader = crate::codec::Reader::new(&out[..n]);
	let r = &mut reader;
	assert_eq!(r.u32(), Some(99), "the reply carries the caller's correlation id back");
	assert_eq!(r.string_lp().as_deref(), Some("liber:log"), "the package identity is the colon-joined path");
	assert_eq!(r.u32(), Some(1), "the package version travels with it");
	assert!(reply_handles.is_empty(), "an identity query transfers no capability");

	// It must not disturb the service: a query is not a method call.
	assert!(service.entries.is_empty(), "answering the query ran no service method");
}

#[test]
fn a_typed_opcode_cannot_reach_the_reserved_control_band() {
	// The two guards must agree: the validator refuses a typed `@op` above TYPED_OP_MAX, and
	// the generated dispatch answers PROTOCOL_INFO_OP before consulting the typed match. If
	// TYPED_OP_MAX ever rises to cover the control band again, an interface method could shadow
	// the identity query and this assertion is what says so.
	assert!(crate::codec::PROTOCOL_INFO_OP > crate::codec::TYPED_OP_MAX, "the identity opcode sits above every typed one");
}

#[test]
fn a_client_reads_the_identity_back_over_a_transport() {
	// End to end over the loopback: the client's query reaches the generated dispatch and the
	// identity comes back decoded. This is what proves the two halves agree on the frame -
	// the dispatch-side test alone would pass even if the client encoded it differently.
	let mut client = log::Client::new(Loopback { service: MemLog::default() });
	assert_eq!(client.protocol_info(), Some((String::from("liber:log"), 1)));

	// Asking twice must give the same answer: the query carries no state, and a fresh
	// correlation id each time must not change what comes back.
	assert_eq!(client.protocol_info(), Some((String::from("liber:log"), 1)));
}

#[test]
fn a_listing_frame_that_will_not_decode_is_refused_rather_than_read_as_an_entry() {
	// The decoder half of "a short listing must not look complete".
	//
	// A frame the reader cannot decode used to be dropped from the listing and the stream still
	// ended cleanly, so a directory came back silently missing a name - a truncation one entry at
	// a time, invisible because the reader ignores the sequence number and cannot see the gap. The
	// producer now ends the listing instead, and this is the half that says the reader agrees:
	// a damaged frame is `None`, not a guess.
	let mut handles = crate::codec::Handles::new();

	// Truncated after the sequence number, with no record behind it.
	assert!(volume::list_read(&[1, 0, 0, 0], &mut handles).is_none(), "a frame with a sequence and nothing else is not an entry");

	// Empty: the terminal marker, which is not an entry either and must not decode as one.
	assert!(volume::list_read(&[], &mut handles).is_none(), "the terminal frame is not an entry");

	// A length prefix that promises more than the frame carries.
	assert!(volume::list_read(&[1, 0, 0, 0, 0xff, 0xff], &mut handles).is_none(), "a name longer than the frame is refused");

	// A positive case belongs here and is missing on purpose: `FileInfo` and `FileType` are not
	// visible from this module, so a well-formed frame cannot be constructed to prove the reader
	// accepts one. The service-side tests cover that - every listing in the kernel suite decodes
	// real entries - so what is left for here is the refusals above.
}

// A transport that answers with the exact bytes and capabilities a test wrote, so what is under
// test is the CLIENT's framing rather than a matching server's. Every loopback above dispatches
// into a real service, which can only produce replies the generator itself considers well formed -
// and the boundary these tests are about is what happens when a reply is NOT.
//
// `closed` is what `discard_handles` was told to release, which is how a leak is observed from the
// host: this transport hands back handle NUMBERS with no kernel object behind them, so the only
// evidence that a refusal released them is the client asking.
struct ScriptedReply {
	body: Vec<u8>,
	handles: Vec<u64>,
	closed: Vec<u64>,
}

impl crate::codec::Transport for ScriptedReply {
	fn call(&mut self, request: &[u8], _request_handles: &[u64], reply_handles: &mut crate::codec::Handles, _deadline: u64) -> Result<Vec<u8>, crate::codec::TransportError> {
		// The correlation id is echoed from the request, so a test writes only the reply BODY and
		// never has to know which call number it is on.
		let corr = u32::from_le_bytes(request[2..6].try_into().map_err(|_| crate::codec::TransportError::Malformed)?);
		let mut reply = corr.to_le_bytes().to_vec();
		reply.extend_from_slice(&self.body);
		*reply_handles = crate::codec::Handles::try_from_slice(&self.handles).expect("the fixture stays within the bound");
		Ok(reply)
	}

	fn discard_handles(&mut self, handles: &[u64]) {
		self.closed.extend_from_slice(handles);
	}
}

fn scripted(body: &[u8], handles: &[u64]) -> ScriptedReply {
	ScriptedReply { body: body.to_vec(), handles: handles.to_vec(), closed: Vec::new() }
}

#[test]
fn every_arm_of_a_guarded_stream_open_ends_at_its_framing_boundary() {
	// THE PROPERTY THE COUNTING RULE COULD NOT SEE, driven rather than pattern-matched.
	//
	// `lsidl-gen` asserted `finishes >= readers` over the generated TEXT, and a guarded stream open
	// has ONE reader with TWO paths through it: the Ok arm ended at a boundary, the Err arm did not,
	// and one reader with one finish satisfied the count while a refusal with bytes after it decoded
	// as an ordinary refusal. Naming the arms in the generated source closed today's gap and said
	// nothing about a new one - and broke on reindentation, because it was matching Rust formatting.
	//
	// So this drives `volume::list`, whose return is `result<stream<file-info>, error>`, with replies
	// written byte by byte. It fails if an arm stops checking, whatever the generated source looks
	// like, and it is the shape a NEW arm gets tested with.
	const OK: u8 = 1;
	const ERR: u8 = 0;

	// The Err arm: tag, then the error, and nothing else.
	let mut client = volume::Client::new(scripted(&[ERR, Error::NotFound as u8], &[]));
	assert_eq!(client.list("/x"), Some(Err(Error::NotFound)), "a well-formed refusal decodes");
	assert!(client.into_transport().closed.is_empty(), "and an accepted refusal releases nothing, because it carried nothing");

	// The same refusal with one byte after it is a different reply, and is refused.
	let mut client = volume::Client::new(scripted(&[ERR, Error::NotFound as u8, 0xdd], &[]));
	assert_eq!(client.list("/x"), None, "one byte after the error makes a reply its writer and its reader disagree about");

	// The Ok arm: tag, the four-byte handle placeholder, and the capability out-of-band.
	let mut client = volume::Client::new(scripted(&[OK, 0, 0, 0, 0], &[0xC0FFEE]));
	assert_eq!(client.list("/x"), Some(Ok(0xC0FFEE)), "a well-formed stream open hands back the consumer end");
	assert!(client.into_transport().closed.is_empty(), "an accepted stream open keeps its capability - closing it here would strand the caller");

	// And the same reply with one byte after it is refused - WITH the capability released, which is
	// the half that would leak a live channel on every malformed reply if the refusal just returned.
	let mut client = volume::Client::new(scripted(&[OK, 0, 0, 0, 0, 0xdd], &[0xC0FFEE]));
	assert_eq!(client.list("/x"), None, "one byte after the handle placeholder is refused too");
	assert_eq!(client.into_transport().closed, alloc::vec![0xC0FFEE], "and the capability the refused reply carried is closed");

	// A refusal that arrives WITH a capability is malformed by cardinality rather than by length -
	// the schema says the error arm carries none - and the capability is released the same way.
	let mut client = volume::Client::new(scripted(&[ERR, Error::NotFound as u8], &[0xC0FFEE]));
	assert_eq!(client.list("/x"), None, "the error arm carries no capability, so one attached makes the reply malformed");
	assert_eq!(client.into_transport().closed, alloc::vec![0xC0FFEE], "and it is closed rather than leaked");

	// An Ok arm with NO capability is malformed the other way: the client would answer with a
	// stream handle it was never given.
	let mut client = volume::Client::new(scripted(&[OK, 0, 0, 0, 0], &[]));
	assert_eq!(client.list("/x"), None, "an Ok stream open with no capability is not a stream");

	// A tag that is neither arm. `Reader::tag` admits 0 and 1 only, and this is what says so from
	// the outside.
	let mut client = volume::Client::new(scripted(&[2, 0, 0, 0, 0], &[]));
	assert_eq!(client.list("/x"), None, "a tag that names neither arm is refused");
}

#[test]
fn the_identity_query_ends_at_its_boundary_too() {
	// `protocol_info` is emitted by the generator for every interface and was written BESIDE the
	// ordinary reply path rather than through it, so it inherited the shape and not the rule: it
	// answered after reading the package and the version without asking whether that was all the
	// bytes. Two replies that differ are two replies, including this one.
	let mut body = alloc::vec![13, 0]; // u16 length prefix for "liber:storage"
	body.extend_from_slice(b"liber:storage");
	body.extend_from_slice(&1u32.to_le_bytes());

	let mut client = volume::Client::new(scripted(&body, &[]));
	assert_eq!(client.protocol_info(), Some((String::from("liber:storage"), 1)), "the well-formed identity reply decodes");

	let mut trailing = body.clone();
	trailing.push(0xdd);
	let mut client = volume::Client::new(scripted(&trailing, &[]));
	assert_eq!(client.protocol_info(), None, "one byte after the version is refused");

	// The identity query takes no capabilities in either direction, so one attached is refused -
	// and released, because nothing else will.
	let mut client = volume::Client::new(scripted(&body, &[0xC0FFEE]));
	assert_eq!(client.protocol_info(), None, "an identity reply carrying a capability is not an identity reply");
	assert_eq!(client.into_transport().closed, alloc::vec![0xC0FFEE], "and it is closed");
}

#[test]
fn the_facades_channel_feature_selects_every_domains_own() {
	// CARGO FEATURES ARE PER PACKAGE, and this facade only re-exports. `channel-client-impl` was
	// declared here as `["dep:ipc-client"]` alone, so enabling it selected the optional dependency
	// and the same-named feature in NONE of the fifteen crates whose wrappers it is named after.
	// `cargo check --features channel-client-impl` passed while compiling not one
	// `liber_channel_impl_*` symbol, and the mismatch surfaced at a link far from the manifest that
	// caused it. `shared-image` masked it by propagating `X/shared-image` per domain.
	//
	// Read out of the manifest rather than asserted against a list typed here: the failure this
	// guards is a SIXTEENTH protocol crate being added and left out, and a hand-written expectation
	// would have to be updated by the same person who forgot.
	const MANIFEST: &str = include_str!("../Cargo.toml");

	let section = |name: &str| -> &str {
		let start = MANIFEST.find(name).expect("the manifest declares this section");
		let rest = &MANIFEST[start..];
		let end = rest[1..].find("\n[").map(|at| at + 1).unwrap_or(rest.len());
		&rest[..end]
	};
	let features = section("[features]");
	let dependencies = section("[dependencies]");

	// Every protocol dependency, taken from the dependency table.
	let mut domains: Vec<&str> = Vec::new();
	for line in dependencies.lines() {
		let Some((name, _)) = line.split_once(" = ") else { continue };
		let name = name.trim();
		if name.ends_with("-proto") {
			domains.push(name);
		}
	}
	assert!(domains.len() >= 15, "the facade re-exports the protocol crates: {domains:?}");

	// The aggregate has to name each one whose crate declares the feature. `base-proto` has no
	// channel methods and therefore no such feature, so it is expected to be absent - which is
	// checked rather than assumed, since a `base` that grew one and was left out is the same bug.
	let aggregate = features.split("channel-client-impl = [").nth(1).expect("the root feature is a list").split(']').next().expect("terminated");
	for domain in &domains {
		let declares = match *domain {
			"base-proto" => false,
			_ => true,
		};
		let named = aggregate.contains(&alloc::format!("{domain}/channel-client-impl"));
		assert_eq!(named, declares, "{domain} is {} the aggregate and {} declare the feature", if named { "in" } else { "not in" }, if declares { "should" } else { "does not" });
	}
	assert!(aggregate.contains("dep:ipc-client"), "and the optional dependency is still selected");
}
