// Which drivers may touch memory without an IOMMU, and what it costs to say yes.
//
// CAPABILITY ISOLATION DOES NOT COVER DMA. A handle table decides what a driver may ASK the kernel
// for; it decides nothing about what the device does once it is mastering the bus. A bus-mastering
// device programmed by a malicious driver writes wherever it is told, and no capability stops it.
// A system that behaves as though capabilities cover DMA has a hole exactly where its strongest
// claim is, so this module exists to make the hole explicit, bounded and named.
//
// THE POLICY IS REGISTRY DATA, NOT A DEVICE-TYPE LIST. This used to decide from a hard-coded
// `IOMMU_REQUIRED_TYPES` containing virtio-net, and every other device type silently answered
// `TrustedUntranslated` - so the isolation claim rested on a kernel list nobody had to update, and
// adding a driver could not protect it without another kernel arm. The registry below is generated
// from the same `services/manifest.toml` DeviceManager selects from, and every staged driver
// declares one of three policies there: `none`, `iommu-required` or `trusted-untranslated`. The
// kernel does not recompute priority - privileged DeviceManager is the selection authority - and it
// validates that the entry it names EXISTS, that the entry's rules admit the concrete device, and
// that the entry's policy is admissible under the boot's DMA mode. Membership, device, policy,
// generation: that is the complete check.
//
// THE MODE IS STATED, NOT INFERRED. Whether this machine translates is not something the kernel
// discovers from whether a controller happens to be on the bus - a controller that is absent looks
// the same on a machine built without one and on a machine whose attacker removed one. The mode
// arrives from the boot contract: a signed manifest field on a public boot, the named harness on
// every other, carried by the loader's `BootInfo` on a UEFI entry and by the device tree on a
// direct one. A boot with no mode is a boot whose producer failed, and it refuses every claim -
// on EVERY path, with no row that gets absence as a default.

use alloc::vec::Vec;
use bootproto::dma_mode::{Handoff, Mode};
use core::sync::atomic::{AtomicBool, Ordering};
use dma::{BindDecision, Policy};

use crate::sync::SpinLock;

// One entry of the trusted registry: the manifest's program name, its declared policy as the
// `abi::DMA_POLICY_*` code, and the rules that say which devices it is declared for. Generated by
// `build.rs` from `services/manifest.toml` into `DMA_REGISTRY`, so a manifest change rebuilds this
// kernel beside the DeviceManager that selects from the same rows.
pub struct DmaEntry {
	pub name: &'static [u8],
	pub policy: u8,
	pub rules: &'static [driver_binding::Match],
}

include!(concat!(env!("OUT_DIR"), "/dma_registry.rs"));

// THE SYNTHETIC ENTRIES, for the claim tests. `device::add_synthetic_device` appends a device
// nothing on the bus is - vendor and product `0xffff`, class `0xff`, transport plain PCI - and a
// registry that declares nothing for it would refuse every test claim by name, which is the correct
// production answer and the wrong test fixture. Three entries, one per policy, declared for exactly
// that identity and for nothing a real machine has. Test builds only: a shipping kernel carries
// the manifest's rows and no others.
//
// AND THE HOSTILE FIXTURE'S ENTRY. The enforcing gate attaches QEMU's `edu` functions - a DMA engine
// with no driver, told to reach memory it was never given - and the fixture claims them the way a
// manager would, so the claim boundary is the one under test. `edu` has no manifest row and never
// binds in a shipping system; this entry exists only in a test kernel and declares it
// `iommu-required`, which is the policy the fixture is about.
#[cfg(test)]
const TEST_ENTRIES: [DmaEntry; 4] = [
	DmaEntry { name: b"synthetic-trusted", policy: abi::DMA_POLICY_TRUSTED_UNTRANSLATED as u8, rules: &[SYNTHETIC_RULE] },
	DmaEntry { name: b"synthetic-none", policy: abi::DMA_POLICY_NONE as u8, rules: &[SYNTHETIC_RULE] },
	DmaEntry { name: b"synthetic-protected", policy: abi::DMA_POLICY_IOMMU_REQUIRED as u8, rules: &[SYNTHETIC_RULE] },
	DmaEntry { name: b"edu-fixture", policy: abi::DMA_POLICY_IOMMU_REQUIRED as u8, rules: &[EDU_RULE] },
];

#[cfg(test)]
const SYNTHETIC_RULE: driver_binding::Match = driver_binding::Match { transport: Some(abi::TRANSPORT_PLAIN_PCI), virtio_type: None, class: Some(0xff), subclass: None, prog_if: None, vendor: Some(0xffff), product: Some(0xffff), address: None };

// QEMU's `edu` device: vendor 0x1234, device 0x11e8, whatever class it reports.
#[cfg(test)]
const EDU_RULE: driver_binding::Match = driver_binding::Match { transport: None, virtio_type: None, class: None, subclass: None, prog_if: None, vendor: Some(0x1234), product: Some(0x11e8), address: None };

// The 64-byte claim field for one of the synthetic entries - `synthetic-trusted` unless a test
// names another - so a test claims the way DeviceManager does, by name.
#[cfg(test)]
pub fn synthetic_entry() -> [u8; abi::ENTRY_NAME_LEN] {
	abi::entry_name_field(b"synthetic-trusted").expect("the synthetic entry's name fits the field")
}

#[cfg(test)]
pub fn entry_field(name: &[u8]) -> [u8; abi::ENTRY_NAME_LEN] {
	abi::entry_name_field(name).expect("a test entry name fits the field")
}

// The registry entry named by a claim field, or none.
//
// EXACT BYTES. The name is canonical or it was refused at manifest validation, so there is no
// normalisation here - a name that differs in one byte is a name the image does not declare.
pub fn lookup(field: &[u8; abi::ENTRY_NAME_LEN]) -> Option<&'static DmaEntry> {
	let name = abi::entry_name_of(field);
	if name.is_empty() || name.len() < abi::ENTRY_NAME_LEN && field[name.len()..].iter().any(|byte| *byte != 0) {
		// Empty, or bytes after the terminator: not a field the ABI defines.
		return None;
	}
	if let Some(entry) = DMA_REGISTRY.iter().find(|entry| entry.name == name) {
		return Some(entry);
	}
	#[cfg(test)]
	if let Some(entry) = TEST_ENTRIES.iter().find(|entry| entry.name == name) {
		return Some(entry);
	}
	None
}

// The first registry entry whose rules admit `device`, as a CLAIM FIELD. What a test uses to claim
// a real device the way DeviceManager would, without carrying the selection logic into the kernel:
// production callers name the entry they selected, and this answers only "which name would that
// be" for a fixture.
#[cfg(test)]
pub fn entry_matching(device: &driver_binding::Discovered) -> Option<[u8; abi::ENTRY_NAME_LEN]> {
	DMA_REGISTRY.iter().chain(TEST_ENTRIES.iter()).find(|entry| entry.rules.iter().any(|rule| rule.matches(device))).and_then(|entry| abi::entry_name_field(entry.name))
}

// Every entry name the registry declares, for the fixture that proves the table and the manifest
// agree.
#[cfg(test)]
pub fn registry_names() -> Vec<&'static [u8]> {
	DMA_REGISTRY.iter().map(|entry| entry.name).collect()
}

#[cfg(test)]
pub fn registry_policy(name: &[u8]) -> Option<u8> {
	DMA_REGISTRY.iter().find(|entry| entry.name == name).map(|entry| entry.policy)
}

// THE BOOT'S DMA MODE, adopted once by the prologue that received it - `kmain` from the loader's
// `BootInfo` on x86_64, the device-tree ports from the loader's `BootInfo` on a UEFI entry and from
// the tree's own record on a direct one - and read by `init` and every admission after it.
static HANDOFF: SpinLock<Option<Handoff>> = SpinLock::new(None);
static ADOPTED: AtomicBool = AtomicBool::new(false);

// Adopt what the entry path established. `None` is ABSENT - the producer failed - and is adopted
// as such rather than left unadopted, so `init` can tell "nothing was handed over" from "the
// prologue never asked", which is a kernel defect and is said in different words.
pub fn adopt(handoff: Option<Handoff>, path: &str) {
	*HANDOFF.lock() = handoff;
	ADOPTED.store(true, Ordering::Release);
	match handoff {
		Some(handoff) => crate::serial_println!("dma: boot DMA mode {} ({} provenance, {path})", handoff.mode().name(), handoff.provenance_name()),
		None => crate::serial_println!("dma: NO DMA MODE reached this kernel ({path}) - the boot's producer failed to state one, and every device claim will be REFUSED"),
	}
}

pub fn handoff() -> Option<Handoff> {
	*HANDOFF.lock()
}

pub fn mode() -> Option<Mode> {
	handoff().map(Handoff::mode)
}

// Whether an enforcing IOMMU is confirmed to be translating. NOT a hint and not a hope: it is set
// only by a backend that has read back its own bypass-off configuration.
static ENFORCING: AtomicBool = AtomicBool::new(false);

// Who is running untranslated, so the degraded state can be reported rather than inferred. One row
// per device that bound without translation.
static DEGRADED: SpinLock<Vec<Degraded>> = SpinLock::new(Vec::new());

// WHETHER THE ISOLATION SUMMARY HAS ALREADY BEEN PUBLISHED.
//
// `report` is printed once the boot devices have bound, and "have bound" is a judgement the kernel
// makes from the outside: it is the moment its supervisor decides the system is up. That moment can
// legitimately arrive while a driver is still on its way to the bus - a machine whose console never
// attaches gets there on a deadline, not on a device count - and a summary taken then says "every
// bus-mastering device is translated" about a machine that may be about to admit one that is not.
//
// Nothing else in the log would contradict it: admissions are RECORDED rather than printed, on
// purpose, so the list replaces a scattering of lines. So the summary is the only statement a reader
// has, and a stale one is indistinguishable from a true one. This flag is what lets the claim
// retract itself: once it has been published, a later degraded admission says so at the moment it
// happens.
static REPORTED: AtomicBool = AtomicBool::new(false);

// HOW MANY TIMES A PUBLISHED CLAIM HAS BEEN RETRACTED, so a test can assert the retraction rather
// than assert the flag that leads to it. The line itself goes to the serial console, which a kernel
// test cannot read back; the count is the same event, observed from inside.
#[cfg(test)]
static RETRACTIONS: core::sync::atomic::AtomicUsize = core::sync::atomic::AtomicUsize::new(0);

#[cfg(test)]
pub fn retractions_for_test() -> usize {
	RETRACTIONS.load(Ordering::Relaxed)
}

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub struct Degraded {
	pub device_type: u16,
	pub bus: u8,
	pub dev: u8,
	pub func: u8,
}

// Establish the machine's DMA isolation state, once the device table exists.
//
// ENFORCEMENT IS A FACT, ESTABLISHED RATHER THAN ASSUMED. It is on only when a backend has brought
// an IOMMU up and read back its own configuration. The `virtio-iommu` backend's bring-up is what
// this calls, and its confirmed bypass-off transition is what turns the answer into `true`.
//
// AND THE MACHINE IS COMPARED WITH THE STATEMENT. The mode says what this machine is supposed to
// be; the bus says what it is. `enforcing-required` with no translation - a controller absent, or
// present and not up - is a machine that will refuse every DMA-capable claim, and says so here.
// `no-iommu` with a controller on the bus is a controller/mode mismatch: something put a
// controller in a machine whose boot says there is none, and that is refused rather than
// reclassified as an enforcing boot nobody signed for.
pub fn init() {
	let enforcing = crate::iommu::init();
	set_enforcing(enforcing);
	if !ADOPTED.load(Ordering::Acquire) {
		crate::serial_println!("dma: the boot mode was never adopted before policy init - a kernel defect, and every device claim will be REFUSED");
	}
	match (mode(), controller_present(), enforcing) {
		(None, _, _) => {}
		(Some(Mode::EnforcingRequired), _, true) => crate::serial_println!("dma: enforcing-required and the controller is translating - every bus-mastering device will be translated"),
		(Some(Mode::EnforcingRequired), true, false) => crate::serial_println!("dma: enforcing-required and the controller did NOT come up - every DMA-capable claim will be REFUSED"),
		(Some(Mode::EnforcingRequired), false, false) => crate::serial_println!("dma: enforcing-required and there is NO controller on this machine - every DMA-capable claim will be REFUSED"),
		(Some(Mode::NoIommu), true, _) => crate::serial_println!("dma: no-iommu and yet a controller is on the bus - a controller/mode MISMATCH, and every DMA-capable claim will be REFUSED rather than reclassified"),
		(Some(Mode::NoIommu), false, _) => crate::serial_println!("dma: no-iommu - the explicit degraded profile: iommu-required refuses, trusted-untranslated masters the bus untranslated and is listed, none masters nothing"),
	}
}

// Called by the IOMMU backend once translation is confirmed - and by nothing else.
pub fn set_enforcing(enforcing: bool) {
	ENFORCING.store(enforcing, Ordering::Release);
}

pub fn enforcing() -> bool {
	ENFORCING.load(Ordering::Acquire)
}

// Whether a controller is on the bus - the fact the mismatch rule reads. Overridable by a test,
// because the rule's subject is the four combinations of mode and machine and a test must be able
// to state the machine rather than inherit whichever one it runs on.
fn controller_present() -> bool {
	#[cfg(test)]
	if let Some(present) = *CONTROLLER_OVERRIDE.lock() {
		return present;
	}
	crate::iommu::present()
}

#[cfg(test)]
static CONTROLLER_OVERRIDE: SpinLock<Option<bool>> = SpinLock::new(None);

#[cfg(test)]
pub fn set_controller_present_for_test(present: Option<bool>) {
	*CONTROLLER_OVERRIDE.lock() = present;
}

#[cfg(test)]
pub fn set_handoff_for_test(handoff: Option<Handoff>) {
	*HANDOFF.lock() = handoff;
	ADOPTED.store(true, Ordering::Release);
}

// Why a claim was not admitted. Each is a different party's mistake and is printed in its own words
// at the moment it is refused.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Refusal {
	// The boot handed over no mode. Every claim, on every path.
	NoMode,
	// The name the manager passed is not an entry the image declares.
	UnknownEntry,
	// The entry exists and none of its rules admits this device.
	EntryDoesNotMatchDevice,
	// `enforcing-required` and nothing is translating.
	EnforcementAbsent,
	// `no-iommu` and a controller is on the bus.
	ControllerOnDegradedMode,
	// `iommu-required` on a `no-iommu` machine: the policy working.
	PolicyRefused,
	// The degraded answer could not be recorded, so it is not given - see `record_degraded`.
	Unaudited,
}

impl Refusal {
	pub const fn message(self) -> &'static str {
		match self {
			Refusal::NoMode => "no DMA mode reached this kernel",
			Refusal::UnknownEntry => "the named entry is not one this image declares",
			Refusal::EntryDoesNotMatchDevice => "the named entry is not declared for this device",
			Refusal::EnforcementAbsent => "the boot mode is enforcing-required and nothing is translating",
			Refusal::ControllerOnDegradedMode => "the boot mode is no-iommu and a controller is on the bus",
			Refusal::PolicyRefused => "the entry declares iommu-required and the boot mode is no-iommu",
			Refusal::Unaudited => "the degraded admission could not be recorded",
		}
	}
}

// What an admitted claim may do.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Admission {
	// Translated, revocable addresses. Bus mastering on, attached to a domain of its own.
	Translated,
	// Untranslated and audited: bus mastering on, recorded in the degraded inventory.
	DegradedUntranslated,
	// Bus mastering stays OFF, no endpoint is attached, and no DMA buffer may be minted under the
	// claim. The device is programmed through its registers and may interrupt.
	NonMastering,
}

// The policy an entry declares, as the shared vocabulary.
fn policy_of(entry: &DmaEntry) -> Policy {
	match entry.policy as u32 {
		abi::DMA_POLICY_NONE => Policy::None,
		abi::DMA_POLICY_IOMMU_REQUIRED => Policy::IommuRequired,
		_ => Policy::TrustedUntranslated,
	}
}

// May the device at `bus:dev.func`, claimed under `entry`, master the bus - and under what terms?
//
// THE COMPLETE CHECK, in the order the plan states it: the entry exists; its rules admit this
// device; the mode admits its policy. The priority DeviceManager chose is not recomputed here - an
// operator may deliberately select a lower-priority candidate, and a kernel that overruled that
// would be a second selection authority. A refusal is a refusal: there is no fall-back from any of
// them to untranslated DMA, because falling back is precisely the failure the isolation claim
// names - "it must never silently become untranslated DMA."
pub fn admit(entry: &[u8; abi::ENTRY_NAME_LEN], device: &driver_binding::Discovered, device_type: u16) -> Result<(Admission, u8), Refusal> {
	let (bus, dev, func) = (device.bus, device.dev, device.func);
	let verdict = decide(entry, device);
	match verdict {
		Ok((Admission::DegradedUntranslated, policy)) => {
			// AND THE DEGRADED ANSWER IS ONLY GIVEN IF IT CAN BE AUDITED. An unaudited degradation
			// is not a weaker version of the audited one - it is the untracked bypass this module
			// exists to remove. Failing CLOSED costs a device that could have run; failing open costs
			// the isolation claim.
			if !record_degraded(Degraded { device_type, bus, dev, func }) {
				crate::serial_println!("dma: {} at {:02x}:{:02x}.{} would master the bus untranslated and its audit row could not be recorded - REFUSED rather than admitted unaudited", abi::device_type_name(device_type as u32), bus, dev, func);
				return Err(Refusal::Unaudited);
			}
			Ok((Admission::DegradedUntranslated, policy))
		}
		Ok(admitted) => Ok(admitted),
		Err(refusal) => {
			// SAID AT THE MOMENT IT HAPPENS, naming the entry and the value that refused it - the
			// operator reading a `no-iommu` boot with no network needs the sentence that says why.
			crate::serial_println!("dma: claim of {} at {:02x}:{:02x}.{} under entry `{}` REFUSED - {}", abi::device_type_name(device_type as u32), bus, dev, func, core::str::from_utf8(abi::entry_name_of(entry)).unwrap_or("?"), refusal.message());
			Err(refusal)
		}
	}
}

// The decision without its audit side effect, so the matrix can be driven from a test without
// leaving rows behind.
pub fn decide(entry: &[u8; abi::ENTRY_NAME_LEN], device: &driver_binding::Discovered) -> Result<(Admission, u8), Refusal> {
	let Some(found) = lookup(entry) else { return Err(Refusal::UnknownEntry) };
	if !found.rules.iter().any(|rule| rule.matches(device)) {
		return Err(Refusal::EntryDoesNotMatchDevice);
	}
	let policy = policy_of(found);
	let admission = match mode() {
		None => return Err(Refusal::NoMode),
		Some(Mode::EnforcingRequired) => {
			// Both DMA-capable policies are translated here, and either refuses if enforcement is
			// absent or failed. `none` masters nothing and needs no translation to be admitted.
			if policy != Policy::None && !enforcing() {
				return Err(Refusal::EnforcementAbsent);
			}
			dma::decide_bind(policy, true)
		}
		Some(Mode::NoIommu) => {
			if controller_present() {
				return Err(Refusal::ControllerOnDegradedMode);
			}
			dma::decide_bind(policy, false)
		}
	};
	match admission {
		BindDecision::Translated => Ok((Admission::Translated, found.policy)),
		BindDecision::DegradedUntranslated => Ok((Admission::DegradedUntranslated, found.policy)),
		BindDecision::NonMastering => Ok((Admission::NonMastering, found.policy)),
		BindDecision::Refused => Err(Refusal::PolicyRefused),
	}
}

// RECORDED, NOT PRINTED. `report` is what prints, once the devices have bound, and its own comment
// says why: "the answer is a list rather than a scattering of lines".
//
// The record is deduplicated: a driver that opens its device repeatedly must not grow the list it
// is audited from. Answers whether the row is RECORDED - which includes "it was already there",
// because a duplicate is one audited device and not a failure to audit one.
fn record_degraded(entry: Degraded) -> bool {
	// THE LOCK IS RELEASED BEFORE ANYTHING IS PRINTED. The line below is the only place this module
	// prints while a caller is mid-admission, and doing it under the list's lock would put the
	// serial path inside a section every other reader of the list waits on.
	let late: bool = {
		let mut degraded = DEGRADED.lock();
		if degraded.iter().any(|held| *held == entry) {
			return true;
		}
		// ALLOC-OK: bounded by the number of PCI functions the boot scan resolved, and this is the
		// boot path rather than an interrupt.
		if degraded.try_reserve(1).is_err() {
			return false;
		}
		degraded.push(entry);
		REPORTED.load(Ordering::Relaxed)
	};
	// A PUBLISHED CLAIM THAT STOPPED BEING TRUE SAYS SO, HERE, AT THE MOMENT IT STOPS.
	//
	// The summary is printed when the supervisor decides the system is up, and that decision can be
	// made on a deadline over a machine whose devices are still binding. Everything admitted
	// afterwards would then be invisible: the record is silent by design and the summary is already
	// behind in the log. One line at the moment of admission costs nothing on the boots where it
	// never fires, and on the boot where it does it is the difference between an audit trail and a
	// wrong sentence nobody can see is wrong.
	if late {
		#[cfg(test)]
		RETRACTIONS.fetch_add(1, Ordering::Relaxed);
		crate::serial_println!("dma: ADMITTED UNTRANSLATED AFTER THE ISOLATION SUMMARY - {} at {:02x}:{:02x}.{} masters the bus untranslated, so the summary above is no longer this machine's state", abi::device_type_name(entry.device_type as u32), entry.bus, entry.dev, entry.func);
	}
	true
}

// The device has given the bus back, so it is no longer one of the devices reaching memory
// untranslated - and the audit list must stop saying it is.
//
// THE RECORD HAS THE SAME LIFETIME AS THE OWNERSHIP IT DESCRIBES. `admit` writes the row at the
// moment a driver ASKS to master the bus, which is the right moment to take the decision and the
// wrong one to make the record permanent: a driver that asked, failed to bind and released was
// audited forever as reaching memory untranslated.
pub fn forget_degraded(bus: u8, dev: u8, func: u8) {
	DEGRADED.lock().retain(|held| !(held.bus == bus && held.dev == dev && held.func == func));
}

// Everything currently running untranslated. The report a supervisor reads, and what a test asserts
// against.
pub fn degraded_devices() -> Vec<Degraded> {
	// ALLOC-OK: a copy of a list with one row per PCI function the boot scan resolved, taken by the
	// boot report and by tests. Not on any syscall path.
	DEGRADED.lock().clone()
}

// The state of the system's DMA isolation, printed once the boot devices have bound.
//
// SAID AT THE END RATHER THAN PER DEVICE, because the question a reader has is "is anything reaching
// memory untranslated", and the answer is a list rather than a scattering of lines. A system with an
// enforcing IOMMU and an empty list is the only shape that carries the isolation claim.
pub fn report() {
	// AND THE CONTROLLER'S OWN STATE WITH IT. What this machine has to translate WITH and who is
	// running untranslated are one question with two halves, and a reader wants them together.
	crate::iommu::report();
	match handoff() {
		Some(handoff) => crate::serial_println!("dma: mode {} ({} provenance)", handoff.mode().name(), handoff.provenance_name()),
		None => crate::serial_println!("dma: mode ABSENT - no device was admitted"),
	}
	let degraded = degraded_devices();
	if enforcing() && degraded.is_empty() {
		crate::serial_println!("dma: every bus-mastering device is translated");
		// ARMED ON THE CLEAN PATH TOO, and this is the path that needs it. "Every bus-mastering
		// device is translated" is the strongest sentence this kernel prints about isolation, and it
		// is the one a later admission falsifies.
		REPORTED.store(true, Ordering::Relaxed);
		return;
	}
	crate::serial_println!("dma: DEGRADED ISOLATION - {} device(s) master the bus untranslated (enforcing={})", degraded.len(), enforcing());
	for entry in &degraded {
		crate::serial_println!("dma:   {} at {:02x}:{:02x}.{}", abi::device_type_name(entry.device_type as u32), entry.bus, entry.dev, entry.func);
	}
	REPORTED.store(true, Ordering::Relaxed);
}

#[cfg(test)]
pub fn forget_degraded_for_test() {
	DEGRADED.lock().clear();
	// AND THE PUBLISHED-CLAIM FLAG WITH IT, because a test that calls `report` would otherwise leave
	// every later test's admission printing a retraction of a summary that belongs to another test.
	REPORTED.store(false, Ordering::Relaxed);
	RETRACTIONS.store(0, Ordering::Relaxed);
}

#[cfg(test)]
mod tests;
