// The one-line synopses the shell's `help` prints. SEPARATE FROM `commands.rs` because that module
// compiles into ConsoleService too, which completes command words and never describes them.
//
// A one-line synopsis for every command the shell knows - the builtins it runs itself
// and the governed / net tools it launches. The `help` builtin prints the whole table
// (sorted); `<command> --help` (and `help <command>`) prints one row. Kept here, one
// place, so a command gets `--help` without every tool ELF hand-rolling a usage string.
// Each entry is (command word, "synopsis - what it does"). Grown in step with the
// dispatch tables (TOOLS / NET_TOOLS in shell.rs and the builtin arms).
pub const SYNOPSES: &[(&str, &str)] = &[
	// shell builtins
	("cd", "cd [dir] - change the working directory (no arg: the system volume)"),
	("env", "env - list the environment variables"),
	("unset", "unset NAME - remove an environment variable (NAME=VALUE sets one)"),
	("jobs", "jobs - list background and stopped jobs"),
	("fg", "fg [job] - resume a job in the foreground"),
	("bg", "bg [job] - resume a stopped job in the background"),
	("time", "time COMMAND - run COMMAND and print its wall-clock time"),
	("clear", "clear - clear the screen"),
	("size", "size - print the terminal size"),
	("resize", "resize COLSxROWS - request a new terminal size"),
	("graph", "graph [json|json-min|cbor|NAME] - render the live system graph, or the one component NAME"),
	("mouse", "mouse - toggle the mouse-reporting demo view"),
	("exit", "exit - log out of this shell (also: quit)"),
	("quit", "quit - log out of this shell (also: exit)"),
	("reboot", "reboot - restart the machine"),
	("poweroff", "poweroff - power the machine off (also: shutdown)"),
	("shutdown", "shutdown - power the machine off (also: poweroff)"),
	("help", "help [command] - list the commands, or show one command's usage"),
	// filesystem / inventory tools
	("ls", "ls [-s KEY][-u UNIT][json] [path] - list a directory"),
	("du", "du [-s][-h][json] [path] - recursive disk usage of a tree"),
	("cat", "cat PATH - print a file"),
	("lico", "lico [DIRECTORY] - open the two-panel file manager"),
	("licoview", "licoview PATH - view a bounded text preview"),
	("licoedit", "licoedit PATH - edit a bounded buffer without persistence"),
	("write", "write PATH TEXT - write TEXT to a file"),
	("rm", "rm PATH - remove a file"),
	("pwd", "pwd [json] - print the inherited working directory"),
	("kill", "kill [--term|--kill|--stop|--continue] JOB... - signal a session job"),
	("sort", "sort [-r][-u][-n][-k FIELD] PATH - order a file's lines"),
	("cut", "cut -b|-c|-f RANGES [-d CHAR] PATH - select parts of each line"),
	("tree", "tree [-L N][-d|-f][-s][json] [path] - render a directory tree"),
	("find", "find [path...] [--name GLOB][--type f|d] - print matching paths"),
	("grep", "grep [-i][-v][-n][-c][-l] TEXT PATH... - print matching lines"),
	("cp", "cp [-f] SRC DST - copy a file, published only when complete"),
	("mv", "mv [-f] SRC DST - rename within a volume, copy-verify-delete across"),
	("clear", "clear - erase the display and home the cursor"),
	("which", "which NAME... - print the artifact each command name resolves to"),
	("wc", "wc PATH... [json] - count lines, words, bytes and characters"),
	("head", "head [-n N][-c N][-q] PATH... - print the first lines or bytes"),
	("tail", "tail [-n N][-f] PATH - print the last lines, optionally following"),
	("hexdump", "hexdump [-s SKIP][-n LEN] PATH - offsets, hex bytes and ASCII"),
	("tee", "tee [-a][--fail-fast] PATH... - copy the input stream to stdout and to files"),
	("watch", "watch [-n SECONDS] COMMAND [ARG...] - rerun a command and show its latest output"),
	("less", "less [-N][-S] [PATH] - page a file or the input stream one screen at a time"),
	("traceroute", "traceroute [-m HOPS][-q PROBES] HOST [json] - the path a packet takes, hop by hop"),
	("truncate", "truncate -s SIZE PATH... - set a file length (+/- is relative)"),
	("touch", "touch [-c][-d SECS] PATH... - stamp mtime, creating when asked"),
	("mkdir", "mkdir PATH - create a directory"),
	("rmdir", "rmdir PATH - remove an empty directory"),
	("snap", "snap <create|list|delete|restore> ... - volume snapshots"),
	("volume", "volume <status|compress|...> ... - volume health and policy"),
	("lsvol", "lsvol [json] - list the volumes with size / used / free"),
	("lsblk", "lsblk [json] - list the block devices and their volumes"),
	("lsdev", "lsdev [json] - list the device nodes"),
	("btctl", "btctl [-c N] [list|scan|pair|enable|disable|forget|power] ... - Bluetooth controllers, pairing and bonds"),
	("sleepctl", "sleepctl [last | status | suspend [idle|ram] [SECONDS] | hibernate [hybrid] | inhibit SECONDS REASON | wake-at SECONDS | wake-cancel] - put the machine to sleep, what can wake it, and how the last sleep ended"),
	("powerctl", "powerctl [status | profile performance|balanced|power-saving | curve FAN CELSIUS:PERCENT...] - the power sources, the processors' profile, states and windows, the thermal zones and the fans"),
	("tpm", "tpm info | random N | pcr N | extend N TEXT | seal N TEXT FILE | unseal FILE | quote N NONCE FILE - the TPM's identity, random bytes, PCRs, sealed secrets and quotes"),
	("bmc", "bmc [info | sensors | sel [--follow | clear] | fru | chassis ... | lan | users] [BMC] - the BMCs this system reaches; erasing and stopping are asked of a person"),
	("typec", "typec - every USB Type-C connector: its partner, roles, contract, offers, cable, modes and last refusal"),
	("brightness", "brightness [set LEVEL|PERCENT%|up|down [--backlight KEY] [--zero] | auto on|off | idle SECONDS|off] - the outputs and their backlights, a level, and the policy's automatic brightness and idle timeout"),
	("audioctl", "audioctl [devices | default DEVICE output|input|voice | volume DEVICE LEVEL | streams | counters] - the audio devices, the defaults, each device's level and where the streams play"),
	("dfu", "dfu TARGET IMAGE | dfu backup TARGET FILE [MAX] - write a firmware image to a USB DFU target, or read its firmware out into FILE; a person confirms either on the protected screen"),
	("lscpu", "lscpu [json] - print the CPU inventory"),
	("lsmem", "lsmem [json] - print the boot memory map"),
	("lsirq", "lsirq [json] - print the device-interrupt vectors"),
	("lspci", "lspci [json] - print the PCI bus scan"),
	("lsusb", "lsusb [json] - print the USB bus inventory"),
	("gamepad", "gamepad [--lines] - show which button is pressed on which gamepad"),
	("lssvc", "lssvc [json] [prefix] - list the services and their state"),
	// system / status tools
	("ps", "ps [json] - list the running processes"),
	("free", "free [-h] - print the memory totals"),
	("icdcheck", "icdcheck - reach the provider bound into a selection slot and report what it agreed to"),
	("lifecheck", "lifecheck - report what ran before this program started and what runs after it ends"),
	("vkprobe", "vkprobe - run the audit-linked loader against the ICD bound into this process"),
	("abiprobe", "abiprobe - call every admitted foreign ABI facility once and check the answer"),
	// The destination services' gate probes, in a development image.
	("btcheck", "btcheck CASE - drive the Bluetooth gate against the in-guest fixture"),
	("btread", "btread - read Bluetooth state with the read authority alone"),
	("btclassic", "btclassic PHASE - drive the Bluetooth gates' scenarios against the fixture"),
	("audioprobe", "audioprobe inventory|hold|operator|voice - the audio device model's gate driver (development)"),
	("btgatt", "btgatt - read, write and subscribe through one GATT grant on the peer aliased tag-1"),
	("hidcheck", "hidcheck CASE - drive the HID-over-I2C gate: a live pointer and contact client with a focused surface"),
	("powercheck", "powercheck CASE - drive the power gate against the in-guest fixture"),
	("powerread", "powerread - read power state with the read authority alone"),
	("acpipower", "acpipower CASE - read the firmware's battery, adapter and thermal zone as a live power client"),
	("sleepcheck", "sleepcheck count SECONDS | timer MS | clocks - what an application sees across a sleep"),
	("procprobe", "procprobe load SECONDS | idle SECONDS - a core kept busy, or the scripted idle pattern"),
	("bmccheck", "bmccheck CASE - watch a BMC's thermal zones through PowerService, its log through the BMC service's follow, and this boot's event reaching every log"),
	("typeccheck", "typeccheck CASE - watch the Type-C connectors and their `usb-c` sources, and make the operator's requests"),
	("brightcheck", "brightcheck CASE - drive the brightness gate: list, set, step, the floor and its explicit zero, and the policy's settings"),
	("brightread", "brightread - read the backlights with the read authority alone, and be refused a set"),
	("upscheck", "upscheck CASE - read and drive a USB UPS through PowerService as a live client and operator"),
	("cardcheck", "cardcheck CASE - drive the smart-card gate against the in-guest fixture"),
	("cardhold", "cardhold CASE - hold a smart-card transaction for the smart-card gate"),
	("cardread", "cardread - read a reader with a read-only smart-card grant"),
	("cardb", "cardb - use the second fixture reader's grant"),
	("modemcheck", "modemcheck CASE - drive the modem gate against the in-guest fixture"),
	("modemhold", "modemhold CASE - hold a modem data context for the modem gate"),
	("modemswap", "modemswap CASE - replace the uplink with a modem context"),
	("modemdata", "modemdata - use a modem with a data grant alone"),
	("tpmprobe", "tpmprobe CASE - drive the TPM gate's refusals and a held connection with the observation and sealing grants"),
	("modemfail", "modemfail - a launch whose second modem grant cannot be minted"),
	("camcheck", "camcheck CASE - drive the camera gate against the in-guest fixture"),
	("camhold", "camhold CASE - hold a camera capture for the camera gate"),
	("camread", "camread - list cameras with inventory alone"),
	("camfail", "camfail - a launch whose second grant cannot be minted"),
	("midicheck", "midicheck CASE - drive the MIDI gate against the in-guest fixture"),
	("midihold", "midihold CASE - hold a MIDI receiver for the MIDI gate"),
	("midiump", "midiump CASE - drive the MIDI gate's UMP phases against the in-guest fixture"),
	("midiread", "midiread - list MIDI endpoints with inventory alone"),
	("midifail", "midifail - a launch whose second grant cannot be minted"),
	("gamepadcheck", "gamepadcheck - drive the gamepad tool's gate from `gamepad --lines` against the in-guest fixture"),
	("admincheck", "admincheck CASE - drive the administrative-path gate as a requester"),
	("adminhelper", "adminhelper CASE - hold another launch's endpoints for the administrative-path gate"),
	("adminhostile", "adminhostile SECONDS - an ordinary client trying to cover the protected screen"),
	("uname", "uname - print the system identity"),
	("uptime", "uptime - print how long the system has been up"),
	("date", "date - print the wall-clock date and time"),
	("dmesg", "dmesg - print the kernel boot log"),
	("log", "log [--boot N] [json] - query the structured journal"),
	("config", "config [KEY | set KEY VALUE] - read or set the config tree"),
	("set", "set KEY VALUE - set a config node (also: config set)"),
	("perm", "perm [json] - print the permission audit trail"),
	("usage", "usage [json] - print the per-domain resource budgets"),
	("beep", "beep [FREQ [MS]] - play a tone"),
	("audiorec", "audiorec [-r HZ][-c N][-s SECS][-f] PATH - record PCM audio to a WAV file"),
	("audioconv", "audioconv [--format F][--rate HZ][--channels N][--bits N][-f] IN OUT - convert audio"),
	("stop", "stop SERVICE - stop a service and its dependents"),
	("run", "run NAME [args] - launch a governed tool by name"),
	// network tools
	("ip", "ip - show the network interfaces (also: net)"),
	("net", "net - show the network interfaces (also: ip)"),
	("arp", "arp - show the neighbour (ARP) cache"),
	("ss", "ss - show the sockets (also: netstat)"),
	("netstat", "netstat - show the sockets (also: ss)"),
	("ping", "ping HOST - probe a host with ICMP echo"),
	("nslookup", "nslookup HOST - resolve a host name (also: host)"),
	("host", "host HOST - resolve a host name (also: nslookup)"),
	("tcp", "tcp HOST PORT - open a TCP connection"),
	("nc", "nc HOST PORT - a netcat-style TCP client"),
	("httpd", "httpd [port] - serve the system volume over HTTP (backgrounds)"),
];

// The synopsis for `command`, if it is a known command.
pub fn synopsis(command: &[u8]) -> Option<&'static str> {
	for &(name, text) in SYNOPSES {
		if name.as_bytes() == command {
			return Some(text);
		}
	}
	None
}
