//! ENVIRONMENT LIGHTING: the split-sum approximation, its two halves, and the irradiance term.
//!
//! THE PREFILTER AND THE LOOKUP TABLE ARE TWO HALVES OF ONE APPROXIMATION AND ARE USELESS IF THE TWO
//! ENDS DISAGREE. The split sum replaces one integral over the environment with a product of two
//! precomputed ones; a prefilter built for a different lookup table, or a table built from a
//! different visibility term, produces a material that is wrong in a way no single image reveals -
//! it is subtly too bright at one roughness and too dark at another.
//!
//! SO BOTH ARE GENERATED HERE, FROM THE SAME `pbr` TERMS THE DIRECT LIGHTING USES. The profile says
//! the table is "generated by the same GGX and Smith terms above", and that is meant literally:
//! `brdf_integration` calls `pbr::visibility_smith`, not a second Smith written for image-based
//! lighting with its own `k`. Two Smith terms in one renderer is two materials.
//!
//! THE SAMPLE SEQUENCE IS NOT IN THE PROFILE, AND THAT IS DELIBERATE ON THE PROFILE'S PART. Its
//! tolerance for an environment lookup says so in as many words - "the prefilter is an
//! importance-sampled integral, and its residual noise is the largest term in the comparison" - so
//! an implementation using a different low-discrepancy sequence still conforms. This one uses
//! Hammersley, which is the usual choice and needs no state.

use render_math::quaternion::sin_cos;
use render_math::{Vec3, sqrt};

use crate::pbr::visibility_smith;

/// The BRDF lookup table is 256 by 256, `x` = `dot(N,V)` and `y` = roughness.
pub const BRDF_TABLE_SIZE: u32 = 256;

/// How many importance samples a prefiltered texel takes.
pub const PREFILTER_SAMPLES: u32 = 1024;

/// The smallest cube face the prefilter descends to.
///
/// BELOW 8x8 THE FILTER IS WIDER THAN THE FACE and the result is the average of the whole
/// environment anyway, so a level below it would cost a mip and carry no information.
pub const SMALLEST_PREFILTER_FACE: u32 = 8;

/// How many prefilter levels a cube of this face size has.
pub fn prefilter_levels(face_size: u32) -> u32 {
	let mut size = face_size;
	let mut levels = 0u32;
	while size >= SMALLEST_PREFILTER_FACE {
		levels += 1;
		size /= 2;
	}
	levels
}

/// The roughness level `i` of `levels` holds: `i / (levels - 1)`, so the first is a mirror and the
/// last is fully rough.
pub fn prefilter_roughness(level: u32, levels: u32) -> f32 {
	if levels <= 1 {
		return 0.0;
	}
	(level.min(levels - 1) as f32) / ((levels - 1) as f32)
}

/// The Hammersley point set: the index over the count, and the radical inverse in base 2.
pub fn hammersley(index: u32, count: u32) -> (f32, f32) {
	if count == 0 {
		return (0.0, 0.0);
	}
	(index as f32 / count as f32, (index.reverse_bits() as f32) * 2.328_306_4e-10)
}

/// An orthonormal basis around a unit normal.
///
/// THE BRANCH IS ON WHICH AXIS THE NORMAL IS LEAST ALIGNED WITH, because crossing with an axis the
/// normal is parallel to gives a zero vector - which is a NaN after normalisation and a black texel
/// in the prefiltered cube at exactly one direction per face.
pub fn orthonormal_basis(normal: Vec3) -> (Vec3, Vec3) {
	let away = if normal.z.abs() < 0.999 { Vec3::new(0.0, 0.0, 1.0) } else { Vec3::new(1.0, 0.0, 0.0) };
	let tangent = away.cross(normal).normalise().unwrap_or(Vec3::new(1.0, 0.0, 0.0));
	let bitangent = normal.cross(tangent);
	(tangent, bitangent)
}

/// One GGX importance sample's half vector, around a unit normal.
///
/// NO `acos` ANYWHERE. The usual derivation writes `theta = acos(sqrt(...))` and then takes its sine
/// and cosine again; the cosine IS that square root, and the sine follows from it, so the angle is
/// never formed. That matters here beyond tidiness: this crate is `no_std` and an inverse cosine is
/// a series whose error would enter every one of the 1024 samples.
pub fn importance_sample_ggx(sample: (f32, f32), a: f32, normal: Vec3) -> Vec3 {
	let (u1, u2) = sample;
	let a2 = a * a;
	let cos_theta_squared = ((1.0 - u2) / (1.0 + (a2 - 1.0) * u2)).clamp(0.0, 1.0);
	let cos_theta = sqrt(cos_theta_squared);
	let sin_theta = sqrt((1.0 - cos_theta_squared).max(0.0));
	let (sin_phi, cos_phi) = sin_cos(2.0 * core::f32::consts::PI * u1);
	let (tangent, bitangent) = orthonormal_basis(normal);
	tangent.scale(sin_theta * cos_phi).add(bitangent.scale(sin_theta * sin_phi)).add(normal.scale(cos_theta))
}

/// The split-sum BRDF table's two channels at one `(dot(N,V), roughness)`.
///
/// `A` SCALES `F0` AND `B` IS ADDED TO IT, which is what makes the table two channels rather than
/// one: the environment term is `prefiltered * (F0 * A + B)`, and the split is exactly what lets one
/// table serve every F0.
///
/// GENERATED FROM `pbr::visibility_smith`, the profile's own term. The usual image-based-lighting
/// derivation substitutes a different Smith `k` here, and a renderer that did that would have two
/// materials: one for its lights and one for its sky.
pub fn brdf_integration(n_dot_v: f32, roughness: f32, samples: u32) -> (f32, f32) {
	let n_dot_v = n_dot_v.clamp(1e-4, 1.0);
	let a = roughness * roughness;
	let normal = Vec3::new(0.0, 0.0, 1.0);
	// The view is in the x-z plane at the given elevation, which loses no generality: the integrand
	// is rotationally symmetric about the normal.
	let view = Vec3::new(sqrt((1.0 - n_dot_v * n_dot_v).max(0.0)), 0.0, n_dot_v);
	let mut scale = 0.0f32;
	let mut bias = 0.0f32;
	for index in 0..samples {
		let half = importance_sample_ggx(hammersley(index, samples), a, normal);
		let v_dot_h = view.dot(half);
		// REFLECT THE VIEW ABOUT THE HALF VECTOR, which is what makes this an importance sample of
		// the specular lobe rather than of the hemisphere.
		let light = half.scale(2.0 * v_dot_h).sub(view);
		let n_dot_l = light.z;
		if n_dot_l <= 0.0 {
			continue;
		}
		let n_dot_h = half.z.max(0.0);
		if n_dot_h <= 0.0 {
			continue;
		}
		let v_dot_h = v_dot_h.clamp(0.0, 1.0);
		// `G_vis = G * VoH / (NoH * NoV)`, with `G = 4 * NoL * NoV * V_smith` - so the `NoV`
		// cancels and the profile's visibility term goes in directly.
		let visible = 4.0 * n_dot_l * visibility_smith(n_dot_l, n_dot_v, a) * v_dot_h / n_dot_h;
		let one_minus = (1.0 - v_dot_h).clamp(0.0, 1.0);
		let squared = one_minus * one_minus;
		let fresnel = squared * squared * one_minus;
		scale += (1.0 - fresnel) * visible;
		bias += fresnel * visible;
	}
	if samples == 0 {
		return (0.0, 0.0);
	}
	let count = samples as f32;
	(scale / count, bias / count)
}

/// The environment term: `prefiltered(R, roughness) * (F0 * A + B)`.
pub fn environment_term(f0: Vec3, prefiltered: Vec3, brdf: (f32, f32)) -> Vec3 {
	let (scale, bias) = brdf;
	prefiltered.mul(f0.scale(scale).add(Vec3::new(bias, bias, bias)))
}

/// One prefiltered texel: the GGX-importance-sampled radiance about a direction.
///
/// THE SOURCE IS A CALLBACK TAKING A DIRECTION AND A SOLID ANGLE, because the profile requires the
/// source to be sampled "at a mip chosen by the sample's own solid angle" - which is what removes
/// the fireflies a naive prefilter has, and which only the caller's sampler can do. A prefilter that
/// took a plain direction would be a prefilter this profile does not describe.
///
/// `N = V = R` IS THE APPROXIMATION EVERY SPLIT-SUM PREFILTER MAKES, and it is why the result is a
/// function of the reflection direction alone rather than of the view and the normal separately.
///
/// `FnMut` AND NOT `Fn`: a real sampler carries state - a mip cache, a texel counter, a fetch it
/// wants to record - and requiring it to be immutable would make every caller wrap its sampler in a
/// cell for no reason this function has.
pub fn prefilter_direction(direction: Vec3, roughness: f32, samples: u32, mut source: impl FnMut(Vec3, f32) -> Vec3) -> Vec3 {
	let Ok(normal) = direction.normalise() else { return Vec3::new(0.0, 0.0, 0.0) };
	let a = roughness * roughness;
	let mut total = Vec3::new(0.0, 0.0, 0.0);
	let mut weight = 0.0f32;
	for index in 0..samples {
		let sample = hammersley(index, samples);
		let half = importance_sample_ggx(sample, a, normal);
		let n_dot_h = normal.dot(half);
		let light = half.scale(2.0 * n_dot_h).sub(normal);
		let n_dot_l = normal.dot(light);
		if n_dot_l <= 0.0 {
			continue;
		}
		// THE SAMPLE'S OWN SOLID ANGLE, from the distribution's density at this half vector. A
		// sample in a sparse part of the lobe covers more of the environment and must be taken from
		// a coarser mip, or a bright texel the lobe barely touches becomes a firefly.
		let d = crate::pbr::distribution_ggx(n_dot_h.max(0.0), a);
		let density = d * n_dot_h / (4.0 * n_dot_h).max(1e-6);
		let solid_angle = if density > 0.0 { 1.0 / (samples as f32 * density) } else { 0.0 };
		total = total.add(source(light, solid_angle).scale(n_dot_l));
		weight += n_dot_l;
	}
	if weight > 0.0 { total.scale(1.0 / weight) } else { Vec3::new(0.0, 0.0, 0.0) }
}

/// Nine spherical-harmonic coefficients holding an environment's irradiance.
///
/// THE PERMITTED ALTERNATIVE TO AN IRRADIANCE CUBE, and the profile requires only that the two agree
/// within its threshold - which is a statement about the RESULT and not about the coefficients, so
/// this is a conforming implementation rather than a second specification.
///
/// NINE IS NOT A BUDGET, IT IS THE WHOLE ANSWER. A cosine lobe's spherical-harmonic expansion has
/// 99.2 per cent of its energy in the first three bands; the tenth coefficient and everything after
/// it describes detail a cosine convolution has already removed.
#[derive(Clone, Copy, PartialEq, Debug)]
pub struct Irradiance {
	coefficients: [Vec3; 9],
}

impl Irradiance {
	pub const fn new() -> Self {
		Self { coefficients: [Vec3::new(0.0, 0.0, 0.0); 9] }
	}

	/// Project one direction's radiance into the coefficients.
	///
	/// `solid_angle` IS THE TEXEL'S, and it is the caller's because only the caller knows the cube's
	/// projection: the corner texels of a cube face cover a smaller solid angle than the middle
	/// ones, and a projection that ignored it would weight the corners of the sky too heavily.
	pub fn add(&mut self, direction: Vec3, radiance: Vec3, solid_angle: f32) {
		let Ok(d) = direction.normalise() else { return };
		let basis = basis(d);
		for (coefficient, weight) in self.coefficients.iter_mut().zip(basis) {
			*coefficient = coefficient.add(radiance.scale(weight * solid_angle));
		}
	}

	/// The irradiance arriving at a surface with this normal.
	///
	/// THE RESULT IS IRRADIANCE `E(n)` AND NOT AN EXIT RADIANCE. A Lambertian surface's contribution
	/// is `albedo * E(n) / pi`, the same `1 / pi` the direct diffuse term carries - so the caller
	/// applies it in the one place rather than this function applying it in another.
	///
	/// THE CONSTANTS ARE THE ANALYTIC COSINE CONVOLUTION, whose band factors are `pi`, `2pi/3` and
	/// `pi/4`. They are not a choice: any correct convolution produces these, which is what makes
	/// the profile's "the same result to within the threshold" checkable at all.
	pub fn evaluate(&self, normal: Vec3) -> Vec3 {
		let Ok(n) = normal.normalise() else { return Vec3::new(0.0, 0.0, 0.0) };
		const C1: f32 = 0.429_043;
		const C2: f32 = 0.511_664;
		const C3: f32 = 0.743_125;
		const C4: f32 = 0.886_227;
		const C5: f32 = 0.247_708;
		let c = &self.coefficients;
		let quadratic = c[8].scale(C1 * (n.x * n.x - n.y * n.y)).add(c[6].scale(C3 * n.z * n.z)).sub(c[6].scale(C5));
		let cross = c[4].scale(2.0 * C1 * n.x * n.y).add(c[7].scale(2.0 * C1 * n.x * n.z)).add(c[5].scale(2.0 * C1 * n.y * n.z));
		let linear = c[3].scale(2.0 * C2 * n.x).add(c[1].scale(2.0 * C2 * n.y)).add(c[2].scale(2.0 * C2 * n.z));
		c[0].scale(C4).add(linear).add(quadratic).add(cross)
	}

	pub fn coefficient(&self, index: usize) -> Option<Vec3> {
		self.coefficients.get(index).copied()
	}
}

impl Default for Irradiance {
	fn default() -> Self {
		Self::new()
	}
}

/// The nine real spherical-harmonic basis functions at a unit direction, in the order the
/// coefficients are stored: `Y00`, `Y1-1`, `Y10`, `Y11`, `Y2-2`, `Y2-1`, `Y20`, `Y21`, `Y22`.
fn basis(d: Vec3) -> [f32; 9] {
	[
		0.282_095,
		0.488_603 * d.y,
		0.488_603 * d.z,
		0.488_603 * d.x,
		1.092_548 * d.x * d.y,
		1.092_548 * d.y * d.z,
		0.315_392 * (3.0 * d.z * d.z - 1.0),
		1.092_548 * d.x * d.z,
		0.546_274 * (d.x * d.x - d.y * d.y),
	]
}
