//! `docs/GRAPHICS.md`, generated from the layer registry it names.
//!
//! ITS CORE IS A NAMING DECISION, and a naming decision written in prose is one that drifts the first
//! time somebody adds a sixth meaning. The five names, the ownership edges, the integration routes
//! and the validation boundaries are all enumerations, so they are generated - and a fixture holds
//! them to being distinct, acyclic and complete.

use std::fmt::Write as _;

use graphics_profile::layers::{BOUNDARIES, LAYERS, OWNERSHIP, ROUTES};

/// The canonical machine-readable form the hash is taken over.
pub fn canonical() -> String {
	let mut out = String::new();
	let _ = writeln!(out, "profile=graphics-layers version={}", graphics_profile::image::IMAGE_COLOR_PROFILE_VERSION);
	for layer in LAYERS {
		let _ = writeln!(out, "layer={} owner={} what={}", layer.name, layer.owner, layer.what);
	}
	for edge in OWNERSHIP {
		let _ = writeln!(out, "edge={}->{} carries={}", edge.above, edge.below, edge.carries);
	}
	for route in ROUTES {
		let _ = writeln!(out, "route={} through={} refused={}", route.api, route.through, route.refused);
	}
	for boundary in BOUNDARIES {
		let _ = writeln!(out, "boundary={} untrusted={} checks={}", boundary.at, boundary.untrusted, boundary.checks);
	}
	out
}

/// The document a person reads.
pub fn document(hash: &str) -> String {
	let mut out = String::from("<!-- @generated by profile-doc from the graphics layer registry. Do not edit; run `./gen.sh`. -->\n");
	let _ = writeln!(out, "# Graphics\n");
	let _ = writeln!(out, "Layer registry hash: `{hash}`\n");
	let _ = writeln!(out, "## The names\n");
	let _ = writeln!(out, "`framebuffer` meant five things in this tree: the UEFI boot surface in `bootproto`, the virtio-gpu");
	let _ = writeln!(out, "resource's DMA backing, the DisplayService scanout, an application's surface, and `pix::Target`. A");
	let _ = writeln!(out, "word that means five things is a word every conversation has to disambiguate and every interface");
	let _ = writeln!(out, "eventually gets wrong - and the way it gets wrong is that somebody passes one of the five where");
	let _ = writeln!(out, "another was meant, which type-checks whenever both are a pointer and a length.\n");
	let _ = writeln!(out, "Each has its own name. Nothing else in this tree is called a framebuffer.\n");
	let _ = writeln!(out, "| name | what it is | owner |");
	let _ = writeln!(out, "| --- | --- | --- |");
	for layer in LAYERS {
		let _ = writeln!(out, "| **{}** | {} | {} |", layer.name, layer.what, layer.owner);
	}

	let _ = writeln!(out, "\n## The stack\n");
	let _ = writeln!(out, "Nothing below depends on anything above it. The edges are an enumeration rather than a diagram,");
	let _ = writeln!(out, "because a diagram is checked by whoever reads it and a list of edges is checked by a fixture - which");
	let _ = writeln!(out, "is what stops a layer growing a dependency nobody agreed to, the one failure that turns a stack into");
	let _ = writeln!(out, "a knot.\n");
	let _ = writeln!(out, "```text");
	let _ = writeln!(out, "    application / UI toolkit / game / CAD / editor");
	let _ = writeln!(out, "         |                                    |");
	let _ = writeln!(out, "         |                                 scene3d");
	let _ = writeln!(out, "         |                                    |");
	let _ = writeln!(out, "      render2d                            render3d");
	let _ = writeln!(out, "         |                                    |");
	let _ = writeln!(out, "      soft2d ... future gpu2d           soft3d ... future gpu3d");
	let _ = writeln!(out, "         |                                    |");
	let _ = writeln!(out, "         +------------ graphics-core ---------+");
	let _ = writeln!(out, "                            |");
	let _ = writeln!(out, "                   Surface / present queue");
	let _ = writeln!(out, "                            |");
	let _ = writeln!(out, "                      DisplayService");
	let _ = writeln!(out, "                            |");
	let _ = writeln!(out, "                      display driver");
	let _ = writeln!(out, "```\n");
	let _ = writeln!(out, "| above | below | what crosses |");
	let _ = writeln!(out, "| --- | --- | --- |");
	for edge in OWNERSHIP {
		let _ = writeln!(out, "| `{}` | `{}` | {} |", edge.above, edge.below, edge.carries);
	}

	let _ = writeln!(out, "\n## How somebody else's API reaches this stack\n");
	let _ = writeln!(out, "Frozen before any of them exists, because a provisional `gl*` or `vk*` API introduced to draw a demo");
	let _ = writeln!(out, "is the API the tree then has. Naming the routes first is what makes \"properly later\" a plan rather");
	let _ = writeln!(out, "than a hope.\n");
	let _ = writeln!(out, "| API | through | and NOT |");
	let _ = writeln!(out, "| --- | --- | --- |");
	for route in ROUTES {
		let _ = writeln!(out, "| {} | {} | {} |", route.api, route.through, route.refused);
	}

	let _ = writeln!(out, "\n## Where untrusted input is validated\n");
	let _ = writeln!(out, "The point of naming a boundary is that the layer below may then ASSUME. A stack where every layer");
	let _ = writeln!(out, "re-checks is a stack where the check that matters is the one nobody wrote because everybody assumed");
	let _ = writeln!(out, "somebody else had; a stack where none does is the other failure. Each row is a place where the check");
	let _ = writeln!(out, "happens, and a statement that it does not happen again deeper.\n");
	let _ = writeln!(out, "| boundary | what arrives untrusted | what is checked |");
	let _ = writeln!(out, "| --- | --- | --- |");
	for boundary in BOUNDARIES {
		let _ = writeln!(out, "| {} | {} | {} |", boundary.at, boundary.untrusted, boundary.checks);
	}
	let _ = writeln!(out, "\nThe image model, the colour model, the formats and every numeric rule they need are in");
	let _ = writeln!(out, "[`graphics/IMAGE_COLOR_PROFILE_1.md`](graphics/IMAGE_COLOR_PROFILE_1.md).\n");

	// THE PROFILES, AND WHAT THEIR HASHES ARE HASHES OF. Written once, here, because it is one rule
	// for every profile and a copy in each document would be several rules the moment one was
	// corrected.
	let _ = writeln!(out, "## The profiles\n");
	let _ = writeln!(out, "Each profile is a machine-readable registry with a document generated from it and a SHA-256 over");
	let _ = writeln!(out, "its canonical form. `docs/gen/profiles.manifest` binds the three together - name, version, hash,");
	let _ = writeln!(out, "canonical file and document - and `./gen.sh --check` refuses any of them that disagrees.\n");
	let _ = writeln!(out, "| profile | document |");
	let _ = writeln!(out, "| --- | --- |");
	for (name, path) in [
		("Image Colour Profile 1", "graphics/IMAGE_COLOR_PROFILE_1.md"),
		("Render2D Profile 1", "graphics/RENDER2D_PROFILE_1.md"),
		("Render3D Profile 1", "graphics/RENDER3D_PROFILE_1.md"),
		("Shader IR 1", "graphics/SHADER_IR_1.md"),
		("Scene3D Core Profile 1", "graphics/SCENE3D_PROFILE_1.md"),
		("Scene3D Extended 1", "graphics/SCENE3D_EXTENDED_1.md"),
		("WSI Profile 1", "graphics/WSI_PROFILE_1.md"),
	] {
		let _ = writeln!(out, "| {name} | [`{path}`]({path}) |");
	}
	let _ = writeln!(out, "\n### How a profile is hashed\n");
	let _ = writeln!(out, "| question | answer |");
	let _ = writeln!(out, "| --- | --- |");
	for rule in graphics_profile::hashing::CANONICAL_ENCODING {
		let _ = writeln!(out, "| {} | {} |", rule.question, rule.answer);
	}
	out
}
