//! The OpenType profile's document, generated from the profile it IS.
//!
//! THE SAME ARRANGEMENT AS THE GRAPHICS PROFILES, for the same reason: a profile that exists only as
//! prose drifts away from the parser and the conformance corpus the first time somebody adds a table
//! in one place. The list is an enumeration, the document is written from it, and the hash over the
//! canonical form is what turns a change from something a reviewer might notice into a line in a
//! diff.
//!
//! IT IS A SEPARATE DOCUMENT FROM THE GRAPHICS ONES because it answers a different question - what a
//! FONT may contain, rather than what a BACKEND must draw - and because the checks over it are
//! different: there is no backend handler for `HVAR`.

use std::fmt::Write as _;

use opentype_profile::{colour, layout, limits, scripts, tables, variations};

/// The canonical machine-readable form the hash is taken over.
///
/// ONE LINE PER ENTRY, IN PROFILE ORDER. Order is part of it: a reordering is a different document,
/// and a hash that ignored order would call two different tables the same profile.
pub fn canonical() -> String {
	let mut out = String::new();
	let _ = writeln!(out, "profile=opentype version={}", opentype_profile::PROFILE_VERSION);
	for table in tables::TABLES {
		let versions: Vec<String> = table.majors.iter().map(|major| major.to_string()).collect();
		let _ = writeln!(out, "table={} majors={}", table.tag.as_str(), if versions.is_empty() { String::from("any") } else { versions.join(",") });
	}
	for excluded in tables::EXCLUDED {
		let tags: Vec<&str> = excluded.tags.iter().map(|tag| core::str::from_utf8(tag).unwrap_or("????")).collect();
		let _ = writeln!(out, "excluded={} tags={}", excluded.what, if tags.is_empty() { String::from("-") } else { tags.join(",") });
	}
	for lookup in layout::GSUB_LOOKUPS {
		let formats: Vec<String> = lookup.formats.iter().map(|format| format.to_string()).collect();
		let _ = writeln!(out, "gsub={} name={} formats={}", lookup.kind, lookup.name, formats.join(","));
	}
	for lookup in layout::GPOS_LOOKUPS {
		let formats: Vec<String> = lookup.formats.iter().map(|format| format.to_string()).collect();
		let _ = writeln!(out, "gpos={} name={} formats={}", lookup.kind, lookup.name, formats.join(","));
	}
	for flag in layout::LOOKUP_FLAGS {
		let _ = writeln!(out, "lookup-flag={:#06x} name={}", flag.bit, flag.name);
	}
	for format in layout::SUBTABLE_FORMATS {
		let _ = writeln!(out, "subtable={} format={}", format.structure, format.format);
	}
	for mechanism in layout::CONDITIONAL_MECHANISMS {
		let _ = writeln!(out, "conditional={} format={}", mechanism.structure, mechanism.format);
	}
	for mechanism in variations::MECHANISMS {
		let _ = writeln!(out, "variation={}", mechanism.name);
	}
	for paint in colour::PAINTS {
		let _ = writeln!(out, "paint={} name={} varies={}", paint.format, paint.name, paint.varies);
	}
	for mode in colour::COMPOSITE_MODES {
		let _ = writeln!(out, "composite={} name={}", mode.value, mode.name);
	}
	for format in colour::BITMAP_FORMATS {
		let _ = writeln!(out, "bitmap={} name={}", format.table, format.name);
	}
	for script in scripts::SCRIPTS {
		let _ = writeln!(out, "script={} name={} class={} rtl={}", core::str::from_utf8(&script.tag).unwrap_or("????"), script.name, script.class.name(), script.right_to_left);
	}
	for language in scripts::LANGUAGES {
		let _ = writeln!(out, "language={} name={}", core::str::from_utf8(&language.tag).unwrap_or("????"), language.name);
	}
	// THE CEILINGS ARE PART OF THE PROFILE AND THEREFORE PART OF THE HASH. A limit raised quietly is
	// exactly the change this hash exists to turn into a line in a diff.
	for limit in limits::LIMITS {
		let _ = writeln!(out, "limit={} value={} unit={} kind={}", limit.name, limit.value, limit.unit, limit.kind.name());
	}
	out
}

/// The document a person reads.
pub fn document(hash: &str) -> String {
	let mut out = String::from("<!-- @generated by profile-doc from the opentype profile. Do not edit; run `./gen.sh`. -->\n");
	let _ = writeln!(out, "# OpenType Profile {}\n", opentype_profile::PROFILE_VERSION);
	let _ = writeln!(out, "Profile hash: `{hash}`\n");
	let _ = writeln!(out, "What this system's font parser reads, and what it REFUSES. Anything outside this document is a");
	let _ = writeln!(out, "typed `Unsupported` refusal naming what was outside it - not undefined behaviour, not a silent");
	let _ = writeln!(out, "wrong result, and not a best effort. A font is untrusted content that arrives from a document, a");
	let _ = writeln!(out, "download or a package.\n");

	let _ = writeln!(out, "## Tables\n");
	let _ = writeln!(out, "A table at a major version this list does not carry is refused: a layout this parser has never");
	let _ = writeln!(out, "seen is one it would be guessing at. `any` means the table has no version field of its own.\n");
	let _ = writeln!(out, "| table | versions | why |");
	let _ = writeln!(out, "| --- | --- | --- |");
	for table in tables::TABLES {
		let versions: Vec<String> = table.majors.iter().map(|major| major.to_string()).collect();
		let _ = writeln!(out, "| `{}` | {} | {} |", table.tag.as_str(), if versions.is_empty() { String::from("any") } else { versions.join(", ") }, table.reason);
	}

	let _ = writeln!(out, "\n## Excluded, by name\n");
	let _ = writeln!(out, "A reader cannot tell a deliberate omission from a forgotten one by looking at a list of what IS");
	let _ = writeln!(out, "supported, so the omissions are listed too.\n");
	let _ = writeln!(out, "| excluded | tables | why |");
	let _ = writeln!(out, "| --- | --- | --- |");
	for excluded in tables::EXCLUDED {
		let tags: Vec<String> = excluded.tags.iter().map(|tag| format!("`{}`", core::str::from_utf8(tag).unwrap_or("????"))).collect();
		let _ = writeln!(out, "| {} | {} | {} |", excluded.what, if tags.is_empty() { String::from("-") } else { tags.join(", ") }, excluded.reason);
	}

	let _ = writeln!(out, "\n## Numeric ceilings\n");
	let _ = writeln!(out, "Checked offsets stop a crafted font reading somebody else's memory. They stop none of the other");
	let _ = writeln!(out, "thing a font can do: a STRUCTURALLY VALID face can ask for work that exhausts time, stack or the");
	let _ = writeln!(out, "caller's memory, and none of it is a parse error at any single read. Exceeding a ceiling is a");
	let _ = writeln!(out, "typed refusal naming which one and by how much - never a truncation, which is a document silently");
	let _ = writeln!(out, "rendered wrong.\n");
	let _ = writeln!(out, "An `internal` ceiling is a property of the face; a `proportional` one caps a multiplier and not a");
	let _ = writeln!(out, "product; an `absolute` one caps a document, and is what makes the proportional ones bound anything");
	let _ = writeln!(out, "at all. The proportional rules continue to apply INSIDE the absolute ones rather than being");
	let _ = writeln!(out, "replaced by them.\n");
	let _ = writeln!(out, "| ceiling | value | unit | kind | why |");
	let _ = writeln!(out, "| --- | ---: | --- | --- | --- |");
	for limit in limits::LIMITS {
		let _ = writeln!(out, "| {} | {} | {} | {} | {} |", limit.name, limit.value, limit.unit, limit.kind.name(), limit.why);
	}

	let _ = writeln!(out, "\n## Shaping: `GSUB`\n");
	let _ = writeln!(out, "| type | name | subtable formats |");
	let _ = writeln!(out, "| ---: | --- | --- |");
	for lookup in layout::GSUB_LOOKUPS {
		let formats: Vec<String> = lookup.formats.iter().map(|format| format.to_string()).collect();
		let _ = writeln!(out, "| {} | {} | {} |", lookup.kind, lookup.name, formats.join(", "));
	}
	let _ = writeln!(out, "\n## Shaping: `GPOS`\n");
	let _ = writeln!(out, "| type | name | subtable formats |");
	let _ = writeln!(out, "| ---: | --- | --- |");
	for lookup in layout::GPOS_LOOKUPS {
		let formats: Vec<String> = lookup.formats.iter().map(|format| format.to_string()).collect();
		let _ = writeln!(out, "| {} | {} | {} |", lookup.kind, lookup.name, formats.join(", "));
	}
	let _ = writeln!(out, "\n## Lookup flags\n");
	let _ = writeln!(out, "| flag | name | effect |");
	let _ = writeln!(out, "| --- | --- | --- |");
	for flag in layout::LOOKUP_FLAGS {
		let _ = writeln!(out, "| `{:#06x}` | `{}` | {} |", flag.bit, flag.name, flag.effect);
	}
	let _ = writeln!(out, "\n## Shared structures, and the conditional mechanisms\n");
	let _ = writeln!(out, "| structure | format | what |");
	let _ = writeln!(out, "| --- | ---: | --- |");
	for format in layout::SUBTABLE_FORMATS.iter().chain(layout::CONDITIONAL_MECHANISMS.iter()) {
		let _ = writeln!(out, "| `{}` | {} | {} |", format.structure, format.format, format.what);
	}

	let _ = writeln!(out, "\n## Variation\n");
	let _ = writeln!(out, "Named as MECHANISMS rather than as tables: `fvar` and `gvar` make an outline vary and do nothing");
	let _ = writeln!(out, "for a metric, so a font instanced without `HVAR` has correct outlines at the wrong advances.\n");
	let _ = writeln!(out, "| mechanism | what it varies, and what is wrong without it |");
	let _ = writeln!(out, "| --- | --- |");
	for mechanism in variations::MECHANISMS {
		let _ = writeln!(out, "| {} | {} |", mechanism.name, mechanism.what);
	}

	let _ = writeln!(out, "\n## Colour: the `COLR` v1 paint graph\n");
	let _ = writeln!(out, "A variable counterpart at `format + 1` is admitted with its paint, where the format has one.\n");
	let _ = writeln!(out, "| format | paint | varies | what |");
	let _ = writeln!(out, "| ---: | --- | --- | --- |");
	for paint in colour::PAINTS {
		let _ = writeln!(out, "| {} | `{}` | {} | {} |", paint.format, paint.name, if paint.varies { "yes" } else { "no" }, paint.what);
	}
	let _ = writeln!(out, "\n{} composite modes: ", colour::COMPOSITE_MODES.len());
	let modes: Vec<String> = colour::COMPOSITE_MODES.iter().map(|mode| format!("`{}`", mode.name)).collect();
	let _ = writeln!(out, "{}.\n", modes.join(", "));
	let _ = writeln!(out, "| bitmap | format | what |");
	let _ = writeln!(out, "| --- | --- | --- |");
	for format in colour::BITMAP_FORMATS {
		let _ = writeln!(out, "| `{}` | {} | {} |", format.table, format.name, format.what);
	}

	let _ = writeln!(out, "\n## Scripts\n");
	let _ = writeln!(out, "\"Indic\" is not a profile entry. Each script is named, with the shaping CLASS it needs - which is");
	let _ = writeln!(out, "what makes \"supports Tamil\" a claim anybody can check. A script outside this list is a typed");
	let _ = writeln!(out, "refusal: the text is reported as unshapeable rather than rendered with rules nothing applied.\n");
	let _ = writeln!(out, "| tag | script | shaping class | direction |");
	let _ = writeln!(out, "| --- | --- | --- | --- |");
	for script in scripts::SCRIPTS {
		let _ = writeln!(out, "| `{}` | {} | {} | {} |", core::str::from_utf8(&script.tag).unwrap_or("????"), script.name, script.class.name(), if script.right_to_left { "right to left" } else { "left to right" });
	}

	let _ = writeln!(out, "\n## Languages\n");
	let _ = writeln!(out, "A language is here because it CHANGES something, and what it changes is written down. An unknown");
	let _ = writeln!(out, "`LangSys` falls back to `dflt` rather than refusing - the one fallback in this profile, and what");
	let _ = writeln!(out, "the format itself does.\n");
	let _ = writeln!(out, "| tag | language | what selecting it changes |");
	let _ = writeln!(out, "| --- | --- | --- |");
	for language in scripts::LANGUAGES {
		let _ = writeln!(out, "| `{}` | {} | {} |", core::str::from_utf8(&language.tag).unwrap_or("????"), language.name, language.effect);
	}
	out
}
