//! `RENDER3D_PROFILE_1.md`, generated from the registries that specify it.
//!
//! THE FEATURE LIST IS NOT THE SPECIFICATION. `Render3D Core Profile 1`'s enumeration says what a
//! backend must be able to do; this document says what the answers ARE - the sample positions, the
//! LOD formula, what a floating-point depth comparison compares, which vertex a flat attribute comes
//! from after a clip. Two backends can implement every feature in the list and produce different
//! images, and every difference they could produce is a question below.

use std::fmt::Write as _;

use graphics_profile::render3d_spec::{CLIP_COORD_Q, CLIP_PLANE_ORDER, CLIP_ROUNDING, CLIP_VOLUME, CLIP_W_EPSILON, COLOUR_FORMATS, DEPTH_BIAS_EQUATION, DEPTH_FORMATS, DEPTH_RULES, DEPTH32F_ANSWER, FORMAT_EXCEPTIONS, HAZARD_RULES, LOD_FORMULA, MSAA_2X, MSAA_4X, MSAA_RULES, PROVOKING_VERTEX, QUALIFIERS, RASTERISER_STATE, RENDER3D_PROFILE_1_MIN_LIMITS, SAMPLER_RULES, SUBMISSION_RULES, VERTEX_FORMATS, VERTEX_NORMALISATION};

/// The canonical machine-readable form the hash is taken over.
pub fn canonical() -> String {
	let mut out = String::new();
	let _ = writeln!(out, "profile=render3d-spec version=1");
	let _ = writeln!(out, "clip-volume={CLIP_VOLUME}");
	let _ = writeln!(out, "clip-w-epsilon={CLIP_W_EPSILON:.12}");
	let _ = writeln!(out, "clip-plane-order={}", CLIP_PLANE_ORDER.join(","));
	for rule in CLIP_COORD_Q {
		let _ = writeln!(out, "clip-coord-q={} answer={}", rule.question, rule.answer);
	}
	for qualifier in QUALIFIERS {
		let _ = writeln!(out, "qualifier={} across={} at-clip={} why={}", qualifier.name, qualifier.across_the_primitive, qualifier.at_a_clip_intersection, qualifier.why);
	}
	for rule in PROVOKING_VERTEX {
		let _ = writeln!(out, "provoking={} answer={}", rule.question, rule.answer);
	}
	let _ = writeln!(out, "clip-rounding={CLIP_ROUNDING}");
	for format in COLOUR_FORMATS {
		let _ = writeln!(out, "colour-format={} full={} bits={} sampled={} filterable={} renderable={} blendable={} msaa={} vertex={} readback={} attachment={}", format.name, format.full_name, format.bits_per_texel, format.sampled, format.filterable, format.renderable, format.blendable, format.msaa, format.vertex, format.readback, format.attachment);
	}
	for rule in FORMAT_EXCEPTIONS {
		let _ = writeln!(out, "format-exception={} answer={}", rule.question, rule.answer);
	}
	for format in VERTEX_FORMATS {
		let _ = writeln!(out, "vertex-format={} full={} bytes={} shader={}", format.name, format.full_name, format.bytes, format.shader_type);
	}
	for rule in VERTEX_NORMALISATION {
		let _ = writeln!(out, "vertex-normalisation={} answer={}", rule.question, rule.answer);
	}
	for field in RASTERISER_STATE {
		let _ = writeln!(out, "rasteriser={} values={} default={} why={}", field.name, field.values, field.default, field.why);
	}
	let _ = writeln!(out, "depth-bias={DEPTH_BIAS_EQUATION}");
	for sample in MSAA_2X {
		let _ = writeln!(out, "msaa2x={} x={:.4} y={:.4}", sample.index, sample.x, sample.y);
	}
	for sample in MSAA_4X {
		let _ = writeln!(out, "msaa4x={} x={:.4} y={:.4}", sample.index, sample.x, sample.y);
	}
	for rule in MSAA_RULES {
		let _ = writeln!(out, "msaa={} answer={}", rule.question, rule.answer);
	}
	for format in DEPTH_FORMATS {
		let _ = writeln!(out, "depth-format={} full={} storage={} range={} comparison={}", format.name, format.full_name, format.storage, format.stored_range, format.comparison);
	}
	let _ = writeln!(out, "depth32f={DEPTH32F_ANSWER}");
	for rule in DEPTH_RULES {
		let _ = writeln!(out, "depth={} answer={}", rule.question, rule.answer);
	}
	let _ = writeln!(out, "lod={LOD_FORMULA}");
	for rule in SAMPLER_RULES {
		let _ = writeln!(out, "sampler={} answer={}", rule.question, rule.answer);
	}
	for rule in HAZARD_RULES {
		let _ = writeln!(out, "hazard={} answer={}", rule.question, rule.answer);
	}
	for rule in SUBMISSION_RULES {
		let _ = writeln!(out, "submission={} answer={}", rule.question, rule.answer);
	}
	for limit in RENDER3D_PROFILE_1_MIN_LIMITS {
		let _ = writeln!(out, "min-limit={} minimum={} why={}", limit.name, limit.minimum, limit.why);
	}
	out.push_str(&crate::thresholds::canonical_for("render3d", true));
	out
}

/// The document a person reads.
pub fn document(hash: &str) -> String {
	let mut out = String::from("<!-- @generated by profile-doc from the Render3D specification registries. Do not edit; run `./gen.sh`. -->\n");
	let _ = writeln!(out, "# Render3D Profile 1: the numbers and the rules\n");
	let _ = writeln!(out, "Specification hash: `{hash}`\n");
	let _ = writeln!(out, "`Render3D Core Profile 1`'s feature list says what a backend must be able to do. This document says");
	let _ = writeln!(out, "what the answers are. Two backends can implement every feature in that list and produce different");
	let _ = writeln!(out, "images; every difference they could produce is a question answered here.\n");

	let _ = writeln!(out, "## Conventions\n");
	let _ = writeln!(out, "| convention | value |");
	let _ = writeln!(out, "| --- | --- |");
	let _ = writeln!(out, "| clip volume | `{CLIP_VOLUME}` |");
	let _ = writeln!(out, "| clip plane order | {} |", CLIP_PLANE_ORDER.join(", then "));
	let _ = writeln!(out, "| horizon epsilon | {CLIP_W_EPSILON} (the same value the 2D profile uses) |");
	let _ = writeln!(out, "| NDC y direction | down, matching the 2D device space and the scanout's row order |");
	let _ = writeln!(out, "| front face | counter-clockwise in NDC |");
	let _ = writeln!(out, "| pixel centres | half-integers, as in the 2D profile |\n");

	let _ = writeln!(out, "## `ClipCoordQ`\n");
	let _ = writeln!(out, "| question | answer |");
	let _ = writeln!(out, "| --- | --- |");
	for rule in CLIP_COORD_Q {
		let _ = writeln!(out, "| {} | {} |", rule.question, rule.answer);
	}
	let _ = writeln!(out);

	let _ = writeln!(out, "## Interpolation qualifiers, and what clipping does to them\n");
	let _ = writeln!(out, "| qualifier | across the primitive | at a clip intersection | why |");
	let _ = writeln!(out, "| --- | --- | --- | --- |");
	for qualifier in QUALIFIERS {
		let _ = writeln!(out, "| `{}` | {} | {} | {} |", qualifier.name, qualifier.across_the_primitive, qualifier.at_a_clip_intersection, qualifier.why);
	}
	let _ = writeln!(out);
	let _ = writeln!(out, "Rounding: {CLIP_ROUNDING}\n");

	let _ = writeln!(out, "### The provoking vertex\n");
	let _ = writeln!(out, "| topology | which vertex |");
	let _ = writeln!(out, "| --- | --- |");
	for rule in PROVOKING_VERTEX {
		let _ = writeln!(out, "| {} | {} |", rule.question, rule.answer);
	}
	let _ = writeln!(out);

	let _ = writeln!(out, "## Colour formats\n");
	let _ = writeln!(out, "| format | full name | bits | sampled | filterable | renderable | blendable | MSAA | vertex | readback | attachment |");
	let _ = writeln!(out, "| --- | --- | ---: | :-: | :-: | :-: | :-: | :-: | :-: | :-: | :-: |");
	for format in COLOUR_FORMATS {
		let _ = writeln!(out, "| `{}` | {} | {} | {} | {} | {} | {} | {} | {} | {} | {} |", format.name, format.full_name, format.bits_per_texel, yes(format.sampled), yes(format.filterable), yes(format.renderable), yes(format.blendable), yes(format.msaa), yes(format.vertex), yes(format.readback), yes(format.attachment));
	}
	let _ = writeln!(out);
	for rule in FORMAT_EXCEPTIONS {
		let _ = writeln!(out, "- **{}**: {}", rule.question, rule.answer);
	}
	let _ = writeln!(out);

	let _ = writeln!(out, "## Vertex formats\n");
	let _ = writeln!(out, "| format | full name | bytes | shader type |");
	let _ = writeln!(out, "| --- | --- | ---: | --- |");
	for format in VERTEX_FORMATS {
		let _ = writeln!(out, "| `{}` | {} | {} | `{}` |", format.name, format.full_name, format.bytes, format.shader_type);
	}
	let _ = writeln!(out);
	for rule in VERTEX_NORMALISATION {
		let _ = writeln!(out, "- **{}**: {}", rule.question, rule.answer);
	}
	let _ = writeln!(out);

	let _ = writeln!(out, "## Rasteriser state\n");
	let _ = writeln!(out, "| state | values | default | why |");
	let _ = writeln!(out, "| --- | --- | --- | --- |");
	for field in RASTERISER_STATE {
		let _ = writeln!(out, "| {} | {} | `{}` | {} |", field.name, field.values, field.default, field.why);
	}
	let _ = writeln!(out);
	let _ = writeln!(out, "Depth bias: {DEPTH_BIAS_EQUATION}\n");

	let _ = writeln!(out, "## Multisampling\n");
	let _ = writeln!(out, "Positions are in the pixel's own [0, 1] space with the origin at its top-left corner.\n");
	let _ = writeln!(out, "| count | sample | x | y |");
	let _ = writeln!(out, "| --- | ---: | ---: | ---: |");
	for sample in MSAA_2X {
		let _ = writeln!(out, "| 2x | {} | {} | {} |", sample.index, sample.x, sample.y);
	}
	for sample in MSAA_4X {
		let _ = writeln!(out, "| 4x | {} | {} | {} |", sample.index, sample.x, sample.y);
	}
	let _ = writeln!(out);
	let _ = writeln!(out, "| question | answer |");
	let _ = writeln!(out, "| --- | --- |");
	for rule in MSAA_RULES {
		let _ = writeln!(out, "| {} | {} |", rule.question, rule.answer);
	}
	let _ = writeln!(out);

	let _ = writeln!(out, "## Depth and stencil\n");
	let _ = writeln!(out, "| format | full name | storage | stored range | comparison |");
	let _ = writeln!(out, "| --- | --- | --- | --- | --- |");
	for format in DEPTH_FORMATS {
		let _ = writeln!(out, "| `{}` | {} | {} | {} | {} |", format.name, format.full_name, format.storage, format.stored_range, format.comparison);
	}
	let _ = writeln!(out);
	let _ = writeln!(out, "### The `Depth32F` question\n");
	let _ = writeln!(out, "{DEPTH32F_ANSWER}\n");
	let _ = writeln!(out, "| question | answer |");
	let _ = writeln!(out, "| --- | --- |");
	for rule in DEPTH_RULES {
		let _ = writeln!(out, "| {} | {} |", rule.question, rule.answer);
	}
	let _ = writeln!(out);

	let _ = writeln!(out, "## Sampling\n");
	let _ = writeln!(out, "LOD: {LOD_FORMULA}\n");
	let _ = writeln!(out, "| question | answer |");
	let _ = writeln!(out, "| --- | --- |");
	for rule in SAMPLER_RULES {
		let _ = writeln!(out, "| {} | {} |", rule.question, rule.answer);
	}
	let _ = writeln!(out);

	let _ = writeln!(out, "## Resource hazards\n");
	let _ = writeln!(out, "| question | answer |");
	let _ = writeln!(out, "| --- | --- |");
	for rule in HAZARD_RULES {
		let _ = writeln!(out, "| {} | {} |", rule.question, rule.answer);
	}
	let _ = writeln!(out);

	let _ = writeln!(out, "## Submission and readback\n");
	let _ = writeln!(out, "| question | answer |");
	let _ = writeln!(out, "| --- | --- |");
	for rule in SUBMISSION_RULES {
		let _ = writeln!(out, "| {} | {} |", rule.question, rule.answer);
	}
	let _ = writeln!(out);

	let _ = writeln!(out, "## Guaranteed minimum limits\n");
	let _ = writeln!(out, "An implementation-defined limit without a floor lets a backend pass every other rule in this");
	let _ = writeln!(out, "document while being useless. The conformance suite runs against these minima rather than against");
	let _ = writeln!(out, "whatever a backend happens to offer.\n");
	let _ = writeln!(out, "| limit | minimum | why |");
	let _ = writeln!(out, "| --- | ---: | --- |");
	for limit in RENDER3D_PROFILE_1_MIN_LIMITS {
		let _ = writeln!(out, "| `{}` | {} | {} |", limit.name, limit.minimum, limit.why);
	}
	out.push_str(&crate::thresholds::chapter("render3d", true));
	out
}

fn yes(value: bool) -> &'static str {
	if value { "yes" } else { "no" }
}
