//! `RENDER2D_PROFILE_1.md`, generated from the registries it specifies.
//!
//! THE FEATURE LIST ALONE IS NOT A PROFILE. `docs/gen/render2d/profile-1.md` names every entry the
//! profile carries; this document says what each of them MEANS numerically - the equation for every
//! operator and blend mode, the tolerances as numbers, and the contracts a recording API has that a
//! drawing API does not. Two implementations that agree on the first and not the second produce
//! different pixels from the same list.

use std::fmt::Write as _;

use graphics_profile::compositing::{BLENDS, COMPOSITING_EQUATION, NON_SEPARABLE_BLENDS, OPERATORS, lcd, model};
use graphics_profile::contracts::{CONTENT_REFRESH, ON_MISMATCH, PREPARED_DEPENDENCIES, builder, filter};
use graphics_profile::geometry::{AT_MAX_DEPTH, BOOLEAN_RULES, COINCIDENCE_EPSILON_PIXELS, FLATTENING_TOLERANCE_PIXELS, HORIZON_RULE, MAX_SUBDIVISION_DEPTH, PROJECTIVE_W_EPSILON};
use graphics_profile::{RENDER2D_CORE_PROFILE_1, RENDER2D_PROFILE_1_MINIMA};

/// The canonical machine-readable form the hash is taken over.
pub fn canonical() -> String {
	let mut out = String::new();
	let _ = writeln!(out, "profile=render2d-spec version=1");
	let _ = writeln!(out, "compositing-equation={COMPOSITING_EQUATION}");
	for operator in OPERATORS {
		let _ = writeln!(out, "operator={} fa={} fb={}", operator.name, operator.source_factor, operator.backdrop_factor);
	}
	for blend in BLENDS {
		let _ = writeln!(out, "blend={} b={}", blend.name, blend.equation);
	}
	for blend in NON_SEPARABLE_BLENDS {
		let _ = writeln!(out, "non-separable={} b={}", blend.name, blend.equation);
	}
	let (red, green, blue) = model::LUMINANCE_COEFFICIENTS;
	let _ = writeln!(out, "model luminance={red},{green},{blue} saturation={} set-luminance={} set-saturation={} clip={}", model::SATURATION, model::SET_LUMINANCE, model::SET_SATURATION, model::CLIP_COLOR);
	let taps: Vec<String> = lcd::FILTER_NINTHS.iter().map(|tap| tap.to_string()).collect();
	let _ = writeln!(out, "lcd filter-ninths={} coverage-gamma={}", taps.join(","), lcd::COVERAGE_GAMMA);
	let _ = writeln!(out, "flattening tolerance-pixels={FLATTENING_TOLERANCE_PIXELS} max-depth={MAX_SUBDIVISION_DEPTH} at-max-depth={AT_MAX_DEPTH}");
	let _ = writeln!(out, "projective w-epsilon={PROJECTIVE_W_EPSILON} horizon={HORIZON_RULE}");
	let _ = writeln!(out, "coincidence-epsilon-pixels={COINCIDENCE_EPSILON_PIXELS}");
	for rule in BOOLEAN_RULES {
		let _ = writeln!(out, "boolean={} answer={}", rule.question, rule.answer);
	}
	for dependency in PREPARED_DEPENDENCIES {
		let _ = writeln!(out, "prepared-dependency={} why={}", dependency.name, dependency.why);
	}
	let _ = writeln!(out, "prepared on-mismatch={ON_MISMATCH} content-refresh={CONTENT_REFRESH}");
	let _ = writeln!(out, "builder within={} beyond={} snapshots={} scratch={}", builder::WITHIN_RESERVATION, builder::BEYOND_RESERVATION, builder::SNAPSHOTS, builder::SCRATCH_REUSE);
	let _ = writeln!(out, "filter shape={} bounds={} working={} edge={} scratch={}", filter::SHAPE, filter::BOUNDS_MAP, filter::WORKING_FORMAT, filter::EDGE_MODE, filter::SCRATCH);
	let minima = RENDER2D_PROFILE_1_MINIMA;
	let _ = writeln!(out, "minima commands={} resources={} path-verbs={} path-points={} subpaths={} clip-depth={} layer-depth={} filter-nodes={} filter-radius={} glyphs-per-run={} image-extent={} layer-pixels={} prepared-scratch={} cache={} display-list={}", minima.max_commands, minima.max_resources, minima.max_path_verbs, minima.max_path_points, minima.max_subpaths, minima.max_clip_depth, minima.max_layer_depth, minima.max_filter_nodes, minima.max_filter_radius, minima.max_glyphs_per_run, minima.max_image_extent, minima.max_layer_pixels, minima.max_prepared_scratch_bytes, minima.max_cache_bytes, minima.max_display_list_bytes);
	let _ = writeln!(out, "features={}", RENDER2D_CORE_PROFILE_1.len());
	out
}

/// The document a person reads.
pub fn document(hash: &str) -> String {
	let mut out = String::from("<!-- @generated by profile-doc from the render2d specification registries. Do not edit; run `./gen.sh`. -->\n");
	let _ = writeln!(out, "# Render2D Core Profile 1: the normative specification\n");
	let _ = writeln!(out, "Specification hash: `{hash}`\n");
	let _ = writeln!(out, "The feature LIST is [`gen/render2d/profile-1.md`](gen/render2d/profile-1.md), which names every entry");
	let _ = writeln!(out, "the profile carries. This document says what each of them MEANS numerically. Two implementations that");
	let _ = writeln!(out, "agree on the list and not on the numbers produce different pixels from the same draw list, which is");
	let _ = writeln!(out, "what a conformance suite exists to catch and what this document exists to prevent.\n");
	let _ = writeln!(out, "Everything below composites PREMULTIPLIED and LINEAR, in the canonical intermediate named by");
	let _ = writeln!(out, "[`IMAGE_COLOR_PROFILE_1.md`](IMAGE_COLOR_PROFILE_1.md). Compositing in an encoded space makes a");
	let _ = writeln!(out, "half-transparent black edge look grey instead of dark, and it is invisible until two implementations");
	let _ = writeln!(out, "are compared side by side.\n");

	let _ = writeln!(out, "## Compositing operators\n");
	let _ = writeln!(out, "The factors ARE the operator:\n");
	let _ = writeln!(out, "```text");
	let _ = writeln!(out, "{COMPOSITING_EQUATION}");
	let _ = writeln!(out, "```\n");
	let _ = writeln!(out, "| operator | Fa, on the source | Fb, on the backdrop |");
	let _ = writeln!(out, "| --- | --- | --- |");
	for operator in OPERATORS {
		let _ = writeln!(out, "| `{}` | `{}` | `{}` |", operator.name, operator.source_factor, operator.backdrop_factor);
	}
	let _ = writeln!(out, "\n`Plus` is not one of Porter and Duff's twelve and is here anyway: additive light is what a glow, a");
	let _ = writeln!(out, "highlight and an emissive overlay are, and an implementation without it grows a private one.\n");

	let _ = writeln!(out, "## Separable blend modes\n");
	let _ = writeln!(out, "`B(Cb, Cs)`, per channel, on UNPREMULTIPLIED values in `0..=1`.\n");
	let _ = writeln!(out, "| mode | equation |");
	let _ = writeln!(out, "| --- | --- |");
	for blend in BLENDS {
		let _ = writeln!(out, "| `{}` | `{}` |", blend.name, blend.equation);
	}
	let _ = writeln!(out, "\nThe two with a division have their ENDPOINTS stated rather than left to whatever the division");
	let _ = writeln!(out, "produces, and `SoftLight`'s `D(Cb)` is a piecewise function of the BACKDROP with its threshold on");
	let _ = writeln!(out, "the backdrop - which is the part that is got wrong.\n");

	let _ = writeln!(out, "## Non-separable blend modes\n");
	let _ = writeln!(out, "These mix the channels, so they need a colour model that the mode's name does not imply.\n");
	let _ = writeln!(out, "| mode | equation |");
	let _ = writeln!(out, "| --- | --- |");
	for blend in NON_SEPARABLE_BLENDS {
		let _ = writeln!(out, "| `{}` | `{}` |", blend.name, blend.equation);
	}
	let (red, green, blue) = model::LUMINANCE_COEFFICIENTS;
	let _ = writeln!(out, "\n```text");
	let _ = writeln!(out, "Lum(C)        = {red}*R + {green}*G + {blue}*B");
	let _ = writeln!(out, "Sat(C)        = {}", model::SATURATION);
	let _ = writeln!(out, "SetLum(C, l)  = {}", model::SET_LUMINANCE);
	let _ = writeln!(out, "SetSat(C, s)  = {}", model::SET_SATURATION);
	let _ = writeln!(out, "ClipColor(C)  = {}", model::CLIP_COLOR);
	let _ = writeln!(out, "```\n");
	let _ = writeln!(out, "`Lum`'s coefficients are the compositing specification's own fixed triple and stay fixed in every");
	let _ = writeln!(out, "colour space. That looks wrong and is right: using the destination space's luminance would make");
	let _ = writeln!(out, "`Luminosity` produce a different result for the same two colours depending on which space they were");
	let _ = writeln!(out, "tagged with, and the mode is defined as an operation on the numbers rather than on the light.\n");
	let _ = writeln!(out, "`ClipColor` is the step every implementation that omits it gets wrong on saturated colours: it");
	let _ = writeln!(out, "preserves luminance and reduces chroma, rather than clamping each channel.\n");

	let _ = writeln!(out, "## Subpixel text\n");
	let taps: Vec<String> = lcd::FILTER_NINTHS.iter().map(|tap| tap.to_string()).collect();
	let _ = writeln!(out, "The five-tap FIR across the subpixel triple is `[{}] / 9`. Without a filter, subpixel coverage", taps.join(", "));
	let _ = writeln!(out, "produces coloured fringes on every stem; with a different filter it produces different fringes.\n");
	let _ = writeln!(out, "Coverage is blended through gamma {}. Blending it linearly makes light-on-dark text look bolder", lcd::COVERAGE_GAMMA);
	let _ = writeln!(out, "than dark-on-light at the same weight, which is the artefact that gets reported as \"the font renders");
	let _ = writeln!(out, "too thin\" - and it is a gamma question rather than a font question.\n");

	let _ = writeln!(out, "## Geometry\n");
	let _ = writeln!(out, "| quantity | value |");
	let _ = writeln!(out, "| --- | --- |");
	let _ = writeln!(out, "| flattening tolerance | {FLATTENING_TOLERANCE_PIXELS} PHYSICAL pixels |");
	let _ = writeln!(out, "| maximum subdivision depth | {MAX_SUBDIVISION_DEPTH} |");
	let _ = writeln!(out, "| at the depth limit | {AT_MAX_DEPTH} |");
	let _ = writeln!(out, "| projective `w` epsilon | {PROJECTIVE_W_EPSILON} |");
	let _ = writeln!(out, "| the horizon rule | {HORIZON_RULE} |");
	let _ = writeln!(out, "| point coincidence | {COINCIDENCE_EPSILON_PIXELS} pixels |");
	let _ = writeln!(out, "\nONE tolerance, shared by fills, strokes, boolean operations, hit tests and bounds. If each flattened");
	let _ = writeln!(out, "to its own, a point would be inside a path for a hit test and outside it for the fill that drew it.");
	let _ = writeln!(out, "PHYSICAL pixels and not logical ones, because flattening in logical pixels makes a curve on a");
	let _ = writeln!(out, "two-times display twice as coarse as the same curve on a one-times display - visible as facets on");
	let _ = writeln!(out, "exactly the screens that show them best.\n");
	let _ = writeln!(out, "The coincidence epsilon is a SEPARATE and smaller number: the tolerance is how far a curve may");
	let _ = writeln!(out, "deviate from its flattening, and this is when two vertices are one. Using the tolerance for both");
	let _ = writeln!(out, "merges vertices a quarter of a pixel apart, which collapses thin features that were meant to be");
	let _ = writeln!(out, "there.\n");

	let _ = writeln!(out, "## Boolean operations: the answers\n");
	let _ = writeln!(out, "Two backends produce different unions if any of these is left open, and the difference is not");
	let _ = writeln!(out, "subtle: it is a hole that is there in one and not the other.\n");
	let _ = writeln!(out, "| question | answer |");
	let _ = writeln!(out, "| --- | --- |");
	for rule in BOOLEAN_RULES {
		let _ = writeln!(out, "| {} | {} |", rule.question, rule.answer);
	}

	let _ = writeln!(out, "\n## Filter graphs: the per-node contract\n");
	let _ = writeln!(out, "| rule | value |");
	let _ = writeln!(out, "| --- | --- |");
	for (name, value) in [
		("shape", filter::SHAPE),
		("bounds map", filter::BOUNDS_MAP),
		("working format", filter::WORKING_FORMAT),
		("edge mode", filter::EDGE_MODE),
		("scratch", filter::SCRATCH),
	] {
		let _ = writeln!(out, "| {name} | {value} |");
	}
	let _ = writeln!(out, "\nWithout the bounds map the whole graph has to be computed over the whole surface, because nothing can");
	let _ = writeln!(out, "say which part of the input a part of the output depends on - which is why a blur over a small dirty");
	let _ = writeln!(out, "region costs a full-screen blur in implementations that skipped it.\n");

	let _ = writeln!(out, "## Prepared lists\n");
	let _ = writeln!(out, "A prepared list is a CACHE, and a cache whose validity conditions are not enumerated eventually");
	let _ = writeln!(out, "replays a drawing that is not the one recorded. `is_compatible` checks these and nothing else.\n");
	let _ = writeln!(out, "| dependency | why a change invalidates |");
	let _ = writeln!(out, "| --- | --- |");
	for dependency in PREPARED_DEPENDENCIES {
		let _ = writeln!(out, "| {} | {} |", dependency.name, dependency.why);
	}
	let _ = writeln!(out, "\nOn a mismatch: {ON_MISMATCH}. Never a silent re-prepare - a caller replaying a list sixty times a");
	let _ = writeln!(out, "second and getting a full preparation each time has a performance bug it cannot see.\n");
	let _ = writeln!(out, "CONTENT IS NOT STRUCTURE: {CONTENT_REFRESH}.\n");

	let _ = writeln!(out, "## The reusable builder\n");
	let _ = writeln!(out, "| rule | value |");
	let _ = writeln!(out, "| --- | --- |");
	for (name, value) in [
		("re-recording within the reservation", builder::WITHIN_RESERVATION),
		("exceeding it", builder::BEYOND_RESERVATION),
		("snapshots", builder::SNAPSHOTS),
		("scratch on re-preparation", builder::SCRATCH_REUSE),
	] {
		let _ = writeln!(out, "| {name} | {value} |");
	}
	let _ = writeln!(out, "\nA transform, an opacity, a colour, a scroll offset and an image frame are what an animation changes");
	let _ = writeln!(out, "between frames; a builder that allocated for any of them would allocate sixty times a second forever.\n");

	let _ = writeln!(out, "## Guaranteed minima\n");
	let _ = writeln!(out, "A backend may raise any of them; none may be lowered. Without them \"supports Profile 1\" can mean");
	let _ = writeln!(out, "\"accepts ten path points\".\n");
	let minima = RENDER2D_PROFILE_1_MINIMA;
	let _ = writeln!(out, "| limit | minimum |");
	let _ = writeln!(out, "| --- | ---: |");
	for (name, value) in [
		("commands in one list", minima.max_commands as u64),
		("distinct resources", minima.max_resources as u64),
		("path verbs", minima.max_path_verbs as u64),
		("path points", minima.max_path_points as u64),
		("subpaths", minima.max_subpaths as u64),
		("clip depth", minima.max_clip_depth as u64),
		("layer depth", minima.max_layer_depth as u64),
		("filter nodes", minima.max_filter_nodes as u64),
		("filter radius, device pixels", minima.max_filter_radius as u64),
		("glyphs per run", minima.max_glyphs_per_run as u64),
		("image extent", minima.max_image_extent as u64),
		("layer pixels", minima.max_layer_pixels),
		("prepared scratch bytes", minima.max_prepared_scratch_bytes),
		("cache bytes", minima.max_cache_bytes),
		("display-list bytes", minima.max_display_list_bytes),
	] {
		let _ = writeln!(out, "| {name} | {value} |");
	}
	out
}
