//! `SCENE3D_PROFILE_1.md`, generated from the scene registries.
//!
//! A SCENE LAYER'S DECISIONS ARE VISIBLE. The order two transparent objects are drawn in, which of
//! two lights is applied first, whether a bounding sphere grows as its object rotates, and what a
//! pick answers where two objects meet - each is something an application can see, and each changes
//! when an implementation is optimised unless it is written down.

use std::fmt::Write as _;

use graphics_profile::scene3d::{CAMERA_RULES, CULLING_RULES, HIERARCHY_RULES, INSTANCING_RULES, LIGHTING_RULES, MATERIAL_RULES, MATERIALS, PICKING_RULES, QUEUE_RULES, QUEUES, SCENE3D_PROFILE_1_MIN_LIMITS};

/// The canonical machine-readable form the hash is taken over.
pub fn canonical() -> String {
	let mut out = String::new();
	let _ = writeln!(out, "profile=scene3d version=1");
	for (section, rules) in [
		("hierarchy", HIERARCHY_RULES),
		("camera", CAMERA_RULES),
		("queue", QUEUE_RULES),
		("culling", CULLING_RULES),
		("instancing", INSTANCING_RULES),
		("material", MATERIAL_RULES),
		("lighting", LIGHTING_RULES),
		("picking", PICKING_RULES),
	] {
		for rule in rules {
			let _ = writeln!(out, "{section}={} answer={}", rule.question, rule.answer);
		}
	}
	for queue in QUEUES {
		let _ = writeln!(out, "queue-definition={} contents={} order={} depth-write={}", queue.name, queue.contents, queue.order, queue.depth_write);
	}
	for material in MATERIALS {
		let _ = writeln!(out, "material={} inputs={} equation={}", material.name, material.inputs, material.equation);
	}
	for limit in SCENE3D_PROFILE_1_MIN_LIMITS {
		let _ = writeln!(out, "min-limit={} minimum={} why={}", limit.name, limit.minimum, limit.why);
	}
	out.push_str(&crate::thresholds::canonical_for("scene3d", false));
	out
}

/// The document a person reads.
pub fn document(hash: &str) -> String {
	let mut out = String::from("<!-- @generated by profile-doc from the Scene3D core registries. Do not edit; run `./gen.sh`. -->\n");
	let _ = writeln!(out, "# Scene3D Core Profile 1: the retained layer's contract\n");
	let _ = writeln!(out, "Specification hash: `{hash}`\n");
	let _ = writeln!(out, "`render3d` draws what it is told. A scene layer decides WHAT to tell it, and every decision it makes");
	let _ = writeln!(out, "is one an application can see. This document is those decisions.\n");
	let _ = writeln!(out, "Physically based materials, shadows, skinning, animation and post-processing are not here: they are");
	let _ = writeln!(out, "`Scene3D Extended 1`, a separate profile with a separate hash, so an implementation can conform to");
	let _ = writeln!(out, "this core without claiming them.\n");

	for (title, rules) in [
		("Nodes and hierarchy", HIERARCHY_RULES),
		("Camera and projection", CAMERA_RULES),
		("Culling", CULLING_RULES),
		("Instancing", INSTANCING_RULES),
		("Materials", MATERIAL_RULES),
		("Lighting", LIGHTING_RULES),
		("Picking and readback", PICKING_RULES),
	] {
		let _ = writeln!(out, "## {title}\n");
		let _ = writeln!(out, "| question | answer |");
		let _ = writeln!(out, "| --- | --- |");
		for rule in rules {
			let _ = writeln!(out, "| {} | {} |", rule.question, rule.answer);
		}
		let _ = writeln!(out);
	}

	let _ = writeln!(out, "## Render queues\n");
	let _ = writeln!(out, "| queue | contents | order | writes depth |");
	let _ = writeln!(out, "| --- | --- | --- | :-: |");
	for queue in QUEUES {
		let _ = writeln!(out, "| `{}` | {} | {} | {} |", queue.name, queue.contents, queue.order, if queue.depth_write { "yes" } else { "no" });
	}
	let _ = writeln!(out);
	let _ = writeln!(out, "| question | answer |");
	let _ = writeln!(out, "| --- | --- |");
	for rule in QUEUE_RULES {
		let _ = writeln!(out, "| {} | {} |", rule.question, rule.answer);
	}
	let _ = writeln!(out);

	let _ = writeln!(out, "## The core materials\n");
	let _ = writeln!(out, "| material | inputs | equation |");
	let _ = writeln!(out, "| --- | --- | --- |");
	for material in MATERIALS {
		let _ = writeln!(out, "| `{}` | {} | {} |", material.name, material.inputs, material.equation);
	}
	let _ = writeln!(out);

	let _ = writeln!(out, "## Guaranteed minimum limits\n");
	let _ = writeln!(out, "| limit | minimum | why |");
	let _ = writeln!(out, "| --- | ---: | --- |");
	for limit in SCENE3D_PROFILE_1_MIN_LIMITS {
		let _ = writeln!(out, "| `{}` | {} | {} |", limit.name, limit.minimum, limit.why);
	}
	out.push_str(&crate::thresholds::chapter("scene3d", false));
	out
}
