//! `SHADER_IR_1.md`, generated from the semantics registries.
//!
//! AN INSTRUCTION LIST IS NOT A SPECIFICATION. Two implementations that agree about every opcode
//! still disagree about integer overflow, division by zero, what an out-of-bounds read returns and
//! where a derivative comes from in a discarded lane. This document is those answers.

use std::fmt::Write as _;

use graphics_profile::shader_ir::{CONVERSION_RULES, ENCODING_RULES, MATRIX_LAYOUT, NUMERIC_RULES, SHADER_IR_VERSION, STAGE_RULES, STRICT_F32_RULES, TRANSCENDENTAL_ACCURACY, UNIFORM_LAYOUT};

/// The canonical machine-readable form the hash is taken over.
pub fn canonical() -> String {
	let mut out = String::new();
	let _ = writeln!(out, "profile=shader-ir version={SHADER_IR_VERSION}");
	for (section, rules) in [
		("numeric", NUMERIC_RULES),
		("conversion", CONVERSION_RULES),
		("uniform-layout", UNIFORM_LAYOUT),
		("matrix-layout", MATRIX_LAYOUT),
		("stage", STAGE_RULES),
		("strict-f32", STRICT_F32_RULES),
		("encoding", ENCODING_RULES),
	] {
		for rule in rules {
			let _ = writeln!(out, "{section}={} answer={}", rule.question, rule.answer);
		}
	}
	for accuracy in TRANSCENDENTAL_ACCURACY {
		let _ = writeln!(out, "accuracy={} max-ulp={} domain={}", accuracy.operation, accuracy.max_ulp, accuracy.domain);
	}
	out
}

/// The document a person reads.
pub fn document(hash: &str) -> String {
	let mut out = String::from("<!-- @generated by profile-doc from the shader-IR semantics registries. Do not edit; run `./gen.sh`. -->\n");
	let _ = writeln!(out, "# Shader IR {SHADER_IR_VERSION}: what a shader means\n");
	let _ = writeln!(out, "Specification hash: `{hash}`\n");
	let _ = writeln!(out, "A list of operations is not a specification. Two implementations that agree about every opcode still");
	let _ = writeln!(out, "disagree about what happens when an integer overflows, what a division by zero produces, what an");
	let _ = writeln!(out, "out-of-bounds array read returns and where a derivative comes from in a lane that was discarded.");
	let _ = writeln!(out, "Every one of those has been a shipping graphics bug. This document answers them.\n");
	let _ = writeln!(out, "## Two arithmetics\n");
	let _ = writeln!(out, "Anything a vertex POSITION depends on is StrictF32. Fragment arithmetic that reaches only a colour is");
	let _ = writeln!(out, "relaxed within the accuracy bounds below. This is not a quality setting: the first is what makes two");
	let _ = writeln!(out, "backends agree about where a triangle is, and the second is what makes a shader affordable.\n");

	for (title, rules) in [
		("Numbers", NUMERIC_RULES),
		("Conversions", CONVERSION_RULES),
		("StrictF32", STRICT_F32_RULES),
		("Stages, derivatives and sampling", STAGE_RULES),
		("Uniform block layout", UNIFORM_LAYOUT),
		("Matrix layout", MATRIX_LAYOUT),
		("The serialised form", ENCODING_RULES),
	] {
		let _ = writeln!(out, "## {title}\n");
		let _ = writeln!(out, "| question | answer |");
		let _ = writeln!(out, "| --- | --- |");
		for rule in rules {
			let _ = writeln!(out, "| {} | {} |", rule.question, rule.answer);
		}
		let _ = writeln!(out);
	}

	let _ = writeln!(out, "## Transcendental accuracy\n");
	let _ = writeln!(out, "An accuracy bound is part of the contract and not a quality of implementation. Without one a");
	let _ = writeln!(out, "conformance suite either demands bit-exactness, which no two backends achieve for a sine, or demands");
	let _ = writeln!(out, "nothing, which is what lets a backend ship a four-term approximation.\n");
	let _ = writeln!(out, "| operation | maximum error (ULP) | domain |");
	let _ = writeln!(out, "| --- | ---: | --- |");
	for accuracy in TRANSCENDENTAL_ACCURACY {
		let _ = writeln!(out, "| `{}` | {} | {} |", accuracy.operation, accuracy.max_ulp, accuracy.domain);
	}
	out
}
