//! `WSI_PROFILE_1.md`, generated from the window-system registries it specifies.
//!
//! THE PART OF A WINDOW SYSTEM THAT GOES WRONG IS NOT THE LIST OF CALLS. It is the numbers two sides
//! round differently and the states an implementation discovers it needed after shipping: a
//! fractional scale, the edge rule between neighbours, how many images a queue negotiates, what
//! happens to a frame that was accepted while visible and completes while occluded, and what
//! "displayed" means on a backend that cannot see a scanout. This document is those.

use std::fmt::Write as _;

use graphics_profile::wsi::{ACQUIRE_ANSWERS, AUTHORITATIVE_EXTENT, COLOUR_METADATA, COMPLETION_ATTENUATION, COMPLETION_DEPTH, COMPLETION_FACTS, COMPLETION_PAIRS, CONFIGURATION, CONFIGURATION_LIFECYCLE, DAMAGE_ROUNDING, DAMAGE_RULES, EDGE_RULE, EVENTS, FIFO_RULE, IMAGE_STATES, INPUT_MAPPING, MAX_DAMAGE_RECTS, MAX_IMAGES, MEMORY_VISIBILITY, MIN_IMAGES, NOT_IN_V1, PRESENT_MODES, PRESENT_OUTCOMES, RESERVED_PRESENT_MODES, SCALE_REPRESENTATION, TIMESTAMP_EVIDENCE, TIMING_CONTRACT, TIMING_OPTIONALITY, TRANSFORMS, TRANSITIONS, VISIBILITY_RULE};

/// The canonical machine-readable form the hash is taken over.
pub fn canonical() -> String {
	let mut out = String::new();
	let _ = writeln!(out, "profile=wsi version=1");
	let _ = writeln!(out, "scale representation={SCALE_REPRESENTATION} authoritative={AUTHORITATIVE_EXTENT}");
	let _ = writeln!(out, "edge-rule={EDGE_RULE}");
	let _ = writeln!(out, "damage-rounding={DAMAGE_ROUNDING}");
	let _ = writeln!(out, "input-mapping={INPUT_MAPPING}");
	let _ = writeln!(out, "transforms={}", TRANSFORMS.join(","));
	for field in CONFIGURATION {
		let _ = writeln!(out, "configuration={} invalidates-images={} why={}", field.name, field.invalidates_images, field.why);
	}
	let _ = writeln!(out, "configuration-lifecycle={CONFIGURATION_LIFECYCLE}");
	let _ = writeln!(out, "colour-metadata={}", COLOUR_METADATA.join(","));
	for event in EVENTS {
		let _ = writeln!(out, "event={} carries={} why={}", event.name, event.carries, event.why);
	}
	for state in IMAGE_STATES {
		let _ = writeln!(out, "image-state={} meaning={}", state.name, state.meaning);
	}
	for transition in TRANSITIONS {
		let _ = writeln!(out, "transition={} --{}--> {} why={}", transition.from, transition.event, transition.to, transition.why);
	}
	let _ = writeln!(out, "acquire-answers={}", ACQUIRE_ANSWERS.join(" | "));
	for outcome in PRESENT_OUTCOMES {
		let _ = writeln!(out, "present-outcome={} meaning={}", outcome.name, outcome.meaning);
	}
	let _ = writeln!(out, "fifo={FIFO_RULE}");
	let _ = writeln!(out, "present-modes={} reserved={}", PRESENT_MODES.join(","), RESERVED_PRESENT_MODES.join(","));
	let _ = writeln!(out, "images min={MIN_IMAGES} max={MAX_IMAGES}");
	for fact in COMPLETION_FACTS {
		let _ = writeln!(out, "completion-fact={} observable-today={} meaning={}", fact.name, fact.observable_today, fact.meaning);
	}
	let _ = writeln!(out, "timestamp-evidence={}", TIMESTAMP_EVIDENCE.join(","));
	let _ = writeln!(out, "timing={} optionality={}", TIMING_CONTRACT.join(","), TIMING_OPTIONALITY);
	let _ = writeln!(out, "max-damage-rects={MAX_DAMAGE_RECTS}");
	for rule in DAMAGE_RULES {
		let _ = writeln!(out, "damage={} answer={}", rule.question, rule.answer);
	}
	for pair in COMPLETION_PAIRS {
		let _ = writeln!(out, "completion-pair={} client={} service={}", pair.name, pair.client_rights, pair.service_rights);
	}
	let _ = writeln!(out, "completion depth={COMPLETION_DEPTH} attenuation={COMPLETION_ATTENUATION}");
	let _ = writeln!(out, "memory={MEMORY_VISIBILITY}");
	let _ = writeln!(out, "visibility={VISIBILITY_RULE}");
	let _ = writeln!(out, "not-in-v1={}", NOT_IN_V1.join(","));
	out
}

/// The document a person reads.
pub fn document(hash: &str) -> String {
	let mut out = String::from("<!-- @generated by profile-doc from the window-system registries. Do not edit; run `./gen.sh`. -->\n");
	let _ = writeln!(out, "# WSI Profile 1: surfaces, presentation and what comes back\n");
	let _ = writeln!(out, "Specification hash: `{hash}`\n");
	let _ = writeln!(out, "This is the contract between an application that draws and the service that puts what it drew on a");
	let _ = writeln!(out, "screen. Every number in it is one two sides round differently if it is not stated, and every state is");
	let _ = writeln!(out, "one an implementation discovers it needed after shipping.\n");

	let _ = writeln!(out, "## Logical, physical and the scale between them\n");
	let _ = writeln!(out, "A surface has THREE sizes and not one. A phone surface is 400 x 800 logical at scale 3.0 and");
	let _ = writeln!(out, "1200 x 2400 physical; an application that cannot see those as three numbers either renders at the");
	let _ = writeln!(out, "wrong size or renders blurred.\n");
	let _ = writeln!(out, "| question | answer |");
	let _ = writeln!(out, "| --- | --- |");
	let _ = writeln!(out, "| how the scale is represented | `{SCALE_REPRESENTATION}` |");
	let _ = writeln!(out, "| which extent is authoritative | {AUTHORITATIVE_EXTENT} |");
	let _ = writeln!(out, "| where an edge lands | {EDGE_RULE} |");
	let _ = writeln!(out, "| how damage rounds | {DAMAGE_ROUNDING} |");
	let _ = writeln!(out, "| how input maps back | {INPUT_MAPPING} |");
	let _ = writeln!(out, "\nThe output transforms are `{}`.\n", TRANSFORMS.join("`, `"));

	let _ = writeln!(out, "## The configuration snapshot\n");
	let _ = writeln!(out, "Configuration arrives as ONE snapshot, atomically. A client never applies a new scale with an old");
	let _ = writeln!(out, "extent, which is what atomic is for.\n");
	let _ = writeln!(out, "| field | invalidates images | why it is in the snapshot |");
	let _ = writeln!(out, "| --- | :---: | --- |");
	for field in CONFIGURATION {
		let _ = writeln!(out, "| {} | {} | {} |", field.name, if field.invalidates_images { "yes" } else { "no" }, field.why);
	}
	let _ = writeln!(out, "\nThe lifecycle is: {CONFIGURATION_LIFECYCLE}.\n");
	let _ = writeln!(out, "The colour information is `{}` - because a colour-space NAME is not enough to tone map with: a", COLOUR_METADATA.join("`, `"));
	let _ = writeln!(out, "conversion that does not know the destination's luminance is guessing at the one number that decides");
	let _ = writeln!(out, "how the image looks.\n");

	let _ = writeln!(out, "## Events\n");
	let _ = writeln!(out, "| event | carries | why it is its own event |");
	let _ = writeln!(out, "| --- | --- | --- |");
	for event in EVENTS {
		let _ = writeln!(out, "| `{}` | {} | {} |", event.name, event.carries, event.why);
	}
	let _ = writeln!(out, "\n{VISIBILITY_RULE}.\n");

	let _ = writeln!(out, "## The present queue\n");
	let _ = writeln!(out, "| state | meaning |");
	let _ = writeln!(out, "| --- | --- |");
	for state in IMAGE_STATES {
		let _ = writeln!(out, "| `{}` | {} |", state.name, state.meaning);
	}
	let _ = writeln!(out, "\n| from | on | to | why |");
	let _ = writeln!(out, "| --- | --- | --- | --- |");
	for transition in TRANSITIONS {
		let _ = writeln!(out, "| `{}` | {} | `{}` | {} |", transition.from, transition.event, transition.to, transition.why);
	}
	let _ = writeln!(out, "\nThe Rust shape is what makes the machine unrepresentable when wrong rather than merely documented:");
	let _ = writeln!(out, "`acquire_next` returns an OWNED acquired image, drawing borrows it, and `present` CONSUMES it - so");
	let _ = writeln!(out, "after presenting there is no safe path to the pixels until the queue hands them back.\n");
	let _ = writeln!(out, "`acquire_next` answers: {}.\n", ACQUIRE_ANSWERS.join("; "));
	let _ = writeln!(out, "Images are NEGOTIATED - the service advertises a minimum and a maximum, the client requests, the");
	let _ = writeln!(out, "service answers with the actual - and v1 advertises `min_images = {MIN_IMAGES}` and `max_images = {MAX_IMAGES}`. A");
	let _ = writeln!(out, "service free to answer one would turn the double-or-triple-buffering gate into a test of nothing.");
	let _ = writeln!(out, "The present modes are `{}`; `{}` have a PLACE rather than a meaning, so adding one later is not an", PRESENT_MODES.join("`, `"), RESERVED_PRESENT_MODES.join("` and `"));
	let _ = writeln!(out, "argument about what the enumeration was for.\n");

	let _ = writeln!(out, "## What a present is worth\n");
	let _ = writeln!(out, "{FIFO_RULE}.\n");
	let _ = writeln!(out, "| outcome | meaning |");
	let _ = writeln!(out, "| --- | --- |");
	for outcome in PRESENT_OUTCOMES {
		let _ = writeln!(out, "| `{}` | {} |", outcome.name, outcome.meaning);
	}
	let _ = writeln!(out, "\n\"Displayed\" runs three different facts together, and a backend that cannot observe the third says so:\n");
	let _ = writeln!(out, "| fact | observable on the current backend | meaning |");
	let _ = writeln!(out, "| --- | :---: | --- |");
	for fact in COMPLETION_FACTS {
		let _ = writeln!(out, "| {} | {} | {} |", fact.name, if fact.observable_today { "yes" } else { "no" }, fact.meaning);
	}
	let _ = writeln!(out, "\nA timestamp is reported as `{}`. {TIMING_OPTIONALITY}.\n", TIMESTAMP_EVIDENCE.join("`, `"));
	let _ = writeln!(out, "The frame loop is given `{}` rather than a clock to sleep on.\n", TIMING_CONTRACT.join("`, `"));

	let _ = writeln!(out, "## Damage\n");
	let _ = writeln!(out, "A bounded LIST of at most {MAX_DAMAGE_RECTS} rectangles with an explicit whole-surface fallback - not one rectangle,");
	let _ = writeln!(out, "because a client updating two corners of a screen would otherwise send their bounding box, which is");
	let _ = writeln!(out, "most of the screen. \"A small cap\" is not an ABI, so the cap is a number and every question a caller");
	let _ = writeln!(out, "asks at it has an answer:\n");
	let _ = writeln!(out, "| question | answer |");
	let _ = writeln!(out, "| --- | --- |");
	for rule in DAMAGE_RULES {
		let _ = writeln!(out, "| {} | {} |", rule.question, rule.answer);
	}

	let _ = writeln!(out, "\n## Completion\n");
	let _ = writeln!(out, "Two ordinary channel pairs per SURFACE, created once when the surface is admitted. No new kernel");
	let _ = writeln!(out, "object, no generic timeline, no ABI number and no signal right.\n");
	let _ = writeln!(out, "| pair | client | service |");
	let _ = writeln!(out, "| --- | --- | --- |");
	for pair in COMPLETION_PAIRS {
		let _ = writeln!(out, "| `{}` | {} | {} |", pair.name, pair.client_rights, pair.service_rights);
	}
	let _ = writeln!(out, "\n{COMPLETION_DEPTH}. {COMPLETION_ATTENUATION}.\n");
	let _ = writeln!(out, "{MEMORY_VISIBILITY}.\n");

	let _ = writeln!(out, "## What v1 does not contract\n");
	let _ = writeln!(out, "`{}` - each of them arrives with the compositor or with a capability the current backend does not", NOT_IN_V1.join("`, `"));
	let _ = writeln!(out, "have. Naming them is what stops an implementation inventing one and a client depending on it.\n");
	out
}
